### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by johnchen94** [HenriWahl/Nagstamon#1005]
Hello,

I'm having a issue with nagstamon.
I tried deleted everything a installing it again.
<img width="570" alt="image" src="https://github.com/HenriWahl/Nagstamon/assets/89012647/fce1679e-2f04-445c-8137-7bfe6d328816">

I launch the debug mod on it so i have something to show you the error.
ERROR: 2024-01-23 15:29:20.450586 Monitor server Traceback (most recent call last):
  File "Nagstamon\Servers\Centreon\CentreonAPI.py", line 778, in check_session
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Regards,
Jonathan

**Comment by BenoitPoulet** [comment]
Hello,

Please have a look at this bug #1002

It it doesn’t solve your problem :
Can you try to enable the debug mode (Setting > Servers) and post the output ?

🧨Don't forget to remove sensitive information, like hostname of Centreon, credentials, ....

**Comment by BenoitPoulet** [comment]
@HenriWahl 
I think you can close this ticket
