### ISSUE TITLE
Monitor name int instance

### ISSUE THREAD

**Issue by Hlovatskyi** [HenriWahl/Nagstamon#1010]
Hi! 
Nagstamon crashes when Monitor names are only numbers, I have created a few new servers with names 1, 2, and 3.  
Nagstamon v3.12, 3.8 and 3.13 were tested

:~$ nagstamon 
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 46, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 53, in <module>
    from Nagstamon.Servers import (SERVER_TYPES,
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/__init__.py", line 265, in <module>
    created_server = create_server(server)
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/__init__.py", line 230, in create_server
    new_server.Debug(server=server.name, debug="Created server.")
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 1682, in Debug
    debug_queue.append(' '.join(log_line))
TypeError: sequence item 2: expected str instance, int found

**Comment by HenriWahl** [comment]
Please check latest release 3.13-20240221.

**Comment by Hlovatskyi** [comment]
Fixed, thanks!
