### ISSUE TITLE
Updating nagstatmon from 3.10.1 to 3.14.0 breaks on Windows 2022

### ISSUE THREAD

**Issue by c3rberus** [HenriWahl/Nagstamon#1023]
I am using nagstatmon 3.10.1 x64 on Windows 2022 without issues.

When I try to get the latest 3.14.0 release, it fails to start with error below:

`
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 46, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 25, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ImportError: Module use of python310.dll conflicts with this version of Python.
`

Not sure why I get this error, I also noticed that the installer has increased 3x in size between 3.10 to 3.14, must be something significant.

Anyone have any ideas?

**Comment by ExeErik** [comment]
I have the same problem since the update but no solution yet. Uninstalling the existing Python version didn't help either.

**Comment by HenriWahl** [comment]
@c3rberus looks somewhat messy. The Python version bundled in 3.14 is 3.10 so I do not understand how this error message comes up: `Module use of python310.dll conflicts with this version of Python` 

How did you upgrade?

May a "fix" would be to uninstall, delete all likely existing folders in `C:\Progams\Nagstamon` and reinstall again.

**Comment by thedubo** [comment]
Had the same issue.
Uninstalling and deleting the Nasgtamon folder did the trick for me!

**Comment by Netfreak25** [comment]
Win 11 Pro - x64

Same happend to me today, not sure from which Verison I upgraded to 3.14

```
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 46, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 25, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ImportError: Module use of python310.dll conflicts with this version of Python.
```

Deleting the Installation folder followed by a reinstallation helped out also.

**Comment by HenriWahl** [comment]
Please check latest development version.
