### ISSUE TITLE
Crashes when Passwords for Monitoring-Servers change

### ISSUE THREAD

**Issue by froemra** [HenriWahl/Nagstamon#1083]
Nagstamon crashes at next start when Passwords for Monitoring Servers Change and Passwords are not changed in Nagstamon before.

Workaround ATM is not letting Nagstamon connect to Monitoring Servers (pull ethernet). Nagstamon then starts but cannot connect, but doesn`t crash. Then change Passwords in Nagstamon. Then Plugin Ethernet and it works hopefully ...

**Comment by netmax79** [comment]
I faced an issue which may be related. I tried to add an icinga 1.x server to a fresh install, after saving settings with password, nagstamon crashes. Any startup results in crash. After finding this issue i tried without saving the password
which brings me a bit further, but after setting some filters it still crashed and is more or less unusable right now.

I got the following crash output on commandline which may help:

`
username@console:~> nagstamon 
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
QThread: Destroyed while thread is still running
Abgebrochen (Speicherabzug geschrieben)
username@console:~> nagstamon 
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/Nagstamon/Config.py", line 580, in SaveConfig
    self.SaveMultipleConfig('servers', 'server')
  File "/usr/lib/python3.11/site-packages/Nagstamon/Config.py", line 623, in SaveMultipleConfig
    value = self.Obfuscate(self.__dict__[settingsdir][s].__dict__[option])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/Config.py", line 728, in Obfuscate
    string = string.encode()
             ^^^^^^^^^^^^^
AttributeError: '_PasswordRetriever' object has no attribute 'encode'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QThread: Destroyed while thread is still running
Abgebrochen (Speicherabzug geschrieben)
`
