### ISSUE TITLE
Nagstamon crashes on Checkmk Multisite recheck

### ISSUE THREAD

**Issue by moschlar** [HenriWahl/Nagstamon#1085]
Using Nagstamon 3.16.2 on Debian - clicking Recheck on a Service on a Checkmk Multisite generates this Stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 4320, in recheck
    self.server.set_recheck(info_dict)
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 413, in set_recheck
    self._set_recheck(info_dict['host'], info_dict['service'])
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Multisite.py", line 609, in _omd_set_recheck
    csrf_token = self._get_csrf_token(host, service)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Multisite.py", line 653, in _get_csrf_token
    csrf_token = self.fetch_url(self.urls["transid"].replace("$HOST$", host).replace("$SERVICE$", service.replace(" ", "+")), "obj").result.find(attrs={"name": "csrf_token"})["value"]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by HenriWahl** [comment]
Hi @moschlar - sorry for the late reply. This happens with context menu? I use Checkmk too but cant reproduce this.

**Comment by moschlar** [comment]
@HenriWahl Sorry, too! 😉 

Yes, Checkmk Enterprise Edition 2.3.0p24 FWIW.

Happens with your Debian-Package as well as mine from the Debian repository.

**Comment by moschlar** [comment]
(-:

**Comment by arthur-lbchn** [comment]
Hi guys, I have the same issue with CheckMK 2.3, clicking on Recheck cause

![Image](https://github.com/user-attachments/assets/fbc954b8-7282-48b1-b77e-283d853d8116)

I've enabled debug to file, but its empty for some reason.

Nagstamon version: 3.16.2

**Comment by HenriWahl** [comment]
Thanks for the fix!
