### ISSUE TITLE
Error on saving configuration with keyring-functionality enabled

### ISSUE THREAD

**Issue by neufeind** [HenriWahl/Nagstamon#153]
With version 1.0.1 on Linux I get the following error when saving the configuration (closing the configuration-dialog). This only happens when the keyring-functionality is activated.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Nagstamon/Config.py", line 596, in SaveMultipleConfig
    self.__dict__[settingsdir][s].proxy_password)
  File "/usr/lib/python2.7/site-packages/keyring/core.py", line 44, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python2.7/site-packages/keyring/backends/SecretService.py", line 62, in set_password
    collection = self.get_default_collection()
  File "/usr/lib/python2.7/site-packages/keyring/backends/SecretService.py", line 41, in get_default_collection
    collection = secretstorage.get_default_collection(bus)
  File "/usr/lib/python2.7/site-packages/secretstorage/collection.py", line 172, in get_default_collection
    'default', session)
  File "/usr/lib/python2.7/site-packages/secretstorage/collection.py", line 151, in create_collection
    dismissed, unlocked = exec_prompt_glib(bus, prompt)
  File "/usr/lib/python2.7/site-packages/secretstorage/util.py", line 119, in exec_prompt_glib
    from gi.repository import GLib
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 39, in <module>
    raise ImportError(_static_binding_error)
ImportError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

**Comment by HenriWahl** [comment]
Can you please check with the latest BETA versions of Nagstamon 2.0? The legacy 1.0 won't be touched anymore.

**Comment by HenriWahl** [comment]
Latest BETA 20160513 binaries available now: https://nagstamon.ifw-dresden.de/nagstamon-20/
