### ISSUE TITLE
Centreon 2.6.6 Timeout

### ISSUE THREAD

**Issue by feiltom** [HenriWahl/Nagstamon#178]
Hello,
i have a bug with my centreon check:
DEBUG: 2016-01-15 09:52:32.455620 Centreon Created server.
DEBUG: 2016-01-15 09:52:32.956024 Centreon FetchURL: https://centreon.************.fr/centreon/index.php?p=101&autologin=1&useralias=t.feillant&token=vK6Ru9lp CGI Data: None
DEBUG: 2016-01-15 09:52:34.388904 Centreon FetchURL: https://centreon.*************.fr/centreonmain.php CGI Data: {'sid': 'c4op8k20v2vdaajf2pfatuubg4', 'p': 201}
DEBUG: 2016-01-15 09:52:34.433269 Centreon FetchURL: https://centreon.**************.fr/centreon/include/monitoring/status/Hosts/xml/broker/hostXML.php?sid=c4op8k20v2vdaajf2pfatuubg4&sort_type=status&limit=9999&o=hpb&num=0 CGI Data: None
DEBUG: 2016-01-15 09:52:34.580023 Centreon FetchURL: https://centreon.***********.fr/centreon/include/monitoring/status/Services/xml/broker/serviceXML.php?sid=c4op8k20v2vdaajf2pfatuubg4&sort_type=status&limit=9999&o=svcpb&num=0 CGI Data: None
DEBUG: 2016-01-15 09:52:35.372639 Centreon FetchURL: https://centreon.********.fr/centreon/include/monitoring/status/Services/xml/broker/serviceXML.php?sid=c4op8k20v2vdaajf2pfatuubg4&sort_type=status&limit=9999&o=meta&num=0 CGI Data: None
DEBUG: 2016-01-15 09:52:39.182169 Centreon Open monitor web page https://centreon.****************.fr/centreon
ERROR: 2016-01-15 09:52:45.412626 Centreon Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
  File "/sw/lib/python3.4/http/client.py", line 1227, in getresponse
  File "/sw/lib/python3.4/http/client.py", line 386, in begin
  File "/sw/lib/python3.4/http/client.py", line 348, in _read_status
  File "/sw/lib/python3.4/socket.py", line 378, in readinto
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='centreon.******.fr', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hw5/Seafile/Nagstamon/Nagstamon/Nagstamon/Servers/Generic.py", line 1199, in FetchURL
  File "/sw/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
  File "/sw/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
  File "/sw/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
  File "/sw/lib/python3.4/site-packages/requests/adapters.py", line 433, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='centreon.*********.fr', port=443): Read timed out. (read timeout=10)

DEBUG: 2016-01-15 09:52:56.141953 Centreon Refreshing all hosts and services
DEBUG: 2016-01-15 09:52:56.423246 Centreon FetchURL: https://centreon.*****************.fr/centreon/include/monitoring/status/Hosts/xml/broker/hostXML.php?sid=c4op8k20v2vdaajf2pfatuubg4&sort_type=status&limit=9999&o=hpb&num=0 CGI Data: None
ERROR: 2016-01-15 09:53:06.458924 Centreon Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
  File "/sw/lib/python3.4/http/client.py", line 1227, in getresponse
  File "/sw/lib/python3.4/http/client.py", line 386, in begin
  File "/sw/lib/python3.4/http/client.py", line 348, in _read_status
  File "/sw/lib/python3.4/socket.py", line 378, in readinto
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='centreon.*************.fr', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hw5/Seafile/Nagstamon/Nagstamon/Nagstamon/Servers/Generic.py", line 1199, in FetchURL
  File "/sw/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
  File "/sw/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
  File "/sw/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
  File "/sw/lib/python3.4/site-packages/requests/adapters.py", line 433, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='centreon.*********************.fr', port=443): Read timed out. (read timeout=10)

DEBUG: 2016-01-15 09:53:06.459477 Centreon Start rechecking all
DEBUG: 2016-01-15 09:54:59.074231 Centreon FetchURL: https://centreon.****************.fr/centreon/include/monitoring/status/Hosts/xml/broker/hostXML.php?sid=c4op8k20v2vdaajf2pfatuubg4&sort_type=status&limit=9999&o=hpb&num=0 CGI Data: None
DEBUG: 2016-01-15 09:54:59.196333 Centreon FetchURL: https://centreon.****************.fr/centreon/include/monitoring/status/Services/xml/broker/serviceXML.php?sid=c4op8k20v2vdaajf2pfatuubg4&sort_type=status&limit=9999&o=svcpb&num=0 CGI Data: None
DEBUG: 2016-01-15 09:54:59.809285 Centreon FetchURL: https://centreon.********************.fr/centreon/include/monitoring/status/Services/xml/broker/serviceXML.php?sid=c4op8k20v2vdaajf2pfatuubg4&sort_type=status&limit=9999&o=meta&num=0 CGI Data: None
ERROR: 2016-01-15 09:55:09.845204 Centreon Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
  File "/sw/lib/python3.4/http/client.py", line 1227, in getresponse
  File "/sw/lib/python3.4/http/client.py", line 386, in begin
  File "/sw/lib/python3.4/http/client.py", line 348, in _read_status
  File "/sw/lib/python3.4/socket.py", line 378, in readinto
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
  File "/sw/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='centreon.******************.fr', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hw5/Seafile/Nagstamon/Nagstamon/Nagstamon/Servers/Generic.py", line 1199, in FetchURL
  File "/sw/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
  File "/sw/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
  File "/sw/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
  File "/sw/lib/python3.4/site-packages/requests/adapters.py", line 433, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='c****************', port=443): Read timed out. (read timeout=10).

I am with mac os 10.10.5 nagstatmon 2 (version 2016-01-12)
and a very large centurion config (600 server 15600 check )
Thanck

**Comment by HenriWahl** [comment]
Please check the latest 20160519 binaires from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by HenriWahl** [comment]
Please check latest 20160527 binaries from https://nagstamon.ifw-dresden.de/nagstamon-20/ which address the not-noticing-any-auth-problems problem.

**Comment by HenriWahl** [comment]
Might possibly be fixed with timeout parameter as in https://github.com/HenriWahl/Nagstamon/issues/191.

**Comment by HenriWahl** [comment]
Added timeout server option in latest commit - can you test from GitHub master or do you need a binary? If so, for which OS?

**Comment by feiltom** [comment]
ok for me now with nagstamon 1.0.1 and autologin.
Tanck you for job

**Comment by HenriWahl** [comment]
Can you check the 2.0 beta from https://nagstamon.ifw-dresden.de/nagstamon-20/ ?
