### ISSUE TITLE
OSX: Nagstamon crashes when starting with negative screen coordinates

### ISSUE THREAD

**Issue by tyhawk** [HenriWahl/Nagstamon#182]
Our department uses nagstamon to keep tabs on our 10+ nagios servers. With the new alpha version we are all running into the following issue.
We run a triple screen setup, where our laptop screen is the bottom screen and our 2 monitors are above the laptop screen. When we drag nagstamon to one of our upper screens, the Y coordinates become a negative number. When we close nagstamon and start it again, it crashes:
```
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Traceback (most recent call last):
  File "nagstamon-qt.py", line 39, in <module>
  File "/sw/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/sw/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/sw/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/sw/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/Users/hw5/Seafile/Nagstamon/Nagstamon/Nagstamon/QUI/__init__.py", line 4783, in <module>
  File "/Users/hw5/Seafile/Nagstamon/Nagstamon/Nagstamon/QUI/__init__.py", line 827, in __init__
  File "/Users/hw5/Seafile/Nagstamon/Nagstamon/Nagstamon/QUI/__init__.py", line 850, in set_mode
TypeError: arguments did not match any overloaded call:
  QWidget.move(QPoint): argument 1 has unexpected type 'int'
  QWidget.move(int, int): argument 2 has unexpected type 'str'
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
```
Workaround is to edit the file .nagstamon/nagstamon.conf and change:
`position_y = -1177`
If we change it to a positive number, Nagstamon works again.

It would be great if Nagstamon 2.0 would be able to handle negative screen positions in some way or another without crashing.

We have seen this behaviour on Mavericks, Yosemite and El Capitan.

**Comment by HenriWahl** [comment]
Interesting point... I will check this.

**Comment by tyhawk** [comment]
Awesome. Thanks!
We're happy to test any update you create based on this issue.

**Comment by HenriWahl** [comment]
Please check latest commit https://github.com/HenriWahl/Nagstamon/commit/75cef07704060e19513fac9ab27ee213d5b1ab94 or do you need a binary?

**Comment by tyhawk** [comment]
A binary would be nice!

**Comment by HenriWahl** [comment]
Please check https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0-alpha-20160128.dmg

**Comment by tyhawk** [comment]
I can confirm that you fixed the bug. Thanks for the very very quick fix!
