### ISSUE TITLE
Nagstamon2 reporting syntax error in master branch

### ISSUE THREAD

**Issue by thomasjamesgoin** [HenriWahl/Nagstamon#232]
```
~/repos/Nagstamon (master)$ python nagstamon.py
'newline' is an invalid keyword argument for this function
Traceback (most recent call last):
  File "nagstamon.py", line 47, in <module>
    from Nagstamon.QUI import (APP,
  File "/Users/thomas-jamesgoin/repos/Nagstamon/Nagstamon/QUI/__init__.py", line 472
    self.exec(QPoint(x, y))  # noqa
            ^
SyntaxError: invalid syntax
```

**Comment by HenriWahl** [comment]
Which Python version did you use? 
Does 'python' resolve to python2 or python3?

**Comment by thomasjamesgoin** [comment]
```
~/repos/Nagstamon/Nagstamon (master)$ python --version
Python 2.7.10
```

I have also tried with python3.5 and get a plugin installation error.
```
~/repos/Nagstamon/Nagstamon (master)$ python3.5 --version
Python 3.5.1
09:33:53-thomas-jamesgoin~/repos/Nagstamon (master)$ python3.5 nagstamon.py
Traceback (most recent call last):
  File "nagstamon.py", line 39, in <module>
    from Nagstamon.Helpers import lock_config_folder
  File "/Users/thomas-jamesgoin/repos/Nagstamon/Nagstamon/Helpers.py", line 26, in <module>
    import psutil
ImportError: No module named 'psutil'
```

**Comment by HenriWahl** [comment]
Only runs with Python3. You apparently miss the psutil module which should be available in your distro, named something like python3-psutil.

**Comment by HenriWahl** [comment]
Looks like you are on OSX. There I use Python3 and all the other requireded modules as described on https://nagstamon.ifw-dresden.de/nagstamon-20/ from the Fink Project http://www.finkproject.org/.
