### ISSUE TITLE
ImportError: No module named 'nagstacli'

### ISSUE THREAD

**Issue by micah** [HenriWahl/Nagstamon#246]
Hi,

I installed 2.0-beta-20160513 and when I try to run nagstamon, I get this:

```
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 24, in <module>
    import nagstacli
ImportError: No module named 'nagstacli'
```

**Comment by HenriWahl** [comment]
Which OS?m

**Comment by micah** [comment]
Debian sid/unstable

**Comment by HenriWahl** [comment]
I rebuild the package at the moment. I tell if it is ready.

**Comment by micah** [comment]
Ok, I'll wait

**Comment by HenriWahl** [comment]
OK its uploaded. You can check again.

**Comment by micah** [comment]
I just downloaded this one:
```
bdfe5322eb2e5e3c6d6e52fedf323734  nagstamon_2.0-beta-20160513_all.deb
```
and installed it, and same issue. 

Is this the right one?

**Comment by HenriWahl** [comment]
I see 4ae2efd7ff7db5bced9e762f9f28c68c  nagstamon_2.0-beta-20160513_all.deb

**Comment by HenriWahl** [comment]
Some caching in between?

**Comment by HenriWahl** [comment]
Check https://seafile.ifw-dresden.de/f/b1c2ff6fb2/?raw=1

**Comment by micah** [comment]
I reloaded the page, and got the deb with the md5sum that you indicated, I installed it, and now get this:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Config.py", line 594, in KeyringAvailable
    import secretstorage
ImportError: No module named 'secretstorage'
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 54, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 5992, in <module>
    dialogs = Dialogs()
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 3772, in __init__
    self.settings = Dialog_Settings(Ui_settings_main)
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 4112, in __init__
    self.toggle_toggles()
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 3921, in toggle_toggles
    self.signalmapper_toggles.mapped[str].connect(self.toggle)
TypeError: decorated slot has no signature compatible with mapped(QString)
```

**Comment by HenriWahl** [comment]
I built and tested on Debian 8 Jessie. This error you have there I saw on older Ubuntu. :-(

**Comment by micah** [comment]
Debian sid is pretty new/cutting edge packages. 

I was able to resolve the 'No Module named 'secretstorage' by installing the package python3-secretstorage, maybe the debian package should depend on that?

but it didn't make the decorated slot error go away

**Comment by HenriWahl** [comment]
The secretstorage only is necessary if credential storage in system keyring is wanted.
The other error... can you find out which version of Qt5 is on your machine?

**Comment by HenriWahl** [comment]
I will create me a sid machine and see what I can do there.

**Comment by micah** [comment]
Qt5 looks like 5.5.1. I've also got libqt4 4.8.7 installed, here are the related packages:

```
ii  libdbusmenu-qt5-2:amd64               0.9.3+16.04.20160218-1                            amd64        Qt implementation of the DBusMenu protocol
ii  libkf5dbusaddons-bin                  5.16.0-1                                          amd64        class library for qtdbus
ii  libkf5dbusaddons-data                 5.16.0-1                                          all          class library for qtdbus
ii  libkf5dbusaddons5:amd64               5.16.0-1                                          amd64        class library for qtdbus
ii  libmarblewidget-qt5-22                4:15.08.3-1.1                                     amd64        Marble globe widget library
ii  libphonon4qt5-4:amd64                 4:4.8.3-2                                         amd64        multimedia framework from KDE using Qt 5 - core library
ii  libpolkit-qt5-1-1:amd64               0.112.0-5                                         amd64        PolicyKit-qt5-1 library
ii  libqt4-dbus:amd64                     4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 D-Bus module
ii  libqt4-declarative:amd64              4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 Declarative module
ii  libqt4-designer:amd64                 4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 designer module
ii  libqt4-help:amd64                     4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 help module
ii  libqt4-network:amd64                  4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 network module
ii  libqt4-opengl:amd64                   4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 OpenGL module
ii  libqt4-script:amd64                   4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 script module
ii  libqt4-scripttools:amd64              4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 script tools module
ii  libqt4-sql:amd64                      4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 SQL module
ii  libqt4-sql-mysql:amd64                4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 MySQL database driver
ii  libqt4-sql-sqlite:amd64               4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 SQLite 3 database driver
ii  libqt4-svg:amd64                      4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 SVG module
ii  libqt4-test:amd64                     4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 test module
ii  libqt4-xml:amd64                      4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 XML module
ii  libqt4-xmlpatterns:amd64              4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 XML patterns module
ii  libqt5clucene5:amd64                  5.5.1-3                                           amd64        Qt 5 CLucene module
ii  libqt5core5a:amd64                    5.5.1+dfsg-16+b1                                  amd64        Qt 5 core module
ii  libqt5dbus5:amd64                     5.5.1+dfsg-16+b1                                  amd64        Qt 5 D-Bus module
ii  libqt5designer5:amd64                 5.5.1-3                                           amd64        Qt 5 designer module
ii  libqt5gui5:amd64                      5.5.1+dfsg-16+b1                                  amd64        Qt 5 GUI module
ii  libqt5help5:amd64                     5.5.1-3                                           amd64        Qt 5 help module
ii  libqt5multimedia5:amd64               5.5.1-4                                           amd64        Qt 5 Multimedia module
ii  libqt5multimedia5-plugins:amd64       5.5.1-4                                           amd64        Qt 5 Multimedia module plugins
ii  libqt5multimediawidgets5:amd64        5.5.1-4                                           amd64        Qt 5 Multimedia Widgets module
ii  libqt5network5:amd64                  5.5.1+dfsg-16+b1                                  amd64        Qt 5 network module
ii  libqt5opengl5:amd64                   5.5.1+dfsg-16+b1                                  amd64        Qt 5 OpenGL module
ii  libqt5printsupport5:amd64             5.5.1+dfsg-16+b1                                  amd64        Qt 5 print support module
ii  libqt5qml5:amd64                      5.5.1-3                                           amd64        Qt 5 QML module
ii  libqt5quick5:amd64                    5.5.1-3                                           amd64        Qt 5 Quick library
ii  libqt5script5:amd64                   5.5.1+dfsg-2                                      amd64        Qt 5 script module
ii  libqt5sql5:amd64                      5.5.1+dfsg-16+b1                                  amd64        Qt 5 SQL module
ii  libqt5sql5-sqlite:amd64               5.5.1+dfsg-16+b1                                  amd64        Qt 5 SQLite 3 database driver
ii  libqt5svg5:amd64                      5.5.1-2                                           amd64        Qt 5 SVG module
ii  libqt5test5:amd64                     5.5.1+dfsg-16+b1                                  amd64        Qt 5 test module
ii  libqt5webkit5:amd64                   5.5.1+dfsg-2+b1                                   amd64        Web content engine library for Qt
ii  libqt5widgets5:amd64                  5.5.1+dfsg-16+b1                                  amd64        Qt 5 widgets module
ii  libqt5x11extras5:amd64                5.5.1-3                                           amd64        Qt 5 X11 extras
ii  libqt5xcbqpa5                         5.5.1+dfsg-14                                     amd64        transitional dummy package for the XCB platform plugin
ii  libqt5xml5:amd64                      5.5.1+dfsg-16+b1                                  amd64        Qt 5 XML module
ii  libqtassistantclient4:amd64           4.6.3-7                                           amd64        Qt Assistant client library (runtime)
ii  libqtcore4:amd64                      4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 core module
ii  libqtdbus4:amd64                      4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 D-Bus module library
ii  libqtgui4:amd64                       4:4.8.7+dfsg-6+b1                                 amd64        Qt 4 GUI module
ii  libqtwebkit4:amd64                    2.3.4.dfsg-7                                      amd64        Web content engine library for Qt
rc  libquazip-qt5-1:amd64                 0.7-2                                             amd64        C++ wrapper wrapper for ZIP/UNZIP (Qt5 build)
ii  phonon4qt5:amd64                      4:4.8.3-2                                         amd64        multimedia framework from KDE using Qt 5 - metapackage
ii  phonon4qt5-backend-vlc:amd64          0.8.2-1                                           amd64        Phonon4Qt5 VLC backend
ii  pinentry-qt                           0.9.7-5                                           amd64        Qt-based PIN or pass-phrase entry dialog for GnuPG
ii  pinentry-qt4                          0.9.7-5                                           all          Qt-based PIN or pass-phrase entry dialog for GnuPG (transitional dummy package)
ii  python-pyqt5                          5.6+dfsg-1                                        amd64        Python 2 bindings for Qt5
ii  python-pyqt5.qtsvg                    5.6+dfsg-1                                        amd64        Python 2 bindings for Qt5's SVG module
ii  python-pyqt5.qtwebkit                 5.6+dfsg-1                                        amd64        Python 2 bindings for Qt5's WebKit module
ii  python-pyside.qtcore                  1.2.2-2+b1                                        amd64        Qt 4 core module - Python bindings
ii  python-pyside.qtdeclarative           1.2.2-2+b1                                        amd64        Qt 4 Declarative module - Python bindings
ii  python-pyside.qtgui                   1.2.2-2+b1                                        amd64        Qt 4 GUI module - Python bindings
ii  python-pyside.qthelp                  1.2.2-2+b1                                        amd64        Qt 4 help module - Python bindings
ii  python-pyside.qtnetwork               1.2.2-2+b1                                        amd64        Qt 4 network module - Python bindings
ii  python-pyside.qtopengl                1.2.2-2+b1                                        amd64        Qt 4 OpenGL module - Python bindings
ii  python-pyside.qtscript                1.2.2-2+b1                                        amd64        Qt 4 script module - Python bindings
ii  python-pyside.qtsql                   1.2.2-2+b1                                        amd64        Qt 4 SQL module - Python bindings
ii  python-pyside.qtsvg                   1.2.2-2+b1                                        amd64        Qt 4 SVG module - Python bindings
ii  python-pyside.qttest                  1.2.2-2+b1                                        amd64        Qt 4 test module - Python bindings
ii  python-pyside.qtuitools               1.2.2-2+b1                                        amd64        Qt 4 UI tools module - Python bindings
ii  python-pyside.qtwebkit                1.2.2-2+b1                                        amd64        Qt 4 WebKit module - Python bindings
ii  python-pyside.qtxml                   1.2.2-2+b1                                        amd64        Qt 4 XML module - Python bindings
ii  python-qt4                            4.11.4+dfsg-1+b3                                  amd64        Python bindings for Qt4
ii  python-qt4-dbus                       4.11.4+dfsg-1+b3                                  amd64        D-Bus Support for PyQt4
ii  python3-dbus.mainloop.pyqt5           5.6+dfsg-1                                        amd64        D-Bus Qt main loop support for Python 3
ii  python3-dbus.mainloop.qt              4.11.4+dfsg-1+b3                                  amd64        D-Bus Support for PyQt4 with Python 3
ii  python3-pyqt4                         4.11.4+dfsg-1+b3                                  amd64        Python3 bindings for Qt4
ii  python3-pyqt5                         5.6+dfsg-1                                        amd64        Python 3 bindings for Qt5
ii  python3-pyqt5.qtmultimedia            5.6+dfsg-1                                        amd64        Python 3 bindings for Qt5's Multimedia module
ii  python3-pyqt5.qtsvg                   5.6+dfsg-1                                        amd64        Python 3 bindings for Qt5's SVG module
ii  qt-at-spi:amd64                       0.4.0-3+b1                                        amd64        at-spi accessibility plugin for Qt
ii  qtchooser                             52-gae5eeef-2                                     amd64        Wrapper to select between Qt development binary versions
ii  qtcore4-l10n                          4:4.8.7+dfsg-6                                    all          Qt 4 core module translations
ii  qttranslations5-l10n                  5.5.1-2                                           all          translations for Qt 5
```

**Comment by HenriWahl** [comment]
Only Qt5 is important. All other OS also work with Qt 5.5 without problems.

**Comment by micah** [comment]
Hmm, ok. Let me know if there is something else I can test. Maybe I should try building nagstamon from source?

**Comment by HenriWahl** [comment]
It's all the same - the package consists of the plain python scripts. The problem with Ubuntu once was some incompatibility of the included Qt 5.3 with some code I used. I fixed it to be backward compatible but now in this case I am wondering about the normaly working version. When I managed to get a sid devel VM I will have a look there.
Anyways - did you got a previous Nagstamon 2.0  running?

**Comment by HenriWahl** [comment]
Please check https://seafile.ifw-dresden.de/f/a4b9840f18/

**Comment by micah** [comment]
> Please check https://seafile.ifw-dresden.de/f/a4b9840f18/

thanks, i will do so, but wont be able to until tomorrow! I'll let you
know as soon as I can.

**Comment by micah** [comment]
Hi, I installed the version you specified:

```
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 54, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 5994, in <module>
    dialogs = Dialogs()
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 3773, in __init__
    self.settings = Dialog_Settings(Ui_settings_main)
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 4114, in __init__
    self.toggle_toggles()
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 3923, in toggle_toggles
    self.signalmapper_toggles.mapped[str].connect(self.toggle)
TypeError: decorated slot has no signature compatible with mapped(QString)
$ md5sum nagstamon_2.0-beta-20160515_all.deb
6e71e7a94339748d657be36b4ce3d735  nagstamon_2.0-beta-20160515_all.deb
```

**Comment by taggart** [comment]
I just tried:
4ae2efd7ff7db5bced9e762f9f28c68c  nagstamon_2.0-beta-20160513_all.deb

on Debian jessie and it's working.

**Comment by HenriWahl** [comment]
Does the 20160515 work on Jessie?

**Comment by HenriWahl** [comment]
I am at creating a sid VM for testing this but dist-upgrade takes ages...

**Comment by taggart** [comment]
Ah I didn't see 0515! I just installed it and it works fine too.

**Comment by HenriWahl** [comment]
With sid?

**Comment by micah** [comment]
@taggart is on Debian Jessie, for me (i'm on Debian Sid), 0515 does not work

**Comment by HenriWahl** [comment]
Finally I have a stretchy sid... at least I can confirm the QString dilemma. Stay tuned...

**Comment by HenriWahl** [comment]
Well, there seems to be a problem with Qt5 5.6 included in sid and Python3. On other platforms I do not run into trouble with that versions but here at Debian sid I do. Maybe worth a bug report at the Debian PyQt5 packagers?

**Comment by micah** [comment]
That is a good idea. I'm not very skilled in Qt, or python, or I'd do the bug report myself. I'd be happy to help you make a bug report though!

**Comment by HenriWahl** [comment]
I do not find the the time at the moment so it would take longer. Please submit that bug yourself. I do not know more of Qt5, I just see the same symptoms as you - Sid version of Qt5 5.6 having problems with decoration signatures as in 
`TypeError: decorated slot has no signature compatible with mapped(QString)`
I tested by removing the error causing line but then it appears on other occurences of the decorator, regardless of QString or whatever being used. Just describe the error and its message to the Debian bug tracker - let's see what happens. Thanks!

**Comment by micah** [comment]
I've filed a bug with Debian about this issue, you can find it here: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824611

If you have any additional information to add, you can simply email 824611@bugs.debian.org, you do not need an account or to login.

**Comment by HenriWahl** [comment]
Great! Thank you. Could not have done it better... :-)

**Comment by HenriWahl** [comment]
Please check this fresh build with all necessary corrections included: https://seafile.ifw-dresden.de/f/0ea2421083/

**Comment by micah** [comment]
@HenriWahl when I go there, I get "File does not exist"

**Comment by HenriWahl** [comment]
Sorry, please grab latest from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by micah** [comment]
Ok, using 45cf9cb4970a6e4f2e51465a0e19a3ff  /tmp/nagstamon_2.0-beta-20160519_all.deb I get this:

```
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 54, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6007, in <module>
    statuswindow = StatusWindow()
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 963, in __init__
    self.servers_vbox.addLayout(self.create_ServerVBox(server))
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 1148, in create_ServerVBox
    server_vbox = ServerVBox(server, parent=self)
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 2492, in __init__
    self.table = TreeView(len(HEADERS) + 1 , 0, sort_column, sort_order, self.server, parent=parent)
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 2873, in __init__
    self.worker.data_array_sorted.connect(self.model().fill_data_array)
TypeError: decorated slot has no signature compatible with Worker.data_array_sorted[list]
```

**Comment by HenriWahl** [comment]
Never ending story... now I replaced the 20160519 with a new version.

**Comment by micah** [comment]
It works!!

**Comment by micah** [comment]
Although when I clicked on the nagstamon icon, it crashed:
```
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:793: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Warning: "Jack server not found"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 1305, in show_window_systrayicon
    self.show_window()
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 1366, in show_window
    deskid = self.ewmh.getCurrentDesktop()
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/ewmh.py", line 226, in getCurrentDesktop
    return self._getProperty('_NET_CURRENT_DESKTOP')[0]
TypeError: 'NoneType' object is not subscriptable
Aborted
```

**Comment by HenriWahl** [comment]
What desktop environment do you use?

**Comment by HenriWahl** [comment]
Pleade check https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/nagstamon_2.0-beta-20160520_all.deb which includes the latest workaround regarding your error.
Anyway it would be interesting which desktop environment you use.

**Comment by micah** [comment]
Hi, that seems to solve the problem for me!

I'm using xmonad, its a tiling window manager, like i3 or awesome. That might be why?

**Comment by micah** [comment]
Interestingly, when I click on the nagstamon icon, the window comes up, as I expect. But it only comes up if I am in the workspace where it was initially launched. I cannot bring up the window in any other workspace. I can bring up the context menu (right click) everywhere, but even if I select "Show status window" it doesn't appear in my workspace.... but if I switch to that original workspace, it is open there.

**Comment by HenriWahl** [comment]
This story grows and grows... but in this case I actually think I know what happens:
SOME desktop environments seem to have problems to keep the Nagstamon statusbar and thus the popup (see https://github.com/HenriWahl/Nagstamon/issues/197). The workaround was exactly this part of Nagstamon where you got the last crash when clicking on the systray icon. Therein the window is moved by telling the window manager to move it to the current desktop. The EWMH protocol is used here, which much window managers seem to understand. In your case xmonad seems not to do so... but there I found this http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Hooks-EwmhDesktops.html - maybe this helps. Otherwise I see nothing  I can do.

**Comment by micah** [comment]
Thanks for the explanation, I'll look into that more. I think this is unrelated to the original issue I filed at this point, and you've fixed that issue. So I'll go ahead and close this now, and see if I can figure out how to get that to work! Thanks a lot for your work on nagstamon and being so quick at responding, it really makes filing bugs worthwhile !

**Comment by varac** [comment]
I'm hit by the original issue:

```
 ~ $ nagstamon --output y
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 37, in <module>
    import nagstacli  # fix crash if more than 2 args are passed - mprenditore
ModuleNotFoundError: No module named 'nagstacli'
```

With wayland using sway 1.1rc (ubuntu 19.04 with nagstamon 3.2.1-1).

**Comment by HenriWahl** [comment]
Just do not add the arguments - at the moment Nagstamon only accepts an alternative config file.
