### ISSUE TITLE
Current HEAD broken

### ISSUE THREAD

**Issue by gtozzi** [HenriWahl/Nagstamon#258]
I have this error on startup after merging. The CREDITS file does not seem to exist. Did you forget to commit it? :)

$ LANG=C ./nagstamon.py
Traceback (most recent call last):
  File "./nagstamon.py", line 53, in <module>
    from Nagstamon.QUI import (APP,
  File "/var/www/nagstamon/Nagstamon/QUI/__init__.py", line 6184, in <module>
    dialogs = Dialogs()
  File "/var/www/nagstamon/Nagstamon/QUI/__init__.py", line 3904, in __init__
    self.about = Dialog_About(Ui_dialog_about)
  File "/var/www/nagstamon/Nagstamon/QUI/__init__.py", line 5796, in __init__
    credits_file = open('{0}{1}CREDITS'.format(RESOURCES, os.sep), encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/nagstamon/Nagstamon/resources/CREDITS'

**Comment by HenriWahl** [comment]
Thanks... here it is: https://github.com/HenriWahl/Nagstamon/commit/d393d6fe15c3587cb73130b4496dac33f89f4dd7
