### ISSUE TITLE
Nagstamon and centreon Centreon 2.7.4

### ISSUE THREAD

**Issue by aarcaz** [HenriWahl/Nagstamon#271]
Dear Colleagues

I can´t user Nagstamon for centreon 2.7.4.

Please could you recommend me witch version of Nagstamon must use? 
Right now i´m using Nagstamon 2.0-beta-20160601

The error problem was "Authentication Problem"
I´m user Authentication: "Basic" Timeout "10 second"

Also i tried with Save password checked and uncheck but same issue.

Regards

**Comment by HenriWahl** [comment]
Did it work with any version of Nagstamon (1 or 2)?

Can you enable debugging in settings and see what you will get there?

**Comment by HenriWahl** [comment]
Please check https://github.com/HenriWahl/Nagstamon/issues/165

**Comment by aarcaz** [comment]
Hi no work with any version 1 and 2.

This is the log about the bug mode. It´s seems a problem with the authentication but when i click on button for MONITOR i can open Centreon for web browser. I don´t know if this can help but we are very loose about this issue.

DEBUG: 2016-08-01 12:25:54.843014 CENTREON Created server.
DEBUG: Initing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003AD5048> for state "OK"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003AC1F78> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003AD50D8> for state "WARNING"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003AD5168> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003AD51F8> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003AD5288> for state "DOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003AD5318> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x0000000003AD53A8>
DEBUG: 2016-08-01 12:26:00.418304 CENTREON FetchURL: https://hyperion.eu.corp/centreon/main.php/index.php CGI Data: None
ERROR: 2016-08-01 12:26:00.418304 CENTREON Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1264, in FetchURL
AttributeError: 'NoneType' object has no attribute 'get'

DEBUG: 2016-08-01 12:26:00.418304 CENTREON Password login : ng55f7b : Pasword123.
ERROR: 2016-08-01 12:26:00.418304 CENTREON Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 201, in _get_sid
UnboundLocalError: local variable 'raw' referenced before assignment

DEBUG: 2016-08-01 12:26:00.433905 CENTREON FetchURL: https://hyperion.eu.corp/centreon/main.php/index.php CGI Data: None
DEBUG: 2016-08-01 12:26:01.042320 CENTREON FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
ERROR: 2016-08-01 12:26:01.135923 CENTREON Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 137, in _new_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 67, in create_connection
  File "c:\Python34\lib\socket.py", line 537, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 784, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 217, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 146, in _new_conn
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003F8C128>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 376, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 609, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 273, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003F8C128>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1292, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 480, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 468, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 576, in send
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 437, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003F8C128>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

ERROR: 2016-08-01 12:26:06.939271 CENTREON Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1264, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 480, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 468, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 597, in send
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 597, in <listcomp>
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

DEBUG: 2016-08-01 12:26:06.939271 CENTREON Error getting the home page : requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

DEBUG: 2016-08-01 12:26:06.939271 CENTREON FetchURL: https://hyperion.eu.corp/centreon/main.php/index.php CGI Data: None
ERROR: 2016-08-01 12:26:12.040602 CENTREON Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1264, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 480, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 468, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 597, in send
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 597, in <listcomp>
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

DEBUG: 2016-08-01 12:26:12.040602 CENTREON Password login : ng55f7b : Password123.
ERROR: 2016-08-01 12:26:12.040602 CENTREON Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 201, in _get_sid
UnboundLocalError: local variable 'raw' referenced before assignment

DEBUG: 2016-08-01 12:26:12.040602 CENTREON FetchURL: https://hyperion.eu.corp/centreon/main.php/include/monitoring/status/Hosts/xml/broker/hostXML.php?o=hpb&sid=ERROR&sort_type=status&num=0&limit=999 CGI Data: None
ERROR: 2016-08-01 12:26:17.656746 CENTREON Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1264, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 480, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 468, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 597, in send
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 597, in <listcomp>
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

DEBUG: 2016-08-01 12:26:40.122789 CENTREON Open monitor web page https://hyperion.eu.corp/centreon/main.php

**Comment by HenriWahl** [comment]
I for a first start fixed 
    ERROR: 2016-08-01 12:26:00.418304 CENTREON Traceback (most recent call last):
    File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 201, in _get_sid
    UnboundLocalError: local variable 'raw' referenced before assignment
in latest commit a41c040c0dd73ffe0e98724e33ebc1759bbcd488.
Are you able to test it directly from source or do you need a binary? If so, which one? Windows 32 or 64 bit?

**Comment by aarcaz** [comment]
@HenriWahl I can open correctly the program and also i can put my credentials. I´m use Windows 64 bit.

AS you can see on below image this is the error when i tried to connect. Please could you help me?
 [
![error](https://cloud.githubusercontent.com/assets/20596128/17296505/e361e912-5801-11e6-9b6b-996645d61246.PNG)
](url)

**Comment by HenriWahl** [comment]
Please check the latest beta - yours is from June.

Once doing this I might give you a binary where another bug is fixed - do you need 32 or 64 bit.

**Comment by aarcaz** [comment]
I need 64 bits please

**Comment by BenoitPoulet** [comment]
Hello,

any news Aarcaz ?

I just did some test on Centeon 2.7.6, password auth, basic auth. works fine.

And for you ?

**Comment by sujeiitosuspeito** [comment]
Good evening,
Give me the 32-bit executable that can also test.
Grateful.

**Comment by HenriWahl** [comment]
Setup.exe: https://seafile.ifw-dresden.de/f/cd8db06360/
Zip-file standalone: https://seafile.ifw-dresden.de/f/96061bf4cd/

**Comment by BenoitPoulet** [comment]
Please test with the lastest executable link by @HenriWahl .
If the error is still here, **try to enable debug log, and post the full log here.**

Please post also a screenshot of your server setting of Nagstamon with «show more option» ON.
(don't forget to mask sensitive data)

**Comment by aarcaz** [comment]
@BenoitPoulet Sorry for my late answer. Still yet facing problem, now a different one i will show you the DEBUG mode


DEBUG: 2016-08-09 13:59:51.176838 CENTREON Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003CC4048> for state "OK"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003CAFF78> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003CC40D8> for state "WARNING"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003CC4168> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003CC41F8> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003CC4288> for state "DOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003CC4318> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x0000000003CC43A8>
DEBUG: 2016-08-09 13:59:51.317240 CENTREON FetchURL: https://hyperion.corp/centreon/main.php?/index.php CGI Data: None
DEBUG: 2016-08-09 13:59:52.190851 CENTREON FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
ERROR: 2016-08-09 13:59:52.268852 CENTREON Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 67, in create_connection
  File "c:\Python34\lib\socket.py", line 537, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 351, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 814, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003D64DD8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 403, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 623, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 281, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003D64DD8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1292, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 487, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 475, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 585, in send
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 467, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003D64DD8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

DEBUG: 2016-08-09 13:59:52.752459 CENTREON Centreon version detected : 2.7
DEBUG: 2016-08-09 13:59:52.752459 CENTREON FetchURL: https://hyperion.corp/centreon/main.php?/index.php CGI Data: None
DEBUG: 2016-08-09 13:59:53.142464 CENTREON FetchURL: https://hyperion.corp/centreon/main.php?/index.php CGI Data: {'password': 'HELLO123', 'centreon_token': 'e3c363cf612527042bc7bd78a7e7d603', 'useralias': 'ng55f7b', 'submitLogin': 'Connect'}
DEBUG: 2016-08-09 13:59:53.532469 CENTREON Password login : ng55f7b : HELLO123
DEBUG: 2016-08-09 13:59:53.532469 CENTREON SID : oj1p99gqj67s8m2l6cuirf6a84
DEBUG: 2016-08-09 13:59:53.532469 CENTREON FetchURL: https://hyperion.corp/centreon/main.php?/include/monitoring/status/Hosts/xml/broker/hostXML.php?limit=999&sort_type=status&sid=oj1p99gqj67s8m2l6cuirf6a84&o=hpb&num=0 CGI Data: None
DEBUG: 2016-08-09 13:59:53.922474 CENTREON FetchURL: https://hyperion.corp/centreon/main.php?/include/monitoring/status/Services/xml/serviceXML.php?limit=999&sort_type=status&sid=oj1p99gqj67s8m2l6cuirf6a84&o=svcpb&num=0 CGI Data: None
DEBUG: 2016-08-09 13:59:54.312479 CENTREON FetchURL: https://hyperion.corp/centreon/main.php?/include/monitoring/status/Meta/xml/broker/metaServiceXML.php?limit=999&sort_type=status&sid=oj1p99gqj67s8m2l6cuirf6a84&o=meta&num=0 CGI Data: None
ERROR: 2016-08-09 13:59:54.702484 CENTREON Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 565, in _get_status
  File "c:\Python34\lib\site-packages\bs4\element.py", line 378, in append
  File "c:\Python34\lib\site-packages\bs4\element.py", line 312, in insert
ValueError: Cannot insert None into a tag.


Regarding "**Please post also a screenshot of your server setting of Nagstamon with «show more option» ON.(don't forget to mask sensitive data)**"

How can made? Where is this menu? On the client or on the web interface?

I hope your news

**Comment by BenoitPoulet** [comment]
Ok @aarcaz , it seems your workstation is unable to go on the internet to check if there is a new Nagstamon version. And it seems that is not handle very well by the program.

One thing : your nagios URL is wrong, it must be what you enter in your browser, as :  https://hyperion.corp/centreon/

@HenriWahl : How this part (New version check) is handled ? It must be in the Centreon class or elsewhere ?

**Comment by HenriWahl** [comment]
New links:
32 Bit Zip: https://seafile.ifw-dresden.de/f/560a490063/?raw=1
32 Bit Setup.exe: https://seafile.ifw-dresden.de/f/ebf5628b38/?raw=1
64 Bit Zip: https://seafile.ifw-dresden.de/f/1eb6d15c27/?raw=1
64 Bit Setup.exe: https://seafile.ifw-dresden.de/f/d801a9b146/?raw=1

@BenoitPoulet The new version is checked by CheckVersion thread in QUI.py using the FetchURL() from all configured servers which is inherited by Generic.py server and not changed in any server class - should have no impact to login or any other server interaction.

**Comment by sujeiitosuspeito** [comment]
@HenriWahl 
working 100% in Centreon 2.7.6.

thank you

**Comment by HenriWahl** [comment]
So I consider this now ready to be closed.
