### ISSUE TITLE
Segfault - AttributeError: 'StatusWindow' object has no attribute 'ewmh'

### ISSUE THREAD

**Issue by idl0r** [HenriWahl/Nagstamon#296]
Hi,

2.0 fails here sometimes because of the mentioned error. It also throws a segfault, likely because of it. I'm using "Awesome" as WM and nagstamon was located on the second screen, in case it's related.

``` 
% nagstamon
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/Nagstamon/Config.py", line 598, in KeyringAvailable
    import Nagstamon.thirdparty.keyring as keyring
ImportError: No module named 'Nagstamon.thirdparty.keyring'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/Nagstamon/QUI/__init__.py", line 1849, in raise_window_on_all_desktops
    self.ewmh.setWmDesktop(winid, 0xffffffff)
AttributeError: 'StatusWindow' object has no attribute 'ewmh'
[1]    24706 abort (core dumped)  nagstamon
```

The coredump is pretty useless I guess, because there are no debug symbols etc.

**Comment by HenriWahl** [comment]
Interesting. I did not test on any none-major WMs (just too much of them).
Some questions:
- it fails SOMETIMES???
- does Awesome foll the EWMH specification?
- do you run it from source or from package?

**Comment by idl0r** [comment]
> it fails SOMETIMES???
Yeah, well. It happens only when I've configured my nagstamon.
So starting with a default config, no server etc. works

> does Awesome foll the EWMH specification?
Not sure about that tbh

> do you run it from source or from package?
It's the distribution "package" I made for Gentoo, it's built from the source.

**Comment by HenriWahl** [comment]
According to their documentation they support EWMH... well, most pragmatically way would be to simply catch that error when it occurs and ignore it. I will check this out for a 2.0.1 bugfix release.

**Comment by idl0r** [comment]
It looks like EWMH has not been initialized at the time the error/exception occurs, while it seems to work sometimes. Right now, it looks like it happens as soon as I have >1 Icinga (tested with Icinga at least) enabled.

**Comment by idl0r** [comment]
Yup, raise_window_on_all_desktops is called before that:

```
        # create vbox for each enabled server
        for server in servers.values():
            if server.enabled:
                self.servers_vbox.addLayout(self.create_ServerVBox(server))

    ...
    ->create_ServerVBox->raise_window_on_all_desktops
```

```
From 8ea1a9336b6239ead43ea7c4b767052e10745fe8 Mon Sep 17 00:00:00 2001
From: Christian Ruppert <idl0r@gentoo.org>
Date: Wed, 31 Aug 2016 20:19:20 +0200
Subject: [PATCH] Initialize EWMH as soon as possible, #296

Signed-off-by: Christian Ruppert <idl0r@gentoo.org>
---
 Nagstamon/QUI/__init__.py | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/Nagstamon/QUI/__init__.py b/Nagstamon/QUI/__init__.py
index 930cb68..d41b786 100644
--- a/Nagstamon/QUI/__init__.py
+++ b/Nagstamon/QUI/__init__.py
@@ -898,6 +898,10 @@ class StatusWindow(QWidget):
         # immediately hide to avoid flicker on Windows and OSX
         self.hide()
 
+        # ewmh.py in thirdparty directory needed to keep floating statusbar on all desktops in Linux
+        if not platform.system() in NON_LINUX:
+            self.ewmh = EWMH()
+
         # avoid quitting when using Qt.Tool flag and closing settings dialog
         APP.setQuitOnLastWindowClosed(False)
 
@@ -1080,10 +1084,6 @@ class StatusWindow(QWidget):
         # start with priority 0 = lowest
         self.worker_thread.start(0)
 
-        # ewmh.py in thirdparty directory needed to keep floating statusbar on all desktops in Linux
-        if not platform.system() in NON_LINUX:
-            self.ewmh = EWMH()
-
         # finally show up
         self.set_mode()
 
-- 
2.7.3

```

**Comment by HenriWahl** [comment]
I assume it works now as expected?

**Comment by idl0r** [comment]
Yeah, that seems to work. I guess this issue can be closed then.

**Comment by HenriWahl** [comment]
OK I'll put this into 2.0.1.

**Comment by idl0r** [comment]
Thanks!
