### ISSUE TITLE
Nagstamon 2.0:  NameError: name 'DBusQtMainLoop' is not defined

### ISSUE THREAD

**Issue by Busindre** [HenriWahl/Nagstamon#315]
Problems with the new version of nagstamon.

**Problem**.
```
python 3.5 nagstamon.py

No DBus for desktop notification available.
Traceback (most recent call last):
  File "nagstamon.py", line 53, in <module>
    from Nagstamon.QUI import (APP,
  File "/home/XX/Nagstamon/Nagstamon/QUI/__init__.py", line 6255, in <module>
    dbus_connection = DBus()
  File "/home/XX/Nagstamon/Nagstamon/QUI/__init__.py", line 6086, in __init__
    dbus_mainloop = DBusQtMainLoop(set_as_default=True)
NameError: name 'DBusQtMainLoop' is not defined
```

**Python3 Modules.**
```
pip3 list

appdirs (1.4.0)
beautifulsoup4 (4.5.1)
Brlapi (0.6.5)
bs4 (0.0.1)
cffi (1.7.0)
cryptography (1.5)
Cython (0.24.1)
dbus-python (1.2.4)
dnspython3 (1.12.0)
idna (2.1)
iotop (0.6)
keyring (9.3.1)
livestreamer (1.12.2)
packaging (16.7)
pgpdump3 (1.5.2)
pip (8.1.2)
ply (3.9)
psutil (4.3.1)
pyasn1 (0.1.9)
pycparser (2.14)
pyOpenSSL (16.1.0)
pyparsing (2.1.9)
PyQt5 (5.7)
python-magic (0.4.10)
requests (2.10.0)
SecretStorage (2.3.1)
setuptools (27.1.2)
sip (4.18.1)
six (1.10.0)
```

**Python dbus Packages.**
```
pacman -Q | grep -i python | grep -i dbus

python-dbus 1.2.4-1
python-dbus-common 1.2.4-1
python2-dbus 1.2.4-1
```

**Comment by HenriWahl** [comment]
What distro is this? ArchLinux?
Apparently Nagstamon finds out there is no Qt5-based DBus connection possible but later on tries to use DBus - I did not ever run it on a non-DBus-desktop. Seems fixable.

**Comment by HenriWahl** [comment]
Can you please test latest source from 2.0.1 branch containing https://github.com/HenriWahl/Nagstamon/commit/a9f699f50a20ca06aa0169abadf94bff6330b22d?

**Comment by Busindre** [comment]
Yes, Archlinux. Perfect, that worked and now nagstamon runs OK.

Cheers!
