### ISSUE TITLE
(nagstamon 2.0 startup) No DBus for desktop notification available.

### ISSUE THREAD

**Issue by gabclim** [HenriWahl/Nagstamon#326]
Hi

When I start nagstamon 2.0 I get

[gabriel@pc-gabriel Downloads]$ nagstamon.py
No DBus for desktop notification available.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nagstamon-2.0-py3.4.egg/EGG-INFO/scripts/nagstamon.py", line 53, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3.4/site-packages/nagstamon-2.0-py3.4.egg/Nagstamon/QUI/__init__.py", line 6258, in <module>
    dialogs = Dialogs()
  File "/usr/lib/python3.4/site-packages/nagstamon-2.0-py3.4.egg/Nagstamon/QUI/__init__.py", line 3935, in __init__
    self.settings = Dialog_Settings(Ui_settings_main)
  File "/usr/lib/python3.4/site-packages/nagstamon-2.0-py3.4.egg/Nagstamon/QUI/__init__.py", line 4235, in __init__
    if not dbus_connection.connected:
AttributeError: 'DBus' object has no attribute 'connected'

[gabriel@pc-gabriel Downloads]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core

[gabriel@pc-gabriel Downloads]$ uname -a
Linux pc-gabriel.steady-sun.com 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I had to install all dependencies (mostly from source), but here I'm pretty much stuck.

**Comment by HenriWahl** [comment]
Please try latest commit of today of branch 2.0.1 which addresses some DBus-problems.

**Comment by gabclim** [comment]
Hi

Just tried it, there's no change.

[gabriel@pc-gabriel Downloads]$ python3 /usr/bin/nagstamon.py
No DBus for desktop notification available.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nagstamon-2.0-py3.4.egg/EGG-INFO/scripts/nagstamon.py", line 53, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3.4/site-packages/nagstamon-2.0-py3.4.egg/Nagstamon/QUI/__init__.py", line 6258, in <module>
    dialogs = Dialogs()
  File "/usr/lib/python3.4/site-packages/nagstamon-2.0-py3.4.egg/Nagstamon/QUI/__init__.py", line 3935, in __init__
    self.settings = Dialog_Settings(Ui_settings_main)
  File "/usr/lib/python3.4/site-packages/nagstamon-2.0-py3.4.egg/Nagstamon/QUI/__init__.py", line 4235, in __init__
    if not dbus_connection.connected:
AttributeError: 'DBus' object has no attribute 'connected'

**Comment by HenriWahl** [comment]
You still seem to use Nagstamon 2.0 - please check out branch 2.0.1.

**Comment by gabclim** [comment]
You were right, it works now (some warnings, but well, it starts and I can use it !)

THanks
