### ISSUE TITLE
Nagstamon crashes zabbix_api.py Connection timed out

### ISSUE THREAD

**Issue by YoSiJo** [HenriWahl/Nagstamon#337]
Nagstamon crashes after random running time.

`
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/zabbix_api.py", line 246, in do_request
    response = opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Nagstamon/QUI/__init__.py", line 3538, in get_status
    status = self.server.GetStatus()
  File "/usr/lib/python3.5/site-packages/Nagstamon/Servers/Generic.py", line 811, in GetStatus
    status = self._get_status()
  File "/usr/lib/python3.5/site-packages/Nagstamon/Servers/Zabbix.py", line 101, in _get_status
    self._login()
  File "/usr/lib/python3.5/site-packages/Nagstamon/Servers/Zabbix.py", line 65, in _login
    self.zapi.login(self.username, self.password)
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/zabbix_api.py", line 204, in login
    result = self.do_request(obj)
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/zabbix_api.py", line 255, in do_request
    if "Connection timed out" in e.message:
AttributeError: 'URLError' object has no attribute 'message'
`

**Comment by HenriWahl** [comment]
@mprenditore looks like an issue for the Zabbix department?

**Comment by mprenditore** [comment]
@HenriWahl Indeed, I found that problem too and I'm trying to find out a solution... But ATM I'm a little bit busy and it will take a bit.

**Comment by mprenditore** [comment]
a quick update... In my case the problem was due to the DNS/Proxy/Firewall... I have zabbix on private network and listening only at "http://zabbix.my.domain". 
I have a Sophos Proxy/Firewall between me and my router, so Sophos some times missed to resolve correctly "zabbix.my.domain" and that made the connection to timeout... 

As temporary fix I've added in "/etc/hosts" the line
10.0.1.1 zabbix.my.domain

And the connection timeout went away... 
I'm going to  fix that ASAP in the code...

@YoSiJo could you please try if that workaround works for you too?

**Comment by YoSiJo** [comment]
@mprenditore Not really. I have several zabbix instances and usually do not open to all the VPN connection. I want to use nagstamon I always have to build all connections, because it does not even start.

**Comment by mprenditore** [comment]
@YoSiJo you mean that you have multiple VPN and on each one there is a different zabbix and you need to open up all the VPN or nagstamon doesn't start?

BTW, I'm working on some fix about this... I hope to finish soon...

**Comment by mprenditore** [comment]
Should be fixed with the commit bb743e855a44803b7c651133cd1ddcd68dd4bab0
@YoSiJo could you check it please? Now should show you the error where there is the "last updated at ..."

**Comment by HenriWahl** [comment]
Assumed to be fixed.
