### ISSUE TITLE
Issue with Fedora 25 - wayland

### ISSUE THREAD

**Issue by anayrat** [HenriWahl/Nagstamon#342]
Hi,

Is nagstamon compatible with fedora 25? I have these errors when I start : 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/Xlib/xauth.py", line 43, in __init__
    raw = open(filename, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.Xauthority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 60, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3.5/site-packages/Nagstamon/QUI/__init__.py", line 6303, in <module>
    statuswindow = StatusWindow()
  File "/usr/lib/python3.5/site-packages/Nagstamon/QUI/__init__.py", line 904, in __init__
    self.ewmh = EWMH()
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/ewmh.py", line 50, in __init__
    self.display = _display or display.Display()
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/Xlib/support/connect.py", line 91, in get_auth
    return mod.get_auth(sock, dname, host, dno)
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/Xlib/support/unix_connect.py", line 105, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/lib/python3.5/site-packages/Nagstamon/thirdparty/Xlib/xauth.py", line 45, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 2] No such file or directory: '/home/user/.Xauthority'
```

**Comment by HenriWahl** [comment]
This exception is new to me but in general it kind of works but not really perfectly. I use it in standard XWayland mode. 
The error looks like you do not have a .Xauthority file which seems to be a requirement even for XWayland. Maybe just touch an empty .XAuthority file?
I will look into Wayland compatibility and necessary workarounds next year.

**Comment by mprenditore** [comment]
Sorry I forgot to reply to this question... 
Henry is right,you should just touch the file with the command:

touch ~/. Xauthority

I'm using it on Fedora 25 with Wayland and it works good... Just few warning but about the gtk library... Nothing serious...
