### ISSUE TITLE
missing dependency in ubuntu 16.04

### ISSUE THREAD

**Issue by madaxel** [HenriWahl/Nagstamon#371]
I installed 2.1.23 and on startup i get 
`$ nagstamon 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Config.py", line 622, in KeyringAvailable
    import secretstorage
ImportError: No module named 'secretstorage'
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 67, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 55, in <module>
    from Nagstamon.Servers import (SERVER_TYPES,
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/__init__.py", line 29, in <module>
    from Nagstamon.Servers.Nagios import NagiosServer
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Nagios.py", line 20, in <module>
    from Nagstamon.Servers.Generic import GenericServer
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 21, in <module>
    import requests_kerberos
ImportError: No module named 'requests_kerberos'`

after an
`apt-get install python3-requests-kerberos`
it worked again. Maybe just a missing dependency of the deb.
Thanks
Markus

**Comment by HenriWahl** [comment]
Thanks for the hint. New .deb is uploaded already.
