### ISSUE TITLE
[icingaweb2] Crashes when using basic auth

### ISSUE THREAD

**Issue by debfx** [HenriWahl/Nagstamon#378]
When Icinga Web 2 is configured to use http basic auth instead of the html form authentication, Nagstamon just crashes.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 3538, in get_status
    status = self.server.GetStatus()
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 805, in GetStatus
    self.init_HTTP()
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/IcingaWeb2.py", line 99, in init_HTTP
    form_inputs[form_input] = form.find('input', {'name': form_input})['value']
TypeError: 'NoneType' object is not subscriptable
```

Checking if `form.find('input', {'name': form_input})` is not None before trying to access `['value']` should fix this.

Tested with version 2.0.1

**Comment by ponchofiesta** [comment]
I assume it's the same problem as #341

**Comment by HenriWahl** [comment]
Tried to fix in latest commit - can you check with latest master?

**Comment by HenriWahl** [comment]
Considered fixed.
