### ISSUE TITLE
Icingaweb2 + AD = MutualAuthenticationError

### ISSUE THREAD

**Issue by FibreFoX** [HenriWahl/Nagstamon#397]
Hi there,

I'm experimenting with a new Icinga2+Icingaweb2 system and tried to add this to my AD-server. This worked (I can use Icinga2 through the browser with my AD-credentials normally) and now I wanted to have this listed inside Nagstamon.

When adding that server, I checked "`show more options`" and selected "`Authentication`" to "`Kerberos`", typed my normal credentials there and (like mentioned here https://github.com/HenriWahl/Nagstamon/issues/278) I checked "`Do not use cookie authentication`" too.

My local system is NOT connected with the AD, I'm connected via VPN doing some administration stuff from home.

Nagstamon-version: 2.1-20170323
icinga2: 2.6.3-1.stretch
icingaweb2: 2.4.1-2.stretch
local desktop system: Windows 10 64bit

```
DEBUG: 2017-07-07 21:05:57.663182 SOME_SERVER_ENTRY Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B5E8> for state "OK"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B558> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B678> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B708> for state "WARNING"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B798> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B828> for state "HIGH"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B8B8> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B948> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B9D8> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64BA68> for state "DOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64BAF8> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x00000210BA64B4C8>
DEBUG: 2017-07-07 21:05:57.883768 SOME_SERVER_ENTRY FetchURL: http://SOME_HOSTNAME/icingaweb2/authentication/login CGI Data: None
DEBUG: 2017-07-07 21:05:57.971000 SOME_SERVER_ENTRY FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
ERROR: 2017-07-07 21:05:57.971000 SOME_SERVER_ENTRY Traceback (most recent call last):
  File "c:\Nagstamon\Nagstamon\Servers\Generic.py", line 1353, in FetchURL
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 501, in get
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 488, in request
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 615, in send
  File "C:\Python36\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [302]>

DEBUG: 2017-07-07 21:05:57.972002 SOME_SERVER_ENTRY FetchURL: http://SOME_HOSTNAME/icingaweb2/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
ERROR: 2017-07-07 21:05:58.038813 SOME_SERVER_ENTRY Traceback (most recent call last):
  File "c:\Nagstamon\Nagstamon\Servers\Generic.py", line 1353, in FetchURL
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 501, in get
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 488, in request
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 615, in send
  File "C:\Python36\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [302]>

DEBUG: 2017-07-07 21:06:03.378594 SOME_SERVER_ENTRY Refreshing all hosts and services
DEBUG: 2017-07-07 21:06:04.047879 SOME_SERVER_ENTRY FetchURL: http://SOME_HOSTNAME/icingaweb2/authentication/login CGI Data: None
ERROR: 2017-07-07 21:06:04.153449 SOME_SERVER_ENTRY Traceback (most recent call last):
  File "c:\Nagstamon\Nagstamon\Servers\Generic.py", line 1353, in FetchURL
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 501, in get
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 488, in request
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 615, in send
  File "C:\Python36\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [302]>

DEBUG: 2017-07-07 21:06:04.153449 SOME_SERVER_ENTRY FetchURL: http://SOME_HOSTNAME/icingaweb2/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
ERROR: 2017-07-07 21:06:04.216120 SOME_SERVER_ENTRY Traceback (most recent call last):
  File "c:\Nagstamon\Nagstamon\Servers\Generic.py", line 1353, in FetchURL
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 501, in get
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 488, in request
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 615, in send
  File "C:\Python36\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [302]>

DEBUG: 2017-07-07 21:06:14.722058 SOME_SERVER_ENTRY Created server.
DEBUG: 2017-07-07 21:06:14.725065 SOME_SERVER_ENTRY FetchURL: http://SOME_HOSTNAME/icingaweb2/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
ERROR: 2017-07-07 21:06:14.832882 SOME_SERVER_ENTRY Traceback (most recent call last):
  File "c:\Nagstamon\Nagstamon\Servers\Generic.py", line 1353, in FetchURL
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 501, in get
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 488, in request
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 615, in send
  File "C:\Python36\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [302]>

DEBUG: 2017-07-07 21:06:15.812531 Saving configuration to file c:\users\user\.nagstamon\nagstamon.conf
DEBUG: 2017-07-07 21:06:15.832628 Saving configuration to file c:\users\user\.nagstamon\nagstamon.conf
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA699C18> for state "OK"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA699828> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA699D38> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B558> for state "WARNING"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B678> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B708> for state "HIGH"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B798> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B828> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B8B8> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B948> for state "DOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000210BA64B9D8> for state "ERROR"
DEBUG: 2017-07-07 21:06:15.847624 SOME_SERVER_ENTRY Refreshing all hosts and services
DEBUG: 2017-07-07 21:06:16.835744 SOME_SERVER_ENTRY FetchURL: http://SOME_HOSTNAME/icingaweb2/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
ERROR: 2017-07-07 21:06:16.916188 SOME_SERVER_ENTRY Traceback (most recent call last):
  File "c:\Nagstamon\Nagstamon\Servers\Generic.py", line 1353, in FetchURL
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 501, in get
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 488, in request
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 615, in send
  File "C:\Python36\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [302]>

DEBUG: 2017-07-07 21:06:21.513662 SOME_SERVER_ENTRY Refreshing all hosts and services
DEBUG: 2017-07-07 21:06:21.919210 SOME_SERVER_ENTRY FetchURL: http://SOME_HOSTNAME/icingaweb2/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
ERROR: 2017-07-07 21:06:21.999101 SOME_SERVER_ENTRY Traceback (most recent call last):
  File "c:\Nagstamon\Nagstamon\Servers\Generic.py", line 1353, in FetchURL
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 501, in get
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 488, in request
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 615, in send
  File "C:\Python36\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [302]>
```

Did I miss something?

**Comment by FibreFoX** [comment]
I changed my settings from "Kerberos" back to "Basic", and unchecked `Do not use cookie authentication`, it seems to work now.

Does this mean, when my Icingaweb2 is configured via LDAP-auth, that I do NOT need to set this inside my Nagstamon-client? Is there any documentation about this login-feature that I missed?

**Comment by HenriWahl** [comment]
Hi,
Kerberos authentication is rather experimental and not yet finished GUI-wise.
If your local system is not connected to the AD Kerberos could not work anyway. Nagstamon does not care how your monitor authenticates.

Regards

**Comment by FibreFoX** [comment]
Ah, okay, than I mis-interpreted this setting :) as this works without having set anything, this is not an issue for me anymore. Thanks for looking into this.
