### ISSUE TITLE
Config is not saved

### ISSUE THREAD

**Issue by ldellefemmine** [HenriWahl/Nagstamon#408]
Hello,
Nagstamon configs files are not created. Traceback is:
Traceback (most recent call last):
  File "/home/ldellefemmine/git/Nagstamon/Nagstamon/Config.py", line 506, in SaveConfig
    self.SaveMultipleConfig('servers', 'server')
  File "/home/ldellefemmine/git/Nagstamon/Nagstamon/Config.py", line 567, in SaveMultipleConfig
    if self.keyring_available and self.use_system_keyring:
AttributeError: 'Config' object has no attribute 'keyring_available'

**Comment by ldellefemmine** [comment]
If it's ok for you I will create a new PR with a fix

**Comment by HenriWahl** [comment]
I found this already and fixed it - thanks!

**Comment by ldellefemmine** [comment]
Thank you
