### ISSUE TITLE
2.1-20170825 - not enough values to unpack (expected 2, got 1) (followed by crash on refresh)

### ISSUE THREAD

**Issue by smeeus** [HenriWahl/Nagstamon#431]
Hi,

I made the silly mistake of upgrading my Centreon 2.7.8 to 2.8.11 without checking nagstamon compatibility and now I have issues running Nagstamon.

OS: Windows 10 x64
Centreon: 2.8.11
Nagstamon:
- Unstable 2.1-20170825 windows installer
- Master branch

I use a normal Centreon user without admin privileges, having language etc set, and using the autologin feature. This user has always been used in the past with previous version of both Nagstamon and Centreon.

When Nagstamon launches, I get the message 'not enough values to unpack (expected 2, got 1)' in the status where there are normally other messages like unreachable server etc. When Nagstamon refreshes status, either automatically or by pressing the refresh button, it crashes with the Windows messagebox 'Nagstamon has stopped working'. With automatic refreshes, I have observed that it may take 2 automatic refreshes, but not more then that.

Enabling the debug log does nothing, it remains empty.

I installed a development environment as described on the requirements page, and used the master branch to debug the application this way. This is the log that I get.

```
D:\Utility\Nagstamon-master>C:\python36\python.exe nagstamon.py
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
DEBUG: 2017-08-26 18:56:32.886993 Apollo public Created server.
DEBUG: 2017-08-26 18:56:32.886993 Apollo Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F103520708> for state "OK"
Traceback (most recent call last):
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F103520678> for state "INFORMATION"
  File "D:\Utility\Nagstamon-master\Nagstamon\Servers\Centreon.py", line 568, in _get_status
    self.new_hosts[str(l.hn.text)].attempt, self.new_hosts[str(l.hn.text)].status_type  = str(l.tr.text).split(' ')
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F103520798> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F103520828> for state "WARNING"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F1035208B8> for state "AVERAGE"
ValueError: not enough values to unpack (expected 2, got 1)
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F103520948> for state "HIGH"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F1035209D8> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F103520A68> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F103520AF8> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F103520B88> for state "DOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001F103520C18> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x000001F103520D38>
DEBUG: 2017-08-26 18:56:33.686062 Apollo FetchURL: http://192.168.5.1/centreon/index.php CGI Data: None
DEBUG: 2017-08-26 18:56:33.836839 Apollo Centreon version detected : 2.8
DEBUG: 2017-08-26 18:56:33.836839 Apollo FetchURL: http://192.168.5.1/centreon/index.php?p=101&autologin=1&useralias=*********&token=********* CGI Data: None
DEBUG: 2017-08-26 18:56:34.372780 Apollo Autologin : ********* : *********
DEBUG: 2017-08-26 18:56:34.372780 Apollo SID : i1h9hqnm75m09b96qjniav5v75
DEBUG: 2017-08-26 18:56:34.372780 Apollo Only Centreon Broker is supported in Centeon >= 2.7 so: XML_PATH=xml
DEBUG: 2017-08-26 18:56:34.373780 Apollo URLs defined for Centreon 2.8
DEBUG: 2017-08-26 18:56:34.390791 Apollo FetchURL: http://192.168.5.1/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=i1h9hqnm75m09b96qjniav5v75 CGI Data: None
ERROR: 2017-08-26 18:56:34.862823 Apollo Traceback (most recent call last):
  File "D:\Utility\Nagstamon-master\Nagstamon\Servers\Centreon.py", line 568, in _get_status
    self.new_hosts[str(l.hn.text)].attempt, self.new_hosts[str(l.hn.text)].status_type  = str(l.tr.text).split(' ')
ValueError: not enough values to unpack (expected 2, got 1)

DEBUG: 2017-08-26 18:56:36.861281 Apollo FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
DEBUG: 2017-08-26 18:57:34.907262 Apollo FetchURL: http://192.168.5.1/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=i1h9hqnm75m09b96qjniav5v75 CGI Data: None
DEBUG: 2017-08-26 18:57:36.294617 Apollo FetchURL: http://192.168.5.1/centreon/include/monitoring/status/Services/xml/serviceXML.php?num=0&limit=999&o=svcpb&p=20201&nc=0&criticality=0&statusService=svcpb&sSetOrderInMemory=1&sid=i1h9hqnm75m09b96qjniav5v75 CGI Data: None
Traceback (most recent call last):
  File "D:\Utility\Nagstamon-master\Nagstamon\Servers\Centreon.py", line 708, in _get_status
    self.new_hosts[str(l.hn.text)].services[str(l.sd.text)].status_type = str(l.ca.text).split(' ')
ValueError: not enough values to unpack (expected 2, got 1)
ERROR: 2017-08-26 18:57:36.601567 Apollo Traceback (most recent call last):
  File "D:\Utility\Nagstamon-master\Nagstamon\Servers\Centreon.py", line 708, in _get_status
    self.new_hosts[str(l.hn.text)].services[str(l.sd.text)].status_type = str(l.ca.text).split(' ')
ValueError: not enough values to unpack (expected 2, got 1)

Traceback (most recent call last):
  File "D:\Utility\Nagstamon-master\Nagstamon\QUI\__init__.py", line 3674, in get_status
    status = self.server.GetStatus()
  File "D:\Utility\Nagstamon-master\Nagstamon\Servers\Generic.py", line 940, in GetStatus
    if CriticalityIsFilteredOutByRE(host.criticality, conf):
AttributeError: 'GenericHost' object has no attribute 'criticality'
```

From this log I tried both url's in a browser and I can confirm data is generated. I can provide this data if needed.

**Comment by smeeus** [comment]
Hi again,

I've got some things solved, it turns out [switching to lxml](https://github.com/HenriWahl/Nagstamon/commit/a02ca6ad7ae8861bc98cf44fce71e4f20de1e5b5#diff-7a10ceb9d1c245f69ba02a67bb293785) is the culprit.

I have reverted the changes made in `Nagstamon/Servers/Generic.py` in the source I have and it works without issues now. On to get it to build on Windows so I don't have to run it from console :)

Please feel free to contact me if you need more data, I will be happy to provide it.

**Comment by HenriWahl** [comment]
I feared side-effects like that. Now it would be interesting if it could get to be working with Centreon and lxml.

**Comment by HenriWahl** [comment]
Can you find out what the lxml parsed BeautifulSoup looks like, compared to the html.parser parsed one?

**Comment by HenriWahl** [comment]
Fixed in https://github.com/HenriWahl/Nagstamon/commit/48fb573794dfd6252a91fb1c837608e525413b78

Binaries are going to be built right now - expect them soon at https://nagstamon.ifw-dresden.de/files/incoming/.

**Comment by smeeus** [comment]
I had look at your fix, it is one way to go :)

I sent you an email with the log files of lxml and html.parser output. I would rather not disclose some of the data, but hopefilly it can help you find a solution for lxml.
