### ISSUE TITLE
Nagstamon 3.0.1 win64 crashes after start

### ISSUE THREAD

**Issue by gilcot** [HenriWahl/Nagstamon#444]
Today I upgraded Nagstamon to version 3.0.1. Nagstamon shows a green icon after start and crashes immediately. Windows eventlog shows following information:
```
Nom du journal :Application
Source :       Application Error
Date :         22/09/2017 11:36:59
ID de l’événement :1000
Catégorie de la tâche :(100)
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   PC-18323
Description :
Nom de l’application défaillante Nagstamon.exe, version : 0.0.0.0, horodatage : 0x00000000
Nom du module défaillant : ucrtbase.DLL, version : 10.0.10586.788, horodatage : 0x5879ab76
Code d’exception : 0x40000015
Décalage d’erreur : 0x000000000006990f
ID du processus défaillant : 0x1a40
Heure de début de l’application défaillante : 0x01d33386539f510e
Chemin d’accès de l’application défaillante : C:\Program Files\Nagstamon\Nagstamon.exe
Chemin d’accès du module défaillant: C:\Windows\system32\ucrtbase.DLL
ID de rapport : 947b8c98-9f79-11e7-bb55-b8ca3acd4e7c
XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-09-22T09:36:59.000000000Z" />
    <EventRecordID>18183</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC-18323</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Nagstamon.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>ucrtbase.DLL</Data>
    <Data>10.0.10586.788</Data>
    <Data>5879ab76</Data>
    <Data>40000015</Data>
    <Data>000000000006990f</Data>
    <Data>1a40</Data>
    <Data>01d33386539f510e</Data>
    <Data>C:\Program Files\Nagstamon\Nagstamon.exe</Data>
    <Data>C:\Windows\system32\ucrtbase.DLL</Data>
    <Data>947b8c98-9f79-11e7-bb55-b8ca3acd4e7c</Data>
  </EventData>
</Event>
```
My Windows edition is 7 Professional.

**Comment by HenriWahl** [comment]
For whatever reason some people have problems with their old settings. Can you please rename or delete the C:\Users\<your name>\.nagstamon folder to see if it works then?

BTW, what version did you upgrade from?

**Comment by gilcot** [comment]
Hello @HenriWahl 

Good catch! The old settings where the causing the problem. :(   
My previous version was the latest 2.1 (I used to update to the latest stable, but didn't have give a try 3.0)   

As I came with an empty setting, I had to add back the Zabbix server (there're two others I'll config later). The resulting configuration file have parameters/properties/settings in different order (I shouldn't mind) and there are some new settings now:  ignore_cert, custom_cert_use, custom_cert_file, check_mk_view_hosts, check_mk_view_services, monitor_site.   
I don't know if missing one of them may make the programm hangs. Maybe, installation programm may add them (with default values) when they miss from the file?

Olso, the new configuration has new settings: close_details_clicking_somewhere, color_average_background, color_average_text, color_disaster_background, color_disaster_text, color_high_background, color_high_text, color_information_background, color_information_text, default_color_average_background, default_color_average_text, default_color_disaster_background, default_disaster_text, default_color_high_background, default_color_high_text, filter_all_average_services, filter_all_disaster_services, filter_all_high_services, filter_all_information_services, notify_if_average, notify_if_disaster, notify_if_high, notify_if_information, position_height, position_width, systray_offset, systray_offset_use, windowed.   
Same thing: installer should add them with default value if they are requiered later.   

After that, it works fine (still without all servers) until I start playing with settings: It hangs again... I haven't been able to found the guilty setting. I'll remove the nagstamon.conf so that it can be recreated with default and try to found what is causing that new crash.

**Comment by gilcot** [comment]
I'm back.

Before removing my `c:\users\<login>\.nagstamon\nagstamon.conf` I had an idea: I edited it and set
```ini
debug_mode = True
debug_to_file = True
debug_file = C:\Users\<login>\nagstamon.log
```
I was able to start it and it works until I went to the settings dialog and disabled debug. From there, it crashed and keep hanging when relaunched. I edited the file conf and set again `debug_mode = True` and it's OK.

**Comment by HenriWahl** [comment]
Actually new versions store new options automatically - that's why it is not clear why craching here.
If I understand you right now everything is OK ore still crashing when opening settings?

**Comment by gilcot** [comment]
If new versions act so that's great! Maybe something went wrong during the install process (even if I saw no message/warning) 

Yes, everything is OK ...with debug enabled (when I uncheck the box and save the dialog it hangs and keep doing so on restart, 'till a enable debug in conf' file) But there's nothing relevant in the log file (it's all about servers)

**Comment by HenriWahl** [comment]
Still sounds not perfect. Should work without debug enabled. Do you think you could run it from Python in a terminal/shell window to get some usable error message? Instructions how to create a Python environment for Nagstamon are at https://nagstamon.ifw-dresden.de/docs/requirements/. This would really help to understand this error.

**Comment by gilcot** [comment]
Houston, we have a problem...
![using Python 3.5 on Windows, pip cannot found PyQt5 at version 5.8.0](https://user-images.githubusercontent.com/27341580/30766074-2cb80486-9ff3-11e7-8422-b96e8fffdf0b.png)

**Comment by HenriWahl** [comment]
Cool, you try it... well, the Qt5 version 5.9 has some flaw under windows regarding the popup window - that's why I pinned the version to 5.8.
A difference is that I use Python 3.6 - can you try with that one? Otherwise just for testing the 5.9 might be ok as well, just remove the "==5.8.0" part.

**Comment by HenriWahl** [comment]
Just for your information: Python 3.6 makes it work.

**Comment by gilcot** [comment]
[They have 3.6 too](https://www.activestate.com/activepython/downloads). I've installed it, near 2.7 and 3.5, the same way I did for 3.5 (install path added, but no file association) But I can't make it works correctly
![pip failing with Python 3.6](https://user-images.githubusercontent.com/27341580/30773213-7769bd66-a06c-11e7-80d6-fcbd654df645.png)

With 3.5 I was able to install Qt5 module in version 5.9 
![dependencies installed with Python 3.5](https://user-images.githubusercontent.com/27341580/30773231-08a09958-a06d-11e7-9f38-7c081ab44e6e.png)

I'll test with the source zip found at https://github.com/HenriWahl/Nagstamon/archive/3.0.1.zip   
First, it's extracted on the second drive. I don't know what to do from there.
![how to launch from source?](https://user-images.githubusercontent.com/27341580/30773411-50e592f6-a070-11e7-9b8f-237df540cb59.png)

**Comment by gilcot** [comment]
Ok, I had to run the script named `nagstamon.py` ^^
```
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"user": "admin", "password":
"zabbix"}, "method": "user.login", "id": 0, "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"output": ["host", "ip", "status", "available", "error"
, "errors_from"], "filter": {}}, "method": "host.get", "id": 1, "auth": "7eb25a8
51e60ce7a541517dcd6f2f780", "jsonrpc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"output": ["host", "ip", "sta
tus", "available", "error", "errors_from"], "filter": {}}, "method": "host.get",
 "id": 1, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Sending: {"params": {}, "method": "apiinfo.version", "id": 2, "jsonrpc": "2.
0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {}, "method": "apiinfo.version
", "id": 2, "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"with_monitored_items": true, "output": "extend"}, "met
hod": "hostgroup.get", "id": 3, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jso
nrpc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"with_monitored_items": true,
 "output": "extend"}, "method": "hostgroup.get", "id": 3, "auth": "7eb25a851e60c
e7a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"monitored": true, "groupids": ["2", "4", "9", "10", "1
1", "20", "27", "28", "29", "30", "31", "32", "33", "34", "37", "38", "41", "42"
, "43", "44", "45", "46", "47", "48", "49", "50", "54", "56", "57"], "filter": {
"value": 1}, "sortfield": "lastchange", "withLastEventUnacknowledged": true, "sk
ipDependent": true}, "method": "trigger.get", "id": 4, "auth": "7eb25a851e60ce7a
541517dcd6f2f780", "jsonrpc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"monitored": true, "groupids"
: ["2", "4", "9", "10", "11", "20", "27", "28", "29", "30", "31", "32", "33", "3
4", "37", "38", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "54"
, "56", "57"], "filter": {"value": 1}, "sortfield": "lastchange", "withLastEvent
Unacknowledged": true, "skipDependent": true}, "method": "trigger.get", "id": 4,
 "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"expandData": true, "output": "extend", "expandDescript
ion": true, "selectHosts": "extend", "triggerids": ["32955", "41351", "43705", "
28012", "25810", "40679", "36058", "44935", "33683", "43733", "33678", "40550",
"25822", "38038", "28756", "43858", "35620", "35594", "41322", "29773", "28044",
 "17753"], "selectItems": "extend", "select_items": "extend"}, "method": "trigge
r.get", "id": 5, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonrpc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"expandData": true, "output":
 "extend", "expandDescription": true, "selectHosts": "extend", "triggerids": ["3
2955", "41351", "43705", "28012", "25810", "40679", "36058", "44935", "33683", "
43733", "33678", "40550", "25822", "38038", "28756", "43858", "35620", "35594",
"41322", "29773", "28044", "17753"], "selectItems": "extend", "select_items": "e
xtend"}, "method": "trigger.get", "id": 5, "auth": "7eb25a851e60ce7a541517dcd6f2
f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "29580", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 6, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonrp
c": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "29580", "selectAp
plications": "extend"}, "method": "item.get", "id": 6, "auth": "7eb25a851e60ce7a
541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "39728", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 7, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonrp
c": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "39728", "selectAp
plications": "extend"}, "method": "item.get", "id": 7, "auth": "7eb25a851e60ce7a
541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "39730", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 8, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonrp
c": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "39730", "selectAp
plications": "extend"}, "method": "item.get", "id": 8, "auth": "7eb25a851e60ce7a
541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "42272", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 9, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonrp
c": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "42272", "selectAp
plications": "extend"}, "method": "item.get", "id": 9, "auth": "7eb25a851e60ce7a
541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "42311", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 10, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "42311", "selectAp
plications": "extend"}, "method": "item.get", "id": 10, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "43246", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 11, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "43246", "selectAp
plications": "extend"}, "method": "item.get", "id": 11, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "44311", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 12, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "44311", "selectAp
plications": "extend"}, "method": "item.get", "id": 12, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "47962", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 13, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "47962", "selectAp
plications": "extend"}, "method": "item.get", "id": 13, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "48777", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 14, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "48777", "selectAp
plications": "extend"}, "method": "item.get", "id": 14, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "48785", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 15, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "48785", "selectAp
plications": "extend"}, "method": "item.get", "id": 15, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "51135", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 16, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "51135", "selectAp
plications": "extend"}, "method": "item.get", "id": 16, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "51168", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 17, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "51168", "selectAp
plications": "extend"}, "method": "item.get", "id": 17, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "51741", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 18, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "51741", "selectAp
plications": "extend"}, "method": "item.get", "id": 18, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "53868", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 19, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "53868", "selectAp
plications": "extend"}, "method": "item.get", "id": 19, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "56902", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 20, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "56902", "selectAp
plications": "extend"}, "method": "item.get", "id": 20, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "32312", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 21, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "32312", "selectAp
plications": "extend"}, "method": "item.get", "id": 21, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "57817", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 22, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "57817", "selectAp
plications": "extend"}, "method": "item.get", "id": 22, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "57852", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 23, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "57852", "selectAp
plications": "extend"}, "method": "item.get", "id": 23, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "61052", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 24, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "61052", "selectAp
plications": "extend"}, "method": "item.get", "id": 24, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "61080", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 25, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "61080", "selectAp
plications": "extend"}, "method": "item.get", "id": 25, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "61402", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 26, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "61402", "selectAp
plications": "extend"}, "method": "item.get", "id": 26, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
20: Creating ZabbixAPISubClass
INFO:zabbix_api.ZabbixAPISubClass:20: Creating ZabbixAPISubClass
20: Sending: {"params": {"itemids": "63381", "selectApplications": "extend"}, "m
ethod": "item.get", "id": 27, "auth": "7eb25a851e60ce7a541517dcd6f2f780", "jsonr
pc": "2.0"}
INFO:zabbix_api.ZabbixAPI:20: Sending: {"params": {"itemids": "63381", "selectAp
plications": "extend"}, "method": "item.get", "id": 27, "auth": "7eb25a851e60ce7
a541517dcd6f2f780", "jsonrpc": "2.0"}
20: Response Code: 200
INFO:zabbix_api.ZabbixAPI:20: Response Code: 200
Traceback (most recent call last):
  File "d:\Nagstamon-3.0.1\Nagstamon\QUI\__init__.py", line 3710, in get_status
    status = self.server.GetStatus()
  File "d:\Nagstamon-3.0.1\Nagstamon\Servers\Generic.py", line 1172, in GetStatu
s
    self.informations += 1
AttributeError: 'ZabbixServer' object has no attribute 'informations'
``` 
It's like the root cause is with _Zabbix_ results parsing with my settings
![capture of last part of the console](https://user-images.githubusercontent.com/27341580/30773545-1a5d881c-a073-11e7-8b33-d709792fe925.png)

**Comment by HenriWahl** [comment]
Obviuosly a typo, must be self.information instead of self.informations. I fixed it in the latest master commit - just try again with that one!

**Comment by HenriWahl** [comment]
I compiled a new binary - please check one of https://nagstamon.ifw-dresden.de/files/incoming.

**Comment by gilcot** [comment]
Hello.   
Sorry, I finally went on week-end and seeing your replies only that monday morning. 

At 11AM CEST today, I grab the [latest source zip](https://github.com/HenriWahl/Nagstamon/archive/master.zip) and extract it onto my D: drive
![launching it in console](https://user-images.githubusercontent.com/27341580/30801785-ab724e60-a1e4-11e7-9147-20bf9a762a4d.png)    
It has been working like a charm :) thanks. 

Now I've downloaded [today's compilation](https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon-3.1-20170925-win64_setup.exe) Unofunally the antivirus doesn't let let the update complete 
![image](https://user-images.githubusercontent.com/27341580/30802151-dd879d64-a1e5-11e7-8020-a0bb92387a01.png)   
(hopefully, for me, the catch came when the installer try to clean up)

Many thanks for being so reactive.

**Comment by HenriWahl** [comment]
Cool to hear it works. Bad to hear the antivirus complaints... what antivirus software is this?

**Comment by gilcot** [comment]
> what antivirus software is this?
_Trend Micro_ Security Agent (I can't say about the version and the settings / rules because It's installed by the corporation and I can access only my local logs)    
The complain was about the signature: I dunno what are valid ones and why it dislike this one (I think it's the same algorithm as usual but it used to accept the previous installers)
