### ISSUE TITLE
Unable to launch Nagstamon .When i run Nagstamon.exe i see no activity . 

### ISSUE THREAD

**Issue by rajeshvshalgar** [HenriWahl/Nagstamon#475]
Recently after updating nagstamon to latest version i am unable to launch Nagstamon . 
I am using windows 7 64 bits 

when downloaded debug.zip and seeing below errors . 

C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug>rem initially clone

C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug>git\bin\git clone https://github.com/HenriWahl/Nagstamon.git
fatal: destination path 'Nagstamon' already exists and is not an empty directory.

C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug>cd Nagstamon

C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon>rem just make sure to get the latest release

C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon>..\git\bin\git pull
Already up-to-date.

C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon>..\python36\python nagstamon.py
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Traceback (most recent call last):
  File "nagstamon.py", line 47, in <module>
    from Nagstamon.QUI import (APP,
  File "C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__init__.py", line 6619, in <module>
    statuswindow = StatusWindow()
  File "C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__init__.py", line 1094, in __init__
    self.create_ServerVBoxes()
  File "C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__init__.py", line 1403, in create_ServerVBoxes
    self.servers_vbox.addLayout(self.create_ServerVBox(server))
  File "C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__init__.py", line 1305, in create_ServerVBox
    if not conf.servers[server.name].save_password and\
KeyError: 'INTEGRATION'

C:\Users\XXXXXX\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon>pause
Press any key to continue . . .

**Comment by HenriWahl** [comment]
Hi,
the word "integration" does not appear in the code... so I wonder how you got in into there. Can you please try to start with an empty configuration?

**Comment by rajeshvshalgar** [comment]
Hi HenriWahl , 
Thanks for help .Its working now after i deleted ./nagstamon from my profile . 
Thank you again ..:)
