### ISSUE TITLE
Crash when rechecking a silenced alert 

### ISSUE THREAD

**Issue by mlachal** [HenriWahl/Nagstamon#497]
Hello,

I use nagstamon_3.0.2_all.deb with a Sensu/Uchiwa server.
Everytime I silence an alert in Uchiwa then click 'Recheck all' in Nagstamon it crashes.
'Recheck all' works the rest of the time.

Here is the error stack :
``
WARNING:Nagstamon.thirdparty.sensu_api:404: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 3981, in recheck_all
    self.server.set_recheck({'host': service.host, 'service': service.name})
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Sensu.py", line 199, in set_recheck
    self.sensu_api.post_check_request(info_dict['service'], self._format_client_subscription(info_dict['host']))
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/sensu_api.py", line 196, in post_check_request
    self._request('POST', '/request', data=json.dumps(data))
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/sensu_api.py", line 94, in _request
    raise SensuAPIException('API bad response {}: {}'.format(resp.status_code, resp.text))
Nagstamon.thirdparty.sensu_api.SensuAPIException: API bad response 404:
Aborted
``
Thank you for your help,

Mikaël

**Comment by HenriWahl** [comment]
Please test with current version 3.6.0.

**Comment by mlachal** [comment]
Hi, I just tried it with 3.6.0 : silencing an alert then recheck all, and Nagstamon didn't crash.
Thank you
