### ISSUE TITLE
Not autorised against Zabbix after IP address changed

### ISSUE THREAD

**Issue by ruzaq** [HenriWahl/Nagstamon#500]
Hi!

I am using nagstamon against Zabbix and found out anytime I suspend my laptop, move to new location (and got new IP address) nagstamon's connection fails with "not authorised" in JSON reply.

ERROR: 2018-06-27 01:40:38.379626 MyZabbix Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 124, in _get_status
    {"output": ["host", "name", "proxy_hostid", "status", "available", "error", "errors_from","maintenance_status"], "selectInterfaces": ["ip"], "filter": {}
})
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 333, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 340, in do_request
    return self.parent.do_request(req)
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 290, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: ('Error -32602: Invalid params., Not authorised. while sending {"jsonrpc": "2.0", "method": "host.get", "params": {"output": ["host", "name", "proxy_hostid", "status", "available", "error", "errors_from", "maintenance_status"], "selectInterfaces": ["ip"], "filter": {}}, "auth": "", "id": 111}', -32602)

I've tried nagstamon stable (3.0.2) and even 3.1-20180523 (since there have been some fixes announced in changelog) and the behaviour is the same.

The only way to fix it is to disable specific Zabbix server in Nagstamon a re-enables it again.

Expected behaviour would be to detect auth problem and start new login/session.

**Comment by HenriWahl** [comment]
What about latest release?

**Comment by mowgli** [comment]
I encounter the same with version 3.4.1

Connection to old zabbix still work but to zabbix server version 4.0.4 I get the following message. It worked in the begin for several days but now it broke.
```
ERROR: 2020-06-10 12:27:18.997024 DSW neu Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 124, in _get_status
    hosts = self.zapi.host.get({"output": ["hostid", "host", "name", "status", \
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 333, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 340, in do_request
    return self.parent.do_request(req)
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 290, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: ('Error -32602: Invalid params., Session terminated, re-login, please. while sending {"jsonrpc": "2.0"
, "method": "host.get", "params": {"output": ["hostid", "host", "name", "status", "available", "error", "errors_from", "snmp_available", "snmp_error", "snmp_errors_from", "ipmi_available", "ipmi_error", "ipmi_errors_from", "jmx_available", "jmx_error", "jmx_errors_from", "maintenance_status", "maintenance_from"], "selectInterfaces": ["ip"], "filter": {}}, "auth": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "id": xx}', -32602)
```

**Comment by hyperman1** [comment]
I assume this is another variant of issue #650
