### ISSUE TITLE
Ubuntu 18.04 issue

### ISSUE THREAD

**Issue by uniwes23** [HenriWahl/Nagstamon#512]
Hi all,

i try to run nagstamon on Ubuntu 18.04. But i get following exception:

```
root@magic:/home/btyka/Downloads# nagstamon 
[Errno 2] No such file or directory: '/root/.nagstamon/nagstamon.pid'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6436, in __init__
    '/org/freedesktop/Notifications')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 47, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6615, in <module>
    statuswindow = StatusWindow()
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 961, in __init__
    self.ewmh = EWMH()
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/ewmh.py", line 50, in __init__
    self.display = _display or display.Display()
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'
root@magic:/home/btyka/Downloads# 
```

What can i do?
Regards
Bart

**Comment by uniwes23** [comment]
> You are running as root, but looks like you are logged in as another user (bytka?) in your desktop.

Yes I run the desktop as user btyka

**Comment by HenriWahl** [comment]
The error results from running as root - just a X permissions problem. Just run nagstamon as user btyka and everything should be fine.
