### ISSUE TITLE
Handle connection errors gracefully

### ISSUE THREAD

**Issue by varac** [HenriWahl/Nagstamon#523]
Please handle connection errors like this one more gracefully, it's not nice to have so long tracebacks in the logs multiple times a day:

```
Dec  9 11:49:22: Traceback (most recent call last):
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
Dec  9 11:49:22:     cnx.do_handshake()
Dec  9 11:49:22:   File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1907, in do_handshake
Dec  9 11:49:22:     self._raise_ssl_error(self._ssl, result)
Dec  9 11:49:22:   File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1614, in _raise_ssl_error
Dec  9 11:49:22:     raise WantReadError()
Dec  9 11:49:22: OpenSSL.SSL.WantReadError
Dec  9 11:49:22: During handling of the above exception, another exception occurred:
Dec  9 11:49:22: Traceback (most recent call last):
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
Dec  9 11:49:22:     self._validate_conn(conn)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
Dec  9 11:49:22:     conn.connect()
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
Dec  9 11:49:22:     ssl_context=context)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
Dec  9 11:49:22:     return context.wrap_socket(sock, server_hostname=server_hostname)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 456, in wrap_socket
Dec  9 11:49:22:     raise timeout('select timed out')
Dec  9 11:49:22: socket.timeout: select timed out
Dec  9 11:49:22: During handling of the above exception, another exception occurred:
Dec  9 11:49:22: Traceback (most recent call last):
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
Dec  9 11:49:22:     timeout=timeout
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
Dec  9 11:49:22:     _stacktrace=sys.exc_info()[2])
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
Dec  9 11:49:22:     raise six.reraise(type(error), error, _stacktrace)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
Dec  9 11:49:22:     raise value
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Dec  9 11:49:22:     chunked=chunked)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
Dec  9 11:49:22:     self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
Dec  9 11:49:22:     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
Dec  9 11:49:22: urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='icinga.shared.plainhost.net', port=443): Read timed out. (read timeout=10)
Dec  9 11:49:22: During handling of the above exception, another exception occurred:
Dec  9 11:49:22: Traceback (most recent call last):
Dec  9 11:49:22:   File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 1370, in FetchURL
Dec  9 11:49:22:     response = self.session.get(url, timeout=self.timeout)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
Dec  9 11:49:22:     return self.request('GET', url, **kwargs)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
Dec  9 11:49:22:     resp = self.send(prep, **send_kwargs)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
Dec  9 11:49:22:     r = adapter.send(request, **kwargs)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
Dec  9 11:49:22:     raise ReadTimeout(e, request=request)
Dec  9 11:49:22: requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='icinga.shared.plainhost.net', port=443): Read timed out. (read timeout=10)
Dec  9 11:49:22: Traceback (most recent call last):
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
Dec  9 11:49:22:     (self._dns_host, self.port), self.timeout, **extra_kw)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
Dec  9 11:49:22:     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Dec  9 11:49:22:   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
Dec  9 11:49:22:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Dec  9 11:49:22: socket.gaierror: [Errno -2] Name or service not known
Dec  9 11:49:22: During handling of the above exception, another exception occurred:
Dec  9 11:49:22: Traceback (most recent call last):
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Dec  9 11:49:22:     chunked=chunked)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
Dec  9 11:49:22:     self._validate_conn(conn)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
Dec  9 11:49:22:     conn.connect()
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
Dec  9 11:49:22:     conn = self._new_conn()
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
Dec  9 11:49:22:     self, "Failed to establish a new connection: %s" % e)
Dec  9 11:49:22: urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1c2a799710>: Failed to establish a new connection: [Errno -2] Name or service not known
Dec  9 11:49:22: During handling of the above exception, another exception occurred:
Dec  9 11:49:22: Traceback (most recent call last):
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
Dec  9 11:49:22:     timeout=timeout
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
Dec  9 11:49:22:     _stacktrace=sys.exc_info()[2])
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
Dec  9 11:49:22:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Dec  9 11:49:22: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='icinga.shared.plainhost.net', port=443): Max retries exceeded with url: /cgi-bin/icinga/status.cgi?style=hostdetail&hoststatustypes=12&hostprops=262144&jsonoutput (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1c2a799710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Dec  9 11:49:22: During handling of the above exception, another exception occurred:
Dec  9 11:49:22: Traceback (most recent call last):
Dec  9 11:49:22:   File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 1370, in FetchURL
Dec  9 11:49:22:     response = self.session.get(url, timeout=self.timeout)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
Dec  9 11:49:22:     return self.request('GET', url, **kwargs)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
Dec  9 11:49:22:     resp = self.send(prep, **send_kwargs)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
Dec  9 11:49:22:     r = adapter.send(request, **kwargs)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
Dec  9 11:49:22:     raise ConnectionError(e, request=request)
Dec  9 11:49:22: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='icinga.shared.plainhost.net', port=443): Max retries exceeded with url: /cgi-bin/icinga/status.cgi?style=hostdetail&hoststatustypes=12&hostprops=262144&jsonoutput (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1c2a799710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Dec  9 11:49:22: Traceback (most recent call last):
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
Dec  9 11:49:22:     six.raise_from(e, None)
Dec  9 11:49:22:   File "<string>", line 2, in raise_from
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
Dec  9 11:49:22:     httplib_response = conn.getresponse()
Dec  9 11:49:22:   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
Dec  9 11:49:22:     response.begin()
Dec  9 11:49:22:   File "/usr/lib/python3.6/http/client.py", line 297, in begin
Dec  9 11:49:22:     version, status, reason = self._read_status()
Dec  9 11:49:22:   File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
Dec  9 11:49:22:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Dec  9 11:49:22:   File "/usr/lib/python3.6/socket.py", line 586, in readinto
Dec  9 11:49:22:     return self._sock.recv_into(b)
Dec  9 11:49:22:   File "/home/varac/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 307, in recv_into
Dec  9 11:49:22:     raise timeout('The read operation timed out')
Dec  9 11:49:22: socket.timeout: The read operation timed out
```

**Comment by varac** [comment]
I just wanted to report this again then I found out that I already reported this one 2,5y ago :astonished: 
Please catch connection exceptions so they don't clutter the journal/(sys)log. Thanks !

**Comment by varac** [comment]
Well, I *also* reported this in a duplicate even longer ago: #476

**Comment by varac** [comment]
Ping, Tracebacks are still cluttering the journal when not connected.
