### ISSUE TITLE
Nagstamon and Centreon 18.10

### ISSUE THREAD

**Issue by ebourgui** [HenriWahl/Nagstamon#524]
Hello,

Centreon 18.10 has been released. Nasgtamon 3.1.99rc2 doesn't support this version yet.

It works but after some minutes an "Authentication problem" occurs.

```
Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 973, in _check_session
AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 217, in _get_sid
AttributeError: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 217, in _get_sid
AttributeError: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 973, in _check_session
AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 217, in _get_sid
AttributeError: 'NoneType' object has no attribute 'find'
DEBUG: 2018-12-10 15:08:11.521920 hal Checking session status
DEBUG: 2018-12-10 15:08:11.522024 hal FetchURL: http://hal/centreon/include/core/autologout/autologoutXMLresponse.php CGI Data: None
ERROR: 2018-12-10 15:08:11.530646 hal Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 973, in _check_session
AttributeError: 'NoneType' object has no attribute 'text'

DEBUG: 2018-12-10 15:08:11.530832 hal FetchURL: http://hal/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=btet8jttmktn8uhikrk5qchh6n CGI Data: None
DEBUG: 2018-12-10 15:08:11.578257 hal Bad session ID, retrieving new one...
DEBUG: 2018-12-10 15:08:11.578288 hal FetchURL: http://hal/centreon/index.php CGI Data: None
ERROR: 2018-12-10 15:08:11.891265 hal Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 217, in _get_sid
AttributeError: 'NoneType' object has no attribute 'find'

DEBUG: 2018-12-10 15:08:11.891391 hal FetchURL: http://hal/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=btet8jttmktn8uhikrk5qchh6n CGI Data: None
DEBUG: 2018-12-10 15:08:11.939079 hal Even after renewing session ID, unable to get the XML
DEBUG: 2018-12-10 15:08:11.939121 hal FetchURL: http://hal/centreon/index.php CGI Data: None
ERROR: 2018-12-10 15:08:12.114451 hal Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 217, in _get_sid
AttributeError: 'NoneType' object has no attribute 'find'

DEBUG: 2018-12-10 15:08:12.114505 hal Checking session status
DEBUG: 2018-12-10 15:08:12.114517 hal FetchURL: http://hal/centreon/include/core/autologout/autologoutXMLresponse.php CGI Data: None
ERROR: 2018-12-10 15:08:12.119608 hal Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 973, in _check_session
AttributeError: 'NoneType' object has no attribute 'text'

DEBUG: 2018-12-10 15:08:12.119817 hal FetchURL: http://hal/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=ERROR CGI Data: None
DEBUG: 2018-12-10 15:08:12.167719 hal Bad session ID, retrieving new one...
DEBUG: 2018-12-10 15:08:12.167754 hal FetchURL: http://hal/centreon/index.php CGI Data: None
ERROR: 2018-12-10 15:08:12.301997 hal Traceback (most recent call last):
  File "Nagstamon/Servers/Centreon.py", line 217, in _get_sid
AttributeError: 'NoneType' object has no attribute 'find'

DEBUG: 2018-12-10 15:08:12.302046 hal FetchURL: http://hal/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=ERROR CGI Data: None
DEBUG: 2018-12-10 15:08:12.346753 hal Even after renewing session ID, unable to get the XML
```

/include/core/autologout/autologoutXMLresponse.php file doesn't exist anymore on centreon 18.10.

Regards,
Eric

**Comment by BenoitPoulet** [comment]
Hello,
Done. Merge request #527

**Comment by ebourgui** [comment]
Thank you Benoit!
Merci Benoit!
Eric
