### ISSUE TITLE
Nagstamon Zabbix Basic Auth 

### ISSUE THREAD

**Issue by finalbeta** [HenriWahl/Nagstamon#557]
Nagstamon version 3.2.1
Zabbix version 3.4.15

My Zabbix server installation uses "Basic authentication" to authenticate users. 
Nagstamon has an option "Basic" under "Authentication" for the Zabbix server settings. 

I'm using the following settings (not my actual IP/user)
![image](https://user-images.githubusercontent.com/22134261/54087101-f269ad00-434f-11e9-8163-87b62f787159.png)

However, I cannot authenticate to Zabbix when using Basic authentication.
If I read that correct, nagstamon supports "basic" inside the settings. I'm assuming this is "basic authentication" support?
However, when authenticating, nagstamon is not sending a http basic header, so authentication is failing. (I ran tcpdump to verify this)

If nagstamon does not support basic authentication. Perhaps the settings should not mention "basic". (and then basic auth may be a feature request ;) )
If nagstamon does support basic authentication, it's not working when using "zabbix" as a server option. 

Thanks for any feedback!

**Comment by HenriWahl** [comment]
Did you once try a testing version of next Nagstamon?

**Comment by HenriWahl** [comment]
Any progress when using 3.4rc2?

**Comment by marcin-github** [comment]
I have similalr issue. After first install nagstamon works, after some time I get 
```
ERROR: 2020-03-26 11:35:04.216900 zabbix decerto Traceback (most recent call last):
  File "Nagstamon\Servers\Zabbix.py", line 129, in _get_status
  File "Nagstamon\thirdparty\zabbix_api.py", line 333, in method
  File "Nagstamon\thirdparty\zabbix_api.py", line 79, in wrapper
  File "Nagstamon\thirdparty\zabbix_api.py", line 340, in do_request
  File "Nagstamon\thirdparty\zabbix_api.py", line 290, in do_request
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: ('Error -32602: Invalid params., Not authorised. while sending {"jsonrpc": "2.0", "method": "host.get", "params": {"output": ["hostid", "host", "name", "status", "available", "error", "errors_from", "snmp_available", "snmp_error", "snmp_errors_from", "ipmi_available", "ipmi_error", "ipmi_errors_from", "jmx_available", "jmx_error", "jmx_errors_from", "maintenance_status", "maintenance_from"], "selectInterfaces": ["ip"], "filter": {}}, "auth": "", "id": 2}', -32602)

```
version 3.4.1

**Comment by HenriWahl** [comment]
Should be working meanwhile.
