### ISSUE TITLE
Segfault on wayland

### ISSUE THREAD

**Issue by varac** [HenriWahl/Nagstamon#570]
I'm getting this segfault on wayland (ubuntu 19.04) with nagstamon 3.2.1-1.

```
 ~ $ nagstamon 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6490, in __init__
    '/org/freedesktop/Notifications')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Using Wayland-EGL
[1]    32287 segmentation fault (core dumped)  nagstamon
```

**Comment by HenriWahl** [comment]
The problem here comes from DBus.

**Comment by varac** [comment]
Can't nagstamon handle this DBUS exception in a way that it doesn't segfault ?  

From the journal:
```
Mai 04 14:00:14 rocinante kernel: nagstamon[21961]: segfault at 1e ip 00007f9d372108f0 sp 00007ffe03293018 error 4 in libpthread-2.29.so[7f9d3720c000+f000]
Mai 04 14:00:14 rocinante kernel: Code: ff 48 8d 0d 92 ad 00 00 ba b1 01 00 00 48 8d 35 1b ac 00 00 48 8d 3d cf ac 00 00 e8 ea b8 ff ff 8b 03 e9 25 fa ff ff 0f 1f 00 <8b> 47 10 89 c2 81 e2 7f 01 00 00 90 83 e0 7c 0f 85 ab 00 00 00 48
```

**Comment by varac** [comment]
After some reboots it work now.

**Comment by varac** [comment]
Hmm, looks similar to #681
