### ISSUE TITLE
Zenoss and HTTP Error 502: notresolvable

### ISSUE THREAD

**Issue by dmarkdvt** [HenriWahl/Nagstamon#605]
Hello,

this is the debug output from the current and testing stage of Nagstamon when I try to connect to our Zenoss instance.

`
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/Nagstamon/Servers/Zenoss.py", line 81, in _get_status
    hosts = self._get_all_events()
  File "/usr/lib/python3.7/site-packages/Nagstamon/Servers/Zenoss.py", line 167, in _get_all_events
    events = self.zapi.get_event()
AttributeError: 'NoneType' object has no attribute 'get_event'

ERROR: 2019-11-12 11:03:49.227483 Zenoss Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/Nagstamon/Servers/Zenoss.py", line 70, in _zlogin
    self.zapi = ZenossAPI(Server=self.server)
  File "/usr/lib/python3.7/site-packages/Nagstamon/thirdparty/zenoss_api.py", line 76, in __init__
    self._login() #login to the zenoss system
  File "/usr/lib/python3.7/site-packages/Nagstamon/thirdparty/zenoss_api.py", line 85, in _login
    self.urlOpener.open(self.ZENOSS_INSTANCE + '/zport/acl_users/cookieAuthHelper/login', loginParams)
  File "/usr/lib64/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
urllib.error.HTTPError: HTTP Error 502: notresolvable
`
The host is like this: https://sub.s-u-b.domain.tlr. I can ping it and connect to the port. I can also see traffic between the client and the server.

Cheers

**Comment by HenriWahl** [comment]
What about latest testing binaries?
