### ISSUE TITLE
Nagstamon 3.2.1 crash when acknowledging alert from an Icinga server 2.6.2

### ISSUE THREAD

**Issue by moschlar** [HenriWahl/Nagstamon#612]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944646

When acknowledging an alert from an Icinga2 server a traceback occurs
submitting the form:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 3967, in acknowledge
    self.server.set_acknowledge(info_dict)
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 359, in set_acknowledge
    all_services)
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/IcingaWeb2.py", line 368, in _set_acknowledge
    CSRFToken = formtag.findNext('input', {'name':'CSRFToken'})['value']
AttributeError: 'NoneType' object has no attribute 'findNext'
Aborted
```

The icinga-web2 version used is 2.6.2.

**Comment by HenriWahl** [comment]
Please try latest testing release.

**Comment by HenriWahl** [comment]
Any change with 3.4rc2?

**Comment by moschlar** [comment]
Couldn't reproduce it now with the demo site at https://icinga.com/demo/.

I asked the original Debian bug reporter for confirmation, but it seems to be good.
