### ISSUE TITLE
Fails to run over ssh

### ISSUE THREAD

**Issue by mowgli** [HenriWahl/Nagstamon#642]
This might be the same issue than #296 but I still have it.

When I run nagstamon over ssh to the remote machine that have access to monitors, it fails with the following dump:
```
~> nagstamon 
[Errno 2] No such file or directory: '/home/klaus/.nagstamon/nagstamon.pid'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-klaus'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6979, in __init__
    dbus_object = dbus_sessionbus.get_object('org.freedesktop.Notifications',
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[1]    22530 segmentation fault  nagstamon
```

The used window manager is fvwm and the version of nagstamon is 3.4.1 from Debian unstable. I use stalonetray as a tray.

When I run it locally on the same box where I did the ssh, it works (but it is rather useless as there is no way, this machine can reach the monitor host.)

**Comment by HenriWahl** [comment]
Looking at
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
I am pretty sure this is a local problem.
