### ISSUE TITLE
Connection error and system tray icon status

### ISSUE THREAD

**Issue by atom32k** [HenriWahl/Nagstamon#675]
Hi, 

After connection error:
```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 1456, in FetchURL
    response = self.session.get(url, timeout=self.timeout)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
Systray icon remain white and with connection error status even if later checks are OK.

Ubuntu 20.04.1 LTS
Nagstamon 3.4.1

**Comment by HenriWahl** [comment]
@atom32k sorry this message got totally lost... maybe a stupid question, but: does this problem still persist?

**Comment by atom32k** [comment]
> @atom32k sorry this message got totally lost... maybe a stupid question, but: does this problem still persist?

Hi, no worries on 3.8.0 looks fine :) cheers

**Comment by HenriWahl** [comment]
👍
