### ISSUE TITLE
Segfault with testing debian package 3.5-20201110

### ISSUE THREAD

**Issue by varac** [HenriWahl/Nagstamon#681]
I want to test the [alertmanager integration](https://github.com/HenriWahl/Nagstamon/pull/679) so I installed the `3.5-20201110` debian package.
Afterwards, nagstamon refuses to start and segfaults:

```
❯ nagstamon                              
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6995, in __init__
    dbus_object = dbus_sessionbus.get_object('org.freedesktop.Notifications',
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.freedesktop.Notifications: No such file or directory
Xlib.xauth: warning, no xauthority details available
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
[1]    52219 segmentation fault (core dumped)  nagstamon
```

From dmesg:

```
[ 4122.561477] nagstamon[52219]: segfault at 17 ip 00007f03de168824 sp 00007ffd7fe0d618 error 4 in libpthread-2.32.so[7f03de164000+10000]
[ 4122.561485] Code: 0d f1 bf 00 00 ba a7 01 00 00 48 8d 35 77 be 00 00 48 8d 3d a6 bd 00 00 e8 f9 be ff ff 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa <8b> 47 10 89 c2 81 e2 7f 01 00 00 90 83 e0 7c 75 7b 53 48 83 ec 10
```

Using Ubuntu 20.10 on wayland (sway). Last installed testing debian package `3.5-20200731` worked fine.

**Comment by varac** [comment]
Btw, is there an archive with older testing deb packages ? I'd like to revert to `3.5-20200731` but I can't find it anymore...

**Comment by varac** [comment]
```
Nov 11 19:43:45 box systemd-coredump[18250]: Process 18233 (nagstamon) of user 1000 dumped core.
                                                   
                                                   Stack trace of thread 18233:
                                                   #0  0x00007f7e00f17824 __GI___pthread_mutex_lock (libpthread.so.0 + 0xb824)
                                                   #1  0x00007f7dffe75ad7 dbus_connection_dispatch (libdbus-1.so.3 + 0x14ad7)
                                                   #2  0x00007f7dfde0cb98 n/a (pyqt5.cpython-38-x86_64-linux-gnu.so + 0x2b98)
                                                   #3  0x00007f7dfce4e651 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2d7651)
                                                   #4  0x00007f7dfd8d8013 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x16b013)
                                                   #5  0x00007f7dfe21e966 n/a (QtWidgets.cpython-38-x86_64-linux-gnu.so + 0x3e3966)
                                                   #6  0x00007f7dfce221ca _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2ab1ca)
                                                   #7  0x00007f7dfce24bc1 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2adbc1)
                                                   #8  0x00007f7dfce7a1c7 n/a (libQt5Core.so.5 + 0x3031c7)
                                                   #9  0x00007f7dffa984db g_main_context_dispatch (libglib-2.0.so.0 + 0x534db)
                                                   #10 0x00007f7dffa98788 n/a (libglib-2.0.so.0 + 0x53788)
                                                   #11 0x00007f7dffa98853 g_main_context_iteration (libglib-2.0.so.0 + 0x53853)
                                                   #12 0x00007f7dfce79843 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x302843)
                                                   #13 0x00007f7dfce20a4b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a9a4b)
                                                   #14 0x00007f7dfce28fc6 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2b1fc6)
                                                   #15 0x00007f7dfe1dc071 n/a (QtWidgets.cpython-38-x86_64-linux-gnu.so + 0x3a1071)
                                                   #16 0x0000000000524d76 PyCFunction_Call (python3.8 + 0x124d76)
                                                   #17 0x0000000000514313 _PyObject_MakeTpCall (python3.8 + 0x114313)
                                                   #18 0x000000000050e85c _PyEval_EvalFrameDefault (python3.8 + 0x10e85c)
                                                   #19 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #20 0x00000000005d3087 PyEval_EvalCode (python3.8 + 0x1d3087)
                                                   #21 0x00000000005f1bb5 n/a (python3.8 + 0x1f1bb5)
                                                   #22 0x00000000005ecfd3 n/a (python3.8 + 0x1ecfd3)
                                                   #23 0x00000000005f5bab PyRun_FileExFlags (python3.8 + 0x1f5bab)
                                                   #24 0x00000000005f5644 PyRun_SimpleFileExFlags (python3.8 + 0x1f5644)
                                                   #25 0x00000000005ea3d9 Py_RunMain (python3.8 + 0x1ea3d9)
                                                   #26 0x00000000005c802d Py_BytesMain (python3.8 + 0x1c802d)
                                                   #27 0x00007f7e00ba3cb2 __libc_start_main (libc.so.6 + 0x28cb2)
                                                   #28 0x00000000005c7f2e _start (python3.8 + 0x1c7f2e)
                                                   
                                                   Stack trace of thread 18239:
                                                   #0  0x00007f7e00c8866f __GI___poll (libc.so.6 + 0x10d66f)
                                                   #1  0x00007f7dffa9871e n/a (libglib-2.0.so.0 + 0x5371e)
                                                   #2  0x00007f7dffa98853 g_main_context_iteration (libglib-2.0.so.0 + 0x53853)
                                                   #3  0x00007f7dfce79843 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x302843)
                                                   #4  0x00007f7dfce20a4b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a9a4b)
                                                   #5  0x00007f7dfcc3f8b2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc88b2)
                                                   #6  0x00007f7df7f114cb n/a (libQt5DBus.so.5 + 0x1a4cb)
                                                   #7  0x00007f7dfcc40a41 n/a (libQt5Core.so.5 + 0xc9a41)
                                                   #8  0x00007f7e00f15590 start_thread (libpthread.so.0 + 0x9590)
                                                   #9  0x00007f7e00c94223 __clone (libc.so.6 + 0x119223)
                                                   
                                                   Stack trace of thread 18240:
                                                   #0  0x00007f7e00f1bc06 futex_wait_cancelable (libpthread.so.0 + 0xfc06)
                                                   #1  0x00007f7dfcc4674b _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xcf74b)
                                                   #2  0x00007f7dfdafee8d n/a (libQt5Widgets.so.5 + 0x391e8d)
                                                   #3  0x00007f7dfcc40a41 n/a (libQt5Core.so.5 + 0xc9a41)
                                                   #4  0x00007f7e00f15590 start_thread (libpthread.so.0 + 0x9590)
                                                   #5  0x00007f7e00c94223 __clone (libc.so.6 + 0x119223)
                                                   
                                                   Stack trace of thread 18248:
                                                   #0  0x00007f7e00f1bc06 futex_wait_cancelable (libpthread.so.0 + 0xfc06)
                                                   #1  0x00007f7ddf01b4eb n/a (i965_dri.so + 0x5474eb)
                                                   #2  0x00007f7ddf01afab n/a (i965_dri.so + 0x546fab)
                                                   #3  0x00007f7e00f15590 start_thread (libpthread.so.0 + 0x9590)
                                                   #4  0x00007f7e00c94223 __clone (libc.so.6 + 0x119223)
                                                   
                                                   Stack trace of thread 18246:
                                                   #0  0x00007f7e00f1bc06 futex_wait_cancelable (libpthread.so.0 + 0xfc06)
                                                   #1  0x00007f7ddf01b4eb n/a (i965_dri.so + 0x5474eb)
                                                   #2  0x00007f7ddf01afab n/a (i965_dri.so + 0x546fab)
                                                   #3  0x00007f7e00f15590 start_thread (libpthread.so.0 + 0x9590)
                                                   #4  0x00007f7e00c94223 __clone (libc.so.6 + 0x119223)
                                                   
                                                   Stack trace of thread 18247:
                                                   #0  0x00007f7e00f1bc06 futex_wait_cancelable (libpthread.so.0 + 0xfc06)
                                                   #1  0x00007f7ddf01b4eb n/a (i965_dri.so + 0x5474eb)
                                                   #2  0x00007f7ddf01afab n/a (i965_dri.so + 0x546fab)
                                                   #3  0x00007f7e00f15590 start_thread (libpthread.so.0 + 0x9590)
                                                   #4  0x00007f7e00c94223 __clone (libc.so.6 + 0x119223)
                                                   
                                                   Stack trace of thread 18242:
                                                   #0  0x00007f7e00c8866f __GI___poll (libc.so.6 + 0x10d66f)
                                                   #1  0x000000000062ae40 n/a (python3.8 + 0x22ae40)
                                                   #2  0x0000000000530b1f n/a (python3.8 + 0x130b1f)
                                                   #3  0x0000000000509571 _PyEval_EvalFrameDefault (python3.8 + 0x109571)
                                                   #4  0x0000000000507fe3 _PyEval_EvalCodeWithName (python3.8 + 0x107fe3)
                                                   #5  0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #6  0x000000000050944e _PyEval_EvalFrameDefault (python3.8 + 0x10944e)
                                                   #7  0x000000000051e8f7 _PyFunction_Vectorcall (python3.8 + 0x11e8f7)
                                                   #8  0x000000000050944e _PyEval_EvalFrameDefault (python3.8 + 0x10944e)
                                                   #9  0x000000000050828f _PyEval_EvalCodeWithName (python3.8 + 0x10828f)
                                                   #10 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #11 0x00000000005302c5 PyVectorcall_Call (python3.8 + 0x1302c5)
                                                   #12 0x000000000050ac37 _PyEval_EvalFrameDefault (python3.8 + 0x10ac37)
                                                   #13 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #14 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #15 0x000000000050a64b _PyEval_EvalFrameDefault (python3.8 + 0x10a64b)
                                                   #16 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #17 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #18 0x000000000050e302 _PyEval_EvalFrameDefault (python3.8 + 0x10e302)
                                                   #19 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #20 0x000000000052fec1 n/a (python3.8 + 0x12fec1)
                                                   #21 0x000000000050a64b _PyEval_EvalFrameDefault (python3.8 + 0x10a64b)
                                                   #22 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #23 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #24 0x000000000050a64b _PyEval_EvalFrameDefault (python3.8 + 0x10a64b)
                                                   #25 0x000000000051e8f7 _PyFunction_Vectorcall (python3.8 + 0x11e8f7)
                                                   #26 0x0000000000509571 _PyEval_EvalFrameDefault (python3.8 + 0x109571)
                                                   #27 0x0000000000507fe3 _PyEval_EvalCodeWithName (python3.8 + 0x107fe3)
                                                   #28 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #29 0x0000000000509571 _PyEval_EvalFrameDefault (python3.8 + 0x109571)
                                                   #30 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #31 0x000000000052fec1 n/a (python3.8 + 0x12fec1)
                                                   #32 0x000000000050a64b _PyEval_EvalFrameDefault (python3.8 + 0x10a64b)
                                                   #33 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #34 0x000000000052fec1 n/a (python3.8 + 0x12fec1)
                                                   #35 0x000000000050a64b _PyEval_EvalFrameDefault (python3.8 + 0x10a64b)
                                                   #36 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #37 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #38 0x00000000005300a3 n/a (python3.8 + 0x1300a3)
                                                   #39 0x00000000005302c5 PyVectorcall_Call (python3.8 + 0x1302c5)
                                                   #40 0x000000000050ac37 _PyEval_EvalFrameDefault (python3.8 + 0x10ac37)
                                                   #41 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #42 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #43 0x00000000005300a3 n/a (python3.8 + 0x1300a3)
                                                   #44 0x00000000005302c5 PyVectorcall_Call (python3.8 + 0x1302c5)
                                                   #45 0x000000000050ac37 _PyEval_EvalFrameDefault (python3.8 + 0x10ac37)
                                                   #46 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #47 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #48 0x000000000052fddd n/a (python3.8 + 0x12fddd)
                                                   #49 0x00000000005302c5 PyVectorcall_Call (python3.8 + 0x1302c5)
                                                   #50 0x000000000050ac37 _PyEval_EvalFrameDefault (python3.8 + 0x10ac37)
                                                   #51 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #52 0x000000000052fec1 n/a (python3.8 + 0x12fec1)
                                                   #53 0x000000000050a64b _PyEval_EvalFrameDefault (python3.8 + 0x10a64b)
                                                   #54 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #55 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #56 0x0000000000509571 _PyEval_EvalFrameDefault (python3.8 + 0x109571)
                                                   #57 0x000000000051e8f7 _PyFunction_Vectorcall (python3.8 + 0x11e8f7)
                                                   #58 0x0000000000509571 _PyEval_EvalFrameDefault (python3.8 + 0x109571)
                                                   #59 0x0000000000507965 _PyEval_EvalCodeWithName (python3.8 + 0x107965)
                                                   #60 0x000000000051e98a _PyFunction_Vectorcall (python3.8 + 0x11e98a)
                                                   #61 0x0000000000509571 _PyEval_EvalFrameDefault (python3.8 + 0x109571)
                                                   #62 0x000000000051e8f7 _PyFunction_Vectorcall (python3.8 + 0x11e8f7)
                                                   #63 0x000000000052fddd n/a (python3.8 + 0x12fddd)
                             
```

**Comment by varac** [comment]
> Btw, is there an archive with older testing deb packages ? I'd like to revert to `3.5-20200731` but I can't find it anymore...

Nevermind. I built `3.5-20200731` myself, but it also segfaults.

**Comment by HenriWahl** [comment]
Are you running on Wayland or Xorg?

**Comment by varac** [comment]
I'm on Ubuntu 20.10 with wayland (sway).

**Comment by HenriWahl** [comment]
I made rather bad experiences with Wayland so far so I switched back to Xorg. I would not be surprised if there is some problem.
Maybe you can try the Flatpak version of Nagstamon from flathub.org?

**Comment by varac** [comment]
I gave it a try and it at least starts without issues:

```
❯ flatpak run de.ifw_dresden.nagstamon
No DBus for desktop notification available.
Xlib.xauth: warning, no xauthority details available
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Using Wayland-EGL
Using the 'xdg-shell' shell integration
```

However, I'm missing the tray icon so it's not usable for me. Also, [flathub hosts an older version](https://flathub.org/apps/details/de.ifw_dresden.nagstamon) (3.4.1) and I'm interested in trying out (and giving feedback) about the alertmanager integration so it doesn't help me.
I'd really love if the wayland issue would be fixed in the testing packages, wayland is used by a growing user base and will replace X11 in the long run.

**Comment by HenriWahl** [comment]
> However, I'm missing the tray icon so it's not usable for me. Also, [flathub hosts an older version](https://flathub.org/apps/details/de.ifw_dresden.nagstamon) (3.4.1) and I'm interested in trying out (and giving feedback) about the alertmanager integration so it doesn't help me.

Right. Maybe you can run it for testing in a virtualenv with PyQt coming via pip instead the distro one? No other Qt is inside the flatpak, coming from pip there too.

> I'd really love if the wayland issue would be fixed in the testing packages, wayland is used by a growing user base and will replace X11 in the long run.

Me too - I tested from time to time how support for Qt and Wayland evolved but everytime it was unusable. I am still hoping...
One upcoming problem will be that under Wayland an application can't modify its window, which is bad for Nagstamon. This is as far as I know - I would be happy to learn there is a way to make it work like in Xorg.

**Comment by varac** [comment]
> One upcoming problem will be that under Wayland an application can't modify its window, which is bad for Nagstamon

It might not be ideal, but until 2 weeks I had nagstamon `3.5-20200731` running under wayland perfectly, and I wasn't missing anything. Wonder what broke it (I upgraded to ubuntu 20.10 shortly after release). And the years before older versions ran fine under wayland as well.

**Comment by HenriWahl** [comment]
Looks like newer Qt coming with Ubuntu 20.10 could be involved?

**Comment by varac** [comment]
Ubuntu 20.10 upgraded `qt5-default` from `5.12.8+dfsg-0ubuntu1` (20.04) to `5.14.2+dfsg-6`, and `python3-pyqt5` from `5.14.1+dfsg-3build1` (20.04) to `5.15.0+dfsg-1`.

**Comment by varac** [comment]
Here's the strace if this is any useful: 
[nagstamon.strace.txt](https://github.com/HenriWahl/Nagstamon/files/5552262/nagstamon.strace.txt)

**Comment by HenriWahl** [comment]
> Here's the strace if this is any useful:
> [nagstamon.strace.txt](https://github.com/HenriWahl/Nagstamon/files/5552262/nagstamon.strace.txt)

Not really... but the update to Ubuntu 20.10 might be a good candidate if it was the only changing thing...

**Comment by varac** [comment]
I can confirm that latest available testing deb package  `3.5-20201222` also segfaults on PopOS (based on Ubuntu 20.10), Gnome, X11, in a fresh environment without previous nagstamon config:


```
❯ nagstamon        
[Errno 2] No such file or directory: '/home/varac/.nagstamon/nagstamon.pid'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
zsh: segmentation fault (core dumped)  nagstamon
```

Journal shows:

```
Jan 25 22:26:42 ... gnome-shell[2928]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x5200008 specified for 0x5200006.
```

`python3-pyqt5` version is `5.15.0+dfsg-1`

**Comment by varac** [comment]
The issue still persists with nagstamon 3.6.0 (deb downloaded from GH release page).

```
❯ nagstamon 
[Errno 2] No such file or directory: '/home/varac/.nagstamon/nagstamon.pid'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
zsh: segmentation fault (core dumped)  nagstamon
```

Journal: 
```
Apr 06 17:36:47 sancho.varac.net kernel: nagstamon[36382]: segfault at 0 ip 00007fc9f0664bc5 sp 00007ffd82579e50 error 4 in iHD_drv_video.so[7fc9f054b000+348000]
Apr 06 17:36:47 sancho.varac.net kernel: Code: 01 48 83 f8 42 75 e6 31 db 66 41 89 9f 58 0c 00 00 49 8b 5f 28 8b 83 f0 1d 00 00 85 c0 0f 84 ba 01 00 00 48 8b b3 e8 1d 00 00 <81> 3e 00 00 01 00 48 89 75 c8 0f 85 a3 01 00 00 44 8d 70 f0 4d 63
```

**Comment by HenriWahl** [comment]
Does the crash happen with Wayland or Xorg?

**Comment by varac** [comment]
> Does the crash happen with Wayland or Xorg?

Xorg, vanilla installation of PopOS 20.10 (which is basically a branded Ubuntu 20.10 with a few extras).

**Comment by HenriWahl** [comment]
I set up a fresh Ubuntu 20.10 and Nagstamon 3.6.0 from GitHub runs with default settings as floating popup window without crash. What is your setting?

**Comment by varac** [comment]
I don't have any settings (no `~/.nagstamon` dir)

**Comment by varac** [comment]
I noticed it segfauts in ` iHD_drv_video.so`, which is shipped in `intel-media-va-driver:amd64 20.2.0+dfsg1-1` on my machine. The original segfault was a different one.

**Comment by varac** [comment]
Just for reference, #676 is also about a segfault in `iHD_drv_video.so`.

**Comment by HenriWahl** [comment]
> I don't have any settings (no `~/.nagstamon` dir)

OK, so apparently it crashes even before being able to store a default config?

**Comment by varac** [comment]
> OK, so apparently it crashes even before being able to store a default config?

Seems like it.

**Comment by HenriWahl** [comment]
> Just for reference, #676 is also about a segfault in `iHD_drv_video.so`.

Interesting - my working setup with plain Ubuntu 20.10 happens in a KVM machine using llvmpipe.

Searching for "iHD_drv_video.so" in The Web apparently gives a bunch of results where this one causes some trouble. :-(

**Comment by varac** [comment]
Ahhhh! I fixed it by installing `intel-media-va-driver-non-free` (which replaces the free `intel-media-va-driver`) after reading 
https://bugs.launchpad.net/ubuntu/+source/gthumb/+bug/1903569.
Nice, I can use Nagstamon again \o/ 
However, I'd be still interested *why* Nagstamon (and other apps) segfault the free driver but not the non-free one, because it would be a pity if that non-free driver would become a dependency of Nagstamon.

**Comment by varac** [comment]
Same issue, same OS, different app: https://github.com/vkohaupt/vokoscreenNG/issues/117#issuecomment-722806723

**Comment by HenriWahl** [comment]
> Ahhhh! I fixed it by installing `intel-media-va-driver-non-free` (which replaces the free `intel-media-va-driver`) after reading
> https://bugs.launchpad.net/ubuntu/+source/gthumb/+bug/1903569.

Right now I wanted to ask you to try the i965-intel-driver but even better if it works with the newer one! Congrats.

> Nice, I can use Nagstamon again \o/

Even more congrats...

> However, I'd be still interested _why_ Nagstamon (and other apps) segfault the free driver but not the non-free one, because it would be a pity if that non-free driver would become a dependency of Nagstamon.

That's the question.

**Comment by HenriWahl** [comment]
Apparently not fixable by Nagstamon so going to be closed,
