### ISSUE TITLE
Crash with Zabbix host that has no network interfaces

### ISSUE THREAD

**Issue by sjjf** [HenriWahl/Nagstamon#687]
I'm seeing this traceback from nagstamon when it starts up:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 4112, in get_status
    status = self.server.GetStatus()
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 859, in GetStatus
    status = self._get_status()
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 168, in _get_status
    'address': host['interfaces'][0]['ip'],
IndexError: list index out of range
```

This appears to be related to hosts in Zabbix that have no network interfaces - in our case some virtual hosts that we're tying monitoring systems to. Adding an interface to those hosts removes this traceback.

**Comment by sjjf** [comment]
Just as an fyi, it appears that as of Zabbix 5.2 an interface isn't mandatory on all hosts - we upgraded to 5.2 recently.

**Comment by HenriWahl** [comment]
Please try latest testing release.
