### ISSUE TITLE
zabbix with proxy error

### ISSUE THREAD

**Issue by al3x2ndru** [HenriWahl/Nagstamon#724]
zabbix version 4.4
nagstamon 3.6.0

this is a screenshot of the error
![image](https://user-images.githubusercontent.com/20455311/117437030-8f700280-af27-11eb-9d39-e83949eae981.png)
same configuration, same proxy, same servers are working with Nagios, but not with Zabbix 
sample from the debug log 

ERROR: 2021-05-07 11:24:15.802402 Z-LAX1 Traceback (most recent call last):
  File "urllib\request.py", line 1346, in do_open
  File "http\client.py", line 1253, in request
  File "http\client.py", line 1299, in _send_request
  File "http\client.py", line 1248, in endheaders
  File "http\client.py", line 1008, in _send_output
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Nagstamon\thirdparty\zabbix_api.py", line 254, in do_request
  File "urllib\request.py", line 517, in open
  File "urllib\request.py", line 534, in _open
  File "urllib\request.py", line 494, in _call_chain
  File "urllib\request.py", line 1375, in http_open
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Nagstamon\Servers\Zabbix.py", line 92, in _login
  File "Nagstamon\thirdparty\zabbix_api.py", line 208, in login
  File "Nagstamon\thirdparty\zabbix_api.py", line 264, in do_request
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: urllib2.URLError - <urlopen error timed out>

**Comment by al3x2ndru** [comment]
just an update on this, I've updated to version 3.7.2 for nagstamon and it seems that the debug has more info
the same proxy info in a browser works for the same server but it's not working in nagstamon

ERROR: 2021-05-07 14:28:21.176482 Z-LAX1 Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 366, in connect
  File "http\client.py", line 903, in _tunnel
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Nagstamon\Servers\Generic.py", line 1492, in FetchURL
  File "requests\sessions.py", line 555, in get
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

**Comment by HenriWahl** [comment]
Looks like the version check causes some trouble?

**Comment by k11h-de** [comment]
@HenriWahl 
I am facing the same issue on MacOS 12.0 Beta 5 with nagstamon 3.7-20210815
I hope my provided details are helpful.

I opened a socks5 Proxy with `ssh -vvv  -D 3128 user@host` and configured `socks5h://127.0.0.1:3128` in both, nagios and zabbix, server setting. For the nagios connection I see request through the tunnel but for the zabbix connection no request is ever sent to the  tunnel. I guess the proxy settings are not correctly applied.
Looking at the code, I realized that a server of type Nagios uses `import Nagstamon.Servers.GenericServer` which contains proxy settings, while `Nagstamon/Servers/Zabbix.py` has no proxy support.

**Comment by HenriWahl** [comment]
Quite likely - if the Zabbix part would use the same method for connections the socks proxy should be working too.
@mprenditore what do you think?

**Comment by HenriWahl** [comment]
As Zabbix module has been overhauled - is ths still an issue?

**Comment by al3x2ndru** [comment]
for me using http://proxy:port it still is an issue

I managed to have a workaround using a Manual proxy setup in Windows and tick the "Use proxy from the OS" box, that way Zabbix is working
