### ISSUE TITLE
Crash on Windows with Icingaweb2

### ISSUE THREAD

**Issue by neubi4** [HenriWahl/Nagstamon#726]
Hi,

since a couple of month we experience crashes of Nagstamon when using it with Icingaweb2. It only crashes sometimes, either at the start or in the middle of running.

I tried to use the Debug Log, but Nagstamon never writes anything in the file.

So i tried to get the code vom Github and run it directly with python, and finally got an error:

```
(env) C:\Users\mtnu\nagpy\Nagstamon>python ./nagstamon.py
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
DEBUG: 2021-05-11 07:16:57.324796 Saving configuration to file c:\users\mtnu\.nagstamon\nagstamon.conf
DEBUG: 2021-05-11 07:16:57.711752 aaa_nagios_zed Created server.
DEBUG: 2021-05-11 07:16:57.711752 zzz_domon_zed Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C770D8> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C77048> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C77168> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C771F8> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C77288> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C77318> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C773A8> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C77438> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C774C8> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C77558> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7C775E8> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x00000261E7C77708>
DEBUG: 2021-05-11 07:16:58.287843 aaa_nagios_zed FetchURL: https://nagios-host/nagios/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2021-05-11 07:16:58.307275 zzz_domon_zed FetchURL: https://icingaweb2-host/authentication/login CGI Data: None
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD048> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CA8EE8> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD0D8> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD168> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD1F8> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD288> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD318> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD3A8> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD438> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD4C8> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000261E7CBD558> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x00000261E7CBD708>
DEBUG: 2021-05-11 07:16:59.253352 aaa_nagios_zed FetchURL: https://nagstamon.de/version/unstable CGI Data: None
Traceback (most recent call last):
  File "C:\Users\mtnu\nagpy\Nagstamon\Nagstamon\QUI\__init__.py", line 4112, in get_status
    status = self.server.GetStatus()
  File "C:\Users\mtnu\nagpy\Nagstamon\Nagstamon\Servers\Generic.py", line 898, in GetStatus
    self.init_HTTP()
  File "C:\Users\mtnu\nagpy\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 95, in init_HTTP
    if not 'Referer' in self.session.headers:
AttributeError: 'NoneType' object has no attribute 'headers'
```

This happens only when the Icingaweb2 Server is enabled, when it is disabed (so nagios server only), everything works.
We are behind a Corporate Proxy, it is set in each server config file.

Server config
```
[server_zzz_domon_zed]
enabled = True
type = IcingaWeb2
name = zzz_domon_zed
monitor_url = https://icingaweb2-host
monitor_cgi_url = https://icingaweb2-host
username = redacted
password = redacted
save_password = True
use_proxy = True
use_proxy_from_os = False
proxy_address = http://proxy-host:8080/
proxy_username = redacted
proxy_password = redacted
authentication = basic
timeout = 10
show_options = False
ignore_cert = False
custom_cert_use = False
custom_cert_ca_file = 
use_autologin = False
autologin_key = redacted
use_display_name_host = False
use_display_name_service = False
no_cookie_auth = False
force_authuser = False
checkmk_view_hosts = nagstamon_hosts
checkmk_view_services = nagstamon_svc
host_filter = state !=0
service_filter = state !=0 or host.state != 0
monitor_site = Site 1
use_description_name_service = False
map_to_hostname = pod_name,namespace,instance
map_to_servicename = alertname
map_to_status_information = message,summary,description
alertmanager_filter = 
```

Nagstamon config
```
[Nagstamon]
update_interval_seconds = 60
short_display = False
long_display = True
show_tooltips = True
show_grid = True
grid_use_custom_intensity = False
grid_alternation_intensity = 49
highlight_new_events = True
default_sort_field = status
default_sort_order = Ascending
filter_all_down_hosts = False
filter_all_unreachable_hosts = False
filter_all_unreachable_services = False
filter_all_flapping_hosts = False
filter_all_unknown_services = False
filter_all_information_services = False
filter_all_warning_services = False
filter_all_average_services = False
filter_all_high_services = False
filter_all_critical_services = False
filter_all_disaster_services = False
filter_all_flapping_services = False
filter_acknowledged_hosts_services = True
filter_hosts_services_disabled_notifications = True
filter_hosts_services_disabled_checks = True
filter_hosts_services_maintenance = True
filter_services_on_acknowledged_hosts = True
filter_services_on_down_hosts = True
filter_services_on_hosts_in_maintenance = True
filter_services_on_unreachable_hosts = True
filter_hosts_in_soft_state = True
filter_services_in_soft_state = True
position_x = 30
position_y = 30
position_width = 640
position_height = 480
popup_details_hover = True
popup_details_clicking = False
close_details_hover = True
close_details_clicking = False
close_details_clicking_somewhere = False
connect_by_host = True
connect_by_dns = False
connect_by_ip = False
use_default_browser = True
use_custom_browser = False
custom_browser = 
debug_mode = True
debug_to_file = True
debug_file = C:\Users\mtnu\nagstamon.log
check_for_new_version = True
notification = True
notification_flashing = True
notification_desktop = False
notification_actions = False
notification_sound = False
notification_sound_repeat = False
notification_default_sound = True
notification_custom_sound = False
notification_custom_sound_warning = 
notification_custom_sound_critical = 
notification_custom_sound_down = 
notification_action_warning = False
notification_action_warning_string = 
notification_action_critical = False
notification_action_critical_string = 
notification_action_down = False
notification_action_down_string = 
notification_action_ok = False
notification_action_ok_string = 
notification_custom_action = False
notification_custom_action_string = 
notification_custom_action_separator = 
notification_custom_action_single = False
notify_if_up = False
notify_if_information = True
notify_if_warning = True
notify_if_average = True
notify_if_high = True
notify_if_critical = True
notify_if_disaster = True
notify_if_unknown = True
notify_if_unreachable = True
notify_if_down = True
re_host_enabled = False
re_host_pattern = 
re_host_reverse = False
re_service_enabled = False
re_service_pattern = 
re_service_reverse = False
re_status_information_enabled = False
re_status_information_pattern = 
re_status_information_reverse = False
re_duration_enabled = False
re_duration_pattern = 
re_duration_reverse = False
re_attempt_enabled = False
re_attempt_pattern = 
re_attempt_reverse = False
re_groups_enabled = False
re_groups_pattern = 
re_groups_reverse = False
color_ok_text = #FFFFFF
default_color_ok_text = #FFFFFF
color_ok_background = #006400
default_color_ok_background = #006400
color_information_text = #000000
default_color_information_text = #000000
color_information_background = #7499FF
default_color_information_background = #7499FF
color_warning_text = #000000
default_color_warning_text = #000000
color_warning_background = #FFFF00
default_color_warning_background = #FFFF00
color_average_text = #000000
default_color_average_text = #000000
color_average_background = #FFA059
default_color_average_background = #FFA059
color_high_text = #000000
default_color_high_text = #000000
color_high_background = #E97659
default_color_high_background = #E97659
color_unknown_text = #000000
default_color_unknown_text = #000000
color_unknown_background = #FFA500
default_color_unknown_background = #FFA500
color_critical_text = #FFFFFF
default_color_critical_text = #FFFFFF
color_critical_background = #FF0000
default_color_critical_background = #FF0000
color_disaster_text = #FFFFFF
default_color_disaster_text = #FFFFFF
color_disaster_background = #660000
default_color_disaster_background = #660000
color_unreachable_text = #FFFFFF
default_color_unreachable_text = #FFFFFF
color_unreachable_background = #8B0000
default_color_unreachable_background = #8B0000
color_down_text = #FFFFFF
default_color_down_text = #FFFFFF
color_down_background = #000000
default_color_down_background = #000000
color_error_text = #000000
default_color_error_text = #000000
color_error_background = #D3D3D3
default_color_error_background = #D3D3D3
statusbar_floating = False
icon_in_systray = True
windowed = False
fullscreen = False
fullscreen_display = 0
systray_offset_use = False
systray_offset = 0
font = MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0,Standard
defaults_acknowledge_sticky = False
defaults_acknowledge_send_notification = False
defaults_acknowledge_persistent_comment = False
defaults_acknowledge_all_services = False
defaults_acknowledge_expire = False
defaults_acknowledge_expire_duration_hours = 2
defaults_acknowledge_expire_duration_minutes = 0
defaults_acknowledge_comment = acknowledged
defaults_submit_check_result_comment = check result submitted
defaults_downtime_duration_hours = 2
defaults_downtime_duration_minutes = 0
defaults_downtime_comment = scheduled downtime
defaults_downtime_type_fixed = True
defaults_downtime_type_flexible = False
keyring_available = False
use_system_keyring = False
re_criticality_enabled = False
re_criticality_pattern = 
re_criticality_reverse = False
unconfigured = False
save_config_after_urlencode = True
```

It happens on current stable, current dev and master version.

**Comment by HenriWahl** [comment]
A build which attempts to fix this is on its way - please try https://github.com/HenriWahl/Nagstamon/releases/tag/latest.
