### ISSUE TITLE
Connection with Zabbix: urlopen error Tunnel connection failed: 403 Tunnel or SSL Forbidden

### ISSUE THREAD

**Issue by Genluck** [HenriWahl/Nagstamon#728]
Hello.
I see this problem since version 3.4 or so. Currently tested version: 3.7-20210512 and problem is still there. Using a server profile with https on private IP address (but port is not 443). As result profile is giving an error: `Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: urllib2.URLError - <urlopen error Tunnel connection failed: 403 Tunnel or SSL Forbidden>`
Did try to use the same server configuration but without TLS and it worked great. Possible reason of the problem: 
> "free accounts on PythonAnywhere only have access to a limited set of external websites (the whitelist)"

Here is a debug log:
```
ERROR: 2021-05-14 11:59:09.380220 Zabbix Traceback (most recent call last):
  File "urllib\request.py", line 1346, in do_open
  File "http\client.py", line 1253, in request
  File "http\client.py", line 1299, in _send_request
  File "http\client.py", line 1248, in endheaders
  File "http\client.py", line 1008, in _send_output
OSError: Tunnel connection failed: 403 Tunnel or SSL Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Nagstamon\thirdparty\zabbix_api.py", line 254, in do_request
  File "urllib\request.py", line 517, in open
  File "urllib\request.py", line 534, in _open
  File "urllib\request.py", line 494, in _call_chain
  File "urllib\request.py", line 1389, in https_open
urllib.error.URLError: <urlopen error Tunnel connection failed: 403 Tunnel or SSL Forbidden>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Nagstamon\Servers\ZabbixProblemBased.py", line 82, in _get_status
  File "Nagstamon\thirdparty\zabbix_api.py", line 333, in method
  File "Nagstamon\thirdparty\zabbix_api.py", line 79, in wrapper
  File "Nagstamon\thirdparty\zabbix_api.py", line 340, in do_request
  File "Nagstamon\thirdparty\zabbix_api.py", line 264, in do_request
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: urllib2.URLError - <urlopen error Tunnel connection failed: 403 Tunnel or SSL Forbidden>
```

Configuration of the profile:
![изображение](https://user-images.githubusercontent.com/24607544/118250585-4f70c880-b4af-11eb-94fe-d6508c15de34.png)

And error message:
![изображение](https://user-images.githubusercontent.com/24607544/118250624-57306d00-b4af-11eb-8e04-15cf8e65f0ca.png)

**Comment by HenriWahl** [comment]
What would happen if the TLS port were 443? Looks like the underlaying urllib2 does not like other ports?

**Comment by Genluck** [comment]
Hi.
Finally was able to do a test :)
Yes, if using a standard 443 port it works without problems. Looks like urllib2 is really have problems with non-standard port of HTTPS.

**Comment by HenriWahl** [comment]
Strange at all that urllib2 shall be used by Python3 code. Apparently the Zabbix module should be somewhat updated, mayb just use the same code as the rest of Nagstamon. @mprenditore what do you think?

**Comment by HenriWahl** [comment]
As Zabbix module has been overhauled - is this still an issue?

**Comment by Genluck** [comment]
Hi.
For some time it is working correctly. Looks like it did help with issue.
