### ISSUE TITLE
Crash after update zabbix to 5.4 (Windows 10)

### ISSUE THREAD

**Issue by igorrim** [HenriWahl/Nagstamon#734]
commit cb6e7175ed9699a133f4d5e76275c7c60ae13ea8 (HEAD -> master, tag: latest, origin/master, origin/HEAD)

```
Faulting application name: python3.9.exe, version: 3.9.5150.1013, time stamp: 0x6090334e
Faulting module name: Qt5Core.dll, version: 5.15.2.0, time stamp: 0x5fa4dd3b
Exception code: 0xc0000409
Fault offset: 0x00000000000204e8
Faulting process id: 0x3528
Faulting application start time: 0x01d74d7f0f12a749
Faulting application path: C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\python3.9.exe
Faulting module path: C:\Users\Igor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyQt5\Qt5\bin\Qt5Core.dll
Report Id: 5836f155-1300-4057-99bf-781bf7c8d554
Faulting package full name: PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0
Faulting package-relative application ID: Python
```

```
Faulting application name: Nagstamon.exe, version: 0.0.0.0, time stamp: 0x5ffec13d
Faulting module name: Qt5Core.dll, version: 5.15.2.0, time stamp: 0x5fa4dd3b
Exception code: 0xc0000409
Fault offset: 0x00000000000204e8
Faulting process id: 0x87bc
Faulting application start time: 0x01d74d7f00b41529
Faulting application path: C:\otherprogram\Nagstamon\Nagstamon.exe
Faulting module path: C:\otherprogram\Nagstamon\Qt5Core.dll
Report Id: dc4da763-69eb-45e1-8e74-c68c4e1b5c6b
Faulting package full name: 
Faulting package-relative application ID: 
```

Manual run:
```
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
20: url: https://xxx.xxx.eu/api_jsonrpc.php
10: Trying to login with 'master':'md5(xxxxxx)'
10: json_obj: {'jsonrpc': '2.0', 'method': 'user.login', 'params': {'user': 'xxx', 'password': 'xxxxxx'}, 'id': 0}
20: Sending: {"jsonrpc": "2.0", "method": "user.login", "params": {"user": "xxx", "password": "xxxxxx"}, "id": 0}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
DEBUG: 2021-05-20 15:50:15.832802 Saving configuration to file c:\users\igor\.nagstamon\nagstamon.conf
DEBUG: 2021-05-20 15:50:16.827802 MEIBE Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C2280> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C21F0> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C2310> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C23A0> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C2430> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C24C0> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C2550> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C25E0> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C2670> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C2700> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031C2790> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x000002C1031C2040>
DEBUG: Initializing SystemTrayIcon
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': 'xxxxxxxxxx', 'id': 0}
10: json_obj: {'jsonrpc': '2.0', 'method': 'host.get', 'params': {'output': ['hostid', 'host', 'name', 'status', 'available', 'error', 'errors_from', 'snmp_available', 'snmp_error', 'snmp_errors_from', 'ipmi_available', 'ipmi_error', 'ipmi_errors_from', 'jmx_available', 'jmx_error', 'jmx_errors_from', 'maintenance_status', 'maintenance_from'], 'selectInterfaces': ['ip'], 'filter': {}}, 'auth': 'xxxxxxxxxx', 'id': 1}
20: Sending: {"jsonrpc": "2.0", "method": "host.get", "params": {"output": ["hostid", "host", "name", "status", "available", "error", "errors_from", "snmp_available", "snmp_error", "snmp_errors_from", "ipmi_available", "ipmi_error", "ipmi_errors_from", "jmx_available", "jmx_error", "jmx_errors_from", "maintenance_status", "maintenance_from"], "selectInterfaces": ["ip"], "filter": {}}, "auth": "xxxxxxxxxx", "id": 1}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F15E0> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F1550> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F1670> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F1700> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F1790> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F1820> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F18B0> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F1940> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F19D0> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F1A60> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000002C1031F1AF0> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x000002C1031F1B80>
DEBUG: 2021-05-20 15:50:19.357327 MEIBE FetchURL: https://nagstamon.de/version/unstable CGI Data: None
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [{'hostid': '10392', 'host': 'xxx.ru', 'name': 'xxx.ru', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '1.1.1.1'}]}, {'hostid': '10393', 'host': 'xxx.com', 'name': 'xxx.com', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '2.2.2.2'}]}, {'hostid': '10084', 'host': 'Zabbix server', 'name': 'Zabbix server', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '127.0.0.1'}]}, {'hostid': '10377', 'host': 'xxx.pro', 'name': 'xxx.pro', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '3.3.3.3'}]}, {'hostid': '10378', 'host': 'xxx.ru', 'name': 'xxx.ru', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '4.4.4.4'}]}, {'hostid': '10375', 'host': 'xxx.xxx.pl', 'name': 'xxx.xxx.pl', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '9.9.9.156'}]}, {'hostid': '10379', 'host': 'xxx.ru', 'name': 'xxx.ru', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '1.1.1.241'}]}, {'hostid': '10382', 'host': 'gd.pi', 'name': 'gd.pi', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '2.2.2.22'}]}, {'hostid': '10383', 'host': 'v.xxx.eu', 'name': 'v.xxx.eu', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '7.7.7.94'}]}, {'hostid': '10376', 'host': 'xxx.ru', 'name': 'xxx.ru', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '8.8.8.134'}]}, {'hostid': '10380', 'host': 'web.xxx.ru', 'name': 'web.xxx.ru', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '3.3.80.3'}]}, {'hostid': '10388', 'host': 'x.ru', 'name': 'x.ru', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '11.11.11.148'}]}, {'hostid': '10391', 'host': 'cp.xxx.eu', 'name': 'cp.xxx.eu', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '22.22.33.151'}]}, {'hostid': '10381', 'host': 'www.xxx.parts', 'name': 'www.xxx.parts', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '66.66.66.106'}]}, {'hostid': '10389', 'host': 'yy.ru', 'name': 'yy.ru', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '66.77.88.31'}]}, {'hostid': '10385', 'host': 'xx.xx.eu', 'name': 'xxx', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '12.12.12.241'}]}, {'hostid': '10390', 'host': 'mx.xxx.ltd', 'name': 'mx.xxx.ltd', 'status': '0', 'maintenance_status': '0', 'maintenance_from': '0', 'interfaces': [{'ip': '11.88.77.148'}]}], 'id': 1}
10: json_obj: {'jsonrpc': '2.0', 'method': 'apiinfo.version', 'params': {}, 'id': 2}
20: Sending: {"jsonrpc": "2.0", "method": "apiinfo.version", "params": {}, "id": 2}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': '5.4.0', 'id': 2}
10: json_obj: {'jsonrpc': '2.0', 'method': 'trigger.get', 'params': {'only_true': True, 'skipDependent': True, 'monitored': True, 'active': True, 'output': 'extend', 'expandDescription': True, 'selectHosts': ['hostid', 'host', 'name'], 'selectItems': ['itemid', 'name', 'key_', 'lastvalue', 'state', 'lastclock'], 'filter': {'value': 1}}, 'auth': 'xxxxxxxxxx', 'id': 3}
20: Sending: {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": "extend", "expandDescription": true, "selectHosts": ["hostid", "host", "name"], "selectItems": ["itemid", "name", "key_", "lastvalue", "state", "lastclock"], "filter": {"value": 1}}, "auth": "xxxxxxxxxx", "id": 3}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [{'triggerid': '19530', 'expression': '{24643}<{$MYSQL.BUFF_UTIL.MIN.WARN}', 'description': 'MySQL: Buffer pool utilization is too low (36.71% less 40% for 5m)', 'url': '', 'status': '0', 'value': '1', 'priority': '1', 'lastchange': '1621433998', 'comments': 'The buffer pool utilization is less than {$MYSQL.BUFF_UTIL.MIN.WARN}% in the last 5 minutes. This means that there is a lot of unused RAM allocated for the buffer pool, which you can easily reallocate at the moment.', 'error': '', 'templateid': '16757', 'type': '0', 'state': '0', 'flags': '0', 'recovery_mode': '0', 'recovery_expression': '', 'correlation_mode': '0', 'correlation_tag': '', 'manual_close': '0', 'opdata': '', 'discover': '0', 'event_name': '', 'uuid': '', 'hosts': [{'hostid': '10393', 'host': 'www.xxx.com', 'name': 'www.xxx.com'}], 'items': [{'itemid': '37498', 'name': 'MySQL: Buffer pool utilization', 'key_': 'mysql.buffer_pool_utilization', 'state': '0', 'lastclock': '1621518598', 'lastvalue': '36.715888627762176'}]}, {'triggerid': '18476', 'expression': '{22193}>=1', 'description': 'Site xxx.pro is down', 'url': '', 'status': '0', 'value': '1', 'priority': '5', 'lastchange': '1621496149', 'comments': '', 'error': '', 'templateid': '0', 'type': '0', 'state': '0', 'flags': '0', 'recovery_mode': '1', 'recovery_expression': '{22193}=0', 'correlation_mode': '0', 'correlation_tag': '', 'manual_close': '1', 'opdata': '', 'discover': '0', 'event_name': '', 'uuid': '', 'hosts': [{'hostid': '10377', 'host': 'xxx.pro', 'name': 'xxx.pro'}], 'items': [{'itemid': '35263', 'name': 'Failed step of scenario "xxx.pro".', 'key_': 'web.test.fail[xxx.pro]', 'state': '0', 'lastclock': '1621518565', 'lastvalue': '1'}]}, {'triggerid': '19116', 'expression': '{23305}<{$MYSQL.BUFF_UTIL.MIN.WARN}', 'description': 'MySQL: Buffer pool utilization is too low (8.95% less 40% for 5m)', 'url': '', 'status': '0', 'value': '1', 'priority': '1', 'lastchange': '1621503485', 'comments': 'The buffer pool utilization is less than {$MYSQL.BUFF_UTIL.MIN.WARN}% in the last 5 minutes. This means that there is a lot of unused RAM allocated for the buffer pool, which you can easily reallocate at the moment.', 'error': '', 'templateid': '16757', 'type': '0', 'state': '0', 'flags': '0', 'recovery_mode': '0', 'recovery_expression': '', 'correlation_mode': '0', 'correlation_tag': '', 'manual_close': '0', 'opdata': '', 'discover': '0', 'event_name': '', 'uuid': '', 'hosts': [{'hostid': '10389', 'host': 'xxx.ru', 'name': 'xxx.ru'}], 'items': [{'itemid': '36425', 'name': 'MySQL: Buffer pool utilization', 'key_': 'mysql.buffer_pool_utilization', 'state': '0', 'lastclock': '1621518605', 'lastvalue': '8.959115441745006'}]}], 'id': 3}
10: json_obj: {'jsonrpc': '2.0', 'method': 'trigger.get', 'params': {'only_true': True, 'skipDependent': True, 'monitored': True, 'active': True, 'output': ['triggerid'], 'expandDescription': True, 'selectHosts': ['hostid'], 'withLastEventUnacknowledged': True}, 'auth': 'xxxxxxxxxx', 'id': 4}
20: Sending: {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid"], "expandDescription": true, "selectHosts": ["hostid"], "withLastEventUnacknowledged": true}, "auth": "xxxxxxxxxx", "id": 4}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [{'triggerid': '19528', 'hosts': [{'hostid': '10393'}]}, {'triggerid': '19530', 'hosts': [{'hostid': '10393'}]}, {'triggerid': '18476', 'hosts': [{'hostid': '10377'}]}, {'triggerid': '19116', 'hosts': [{'hostid': '10389'}]}], 'id': 4}
10: json_obj: {'jsonrpc': '2.0', 'method': 'item.get', 'params': {'itemids': ['37498'], 'output': ['itemid', 'hostid', 'name', 'lastvalue'], 'selectApplications': 'extend'}, 'auth': 'xxxxxxxxxx', 'id': 5}
20: Sending: {"jsonrpc": "2.0", "method": "item.get", "params": {"itemids": ["37498"], "output": ["itemid", "hostid", "name", "lastvalue"], "selectApplications": "extend"}, "auth": "xxxxxxxxxx", "id": 5}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [{'itemid': '37498', 'hostid': '10393', 'name': 'MySQL: Buffer pool utilization', 'lastvalue': '36.715888627762176'}], 'id': 5}
Traceback (most recent call last):
  File "E:\WORK\Nagstamon\Nagstamon\QUI\__init__.py", line 4112, in get_status
    status = self.server.GetStatus()
  File "E:\WORK\Nagstamon\Nagstamon\Servers\Generic.py", line 866, in GetStatus
    status = self._get_status()
  File "E:\WORK\Nagstamon\Nagstamon\Servers\Zabbix.py", line 291, in _get_status
    t['application'] = self.getLastApp(this_item)
  File "E:\WORK\Nagstamon\Nagstamon\Servers\Zabbix.py", line 99, in getLastApp
    last_app = len(this_item[0]['applications']) - 1  # use it to get the last application name
KeyError: 'applications'
```

**Comment by HenriWahl** [comment]
Looks like some invalid server response?

**Comment by igorrim** [comment]
https://www.zabbix.com/documentation/current/manual/api/changes_5.2_-_5.4

I think the problems are due to changes in the api.
I'll try to look at the problem in more detail.

**Comment by SLMitch** [comment]
Hi
Yes, application disappear.

I do this "quick" corrective and it is OK (but I don't know if we can have better than "NO APP" for all rows)

diff --git a/Nagstamon/Servers/Zabbix.py b/Nagstamon/Servers/Zabbix.py
index 56980fc..782aac8 100644
--- a/Nagstamon/Servers/Zabbix.py
+++ b/Nagstamon/Servers/Zabbix.py
@@ -96,11 +96,7 @@ class ZabbixServer(GenericServer):
 
     def getLastApp(self, this_item):
         if len(this_item) > 0:
-            last_app = len(this_item[0]['applications']) - 1  # use it to get the last application name
-            if last_app > -1:
-                return "%s" % this_item[0]['applications'][last_app]['name']
-            else:
-                return "NO APP"
+            return "NO APP"
         else:
             return "Web scenario"

**Comment by igorrim** [comment]
@SLMitch thanks.
