### ISSUE TITLE
3.6.0: python core dump on startup

### ISSUE THREAD

**Issue by 0-wiz-0** [HenriWahl/Nagstamon#748]
After applying https://github.com/HenriWahl/Nagstamon/pull/747 I tried running nagstamon a NetBSD machine where I hadn't run it before (I've never used it before).
It causes a python coredump. The backtrace is:
```
Core was generated by `python3.8'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000075bd6e638485 in _dbus_list_unlink (list=list@entry=0x7f7fffea9420, link=link@entry=0x75bd70536c70) at dbus-list.c:509
509     dbus-list.c: No such file or directory.
[Current thread is 1 (process 17809)]
(gdb) bt
#0  0x000075bd6e638485 in _dbus_list_unlink (list=list@entry=0x7f7fffea9420, link=link@entry=0x75bd70536c70) at dbus-list.c:509
#1  0x000075bd6e638868 in _dbus_list_pop_first_link (list=list@entry=0x7f7fffea9420) at dbus-list.c:636
#2  0x000075bd6e613e7c in _dbus_connection_unlock (connection=connection@entry=0x75bd7103fb00) at dbus-connection.c:417
#3  0x000075bd6e616117 in _dbus_connection_acquire_dispatch (connection=connection@entry=0x75bd7103fb00) at dbus-connection.c:4135
#4  0x000075bd6e61828a in dbus_connection_dispatch (connection=0x75bd7103fb00) at dbus-connection.c:4604
#5  dbus_connection_dispatch (connection=0x75bd7103fb00) at dbus-connection.c:4576
#6  0x000075bd4e803115 in pyqt5DBusHelper::dispatch (this=0x75bd70597c90) at dbus.cpp:323
#7  0x000075bd660687f9 in QObject::event (this=0x75bd70597c90, e=0x75bd70c82320) at kernel/qobject.cpp:1314
#8  0x000075bd66f5fd8a in QApplicationPrivate::notify_helper (this=this@entry=0x75bd711d0880, receiver=receiver@entry=0x75bd70597c90, e=e@entry=0x75bd70c82320) at kernel/qapplication.cpp:3632
#9  0x000075bd66f67372 in QApplication::notify (this=this@entry=0x75bd711c2c60, receiver=receiver@entry=0x75bd70597c90, e=e@entry=0x75bd70c82320) at kernel/qapplication.cpp:3582
#10 0x000075bd67b103a2 in sipQApplication::notify (this=0x75bd711c2c60, a0=0x75bd70597c90, a1=0x75bd70c82320) at sipQtWidgetsQApplication.cpp:262
#11 0x000075bd6603cfab in QCoreApplication::notifyInternal2 (receiver=0x75bd70597c90, event=0x75bd70c82320) at kernel/qcoreapplication.cpp:1063
#12 0x000075bd6603d2c4 in QCoreApplication::sendEvent (receiver=receiver@entry=0x75bd70597c90, event=<optimized out>) at kernel/qcoreapplication.cpp:1458
#13 0x000075bd660409fe in QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x75bd73087480) at kernel/qcoreapplication.cpp:1817
#14 0x000075bd66040cb3 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1676
#15 0x000075bd6608ca05 in postEventSourceDispatch (s=s@entry=0x75bd711462e0) at kernel/qeventdispatcher_glib.cpp:277
#16 0x000075bd6ca58526 in g_main_dispatch (context=0x75bd7463e980) at ../glib/gmain.c:3337
#17 g_main_context_dispatch (context=context@entry=0x75bd7463e980) at ../glib/gmain.c:4055
#18 0x000075bd6ca58775 in g_main_context_iterate (context=context@entry=0x75bd7463e980, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4131
#19 0x000075bd6ca58893 in g_main_context_iteration (context=0x75bd7463e980, may_block=may_block@entry=1) at ../glib/gmain.c:4196
#20 0x000075bd6608c345 in QEventDispatcherGlib::processEvents (this=0x75bd70c8b000, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#21 0x000075bd6603b8cb in QEventLoop::exec (this=this@entry=0x7f7fffea9bc0, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#22 0x000075bd66044089 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#23 0x000075bd667018d7 in QGuiApplication::exec () at kernel/qguiapplication.cpp:1867
#24 0x000075bd66f5fcdf in QApplication::exec () at kernel/qapplication.cpp:2824
#25 0x000075bd67b0eda0 in meth_QApplication_exec_ (sipArgs=<optimized out>) at sipQtWidgetsQApplication.cpp:1857
#26 0x000075bd7548ad48 in cfunction_call_varargs (func=0x75bd6f101250, args=<optimized out>, kwargs=<optimized out>) at Objects/call.c:758
#27 0x000075bd7548b59c in _PyObject_MakeTpCall (callable=callable@entry=0x75bd6f101250, args=args@entry=0x75bd75aa4988, nargs=<optimized out>, keywords=keywords@entry=0x0) at Objects/call.c:159
#28 0x000075bd75618d27 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x75bd75aa4988, callable=0x75bd6f101250) at ./Include/cpython/abstract.h:125
#29 _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x75bd75aa4988, callable=0x75bd6f101250) at ./Include/cpython/abstract.h:115
#30 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x75bd75a5f000) at Python/ceval.c:4963
#31 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3469
#32 0x000075bd7555438c in _PyEval_EvalCodeWithName (_co=0x75bd7532db40, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=argcount@entry=0, kwnames=0x0, kwargs=0x0, kwcount=kwcount@entry=0, kwstep=kwstep@entry=2, 
    defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=name@entry=0x0, qualname=qualname@entry=0x0) at Python/ceval.c:4298
#33 0x000075bd755546f9 in PyEval_EvalCodeEx (_co=_co@entry=0x75bd7532db40, globals=globals@entry=0x75bd75969750, locals=locals@entry=0x75bd75969750, args=args@entry=0x0, argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=kwcount@entry=0, defs=0x0, 
    defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4327
#34 0x000075bd75554771 in PyEval_EvalCode (co=co@entry=0x75bd7532db40, globals=globals@entry=0x75bd75969750, locals=locals@entry=0x75bd75969750) at Python/ceval.c:718
#35 0x000075bd7558f144 in run_eval_code_obj (co=co@entry=0x75bd7532db40, globals=globals@entry=0x75bd75969750, locals=locals@entry=0x75bd75969750) at Python/pythonrun.c:1166
#36 0x000075bd7558f21a in run_mod (mod=mod@entry=0x75bd752ee930, filename=filename@entry=0x75bd75387620, globals=globals@entry=0x75bd75969750, locals=locals@entry=0x75bd75969750, flags=flags@entry=0x7f7fffeaa2f0, arena=arena@entry=0x75bd7538a440)
    at Python/pythonrun.c:1188
#37 0x000075bd75591ccc in pyrun_file (fp=fp@entry=0x75bd73e0ade0, filename=filename@entry=0x75bd75387620, start=start@entry=257, globals=globals@entry=0x75bd75969750, locals=locals@entry=0x75bd75969750, closeit=closeit@entry=1, 
    flags=flags@entry=0x7f7fffeaa2f0) at Python/pythonrun.c:1085
#38 0x000075bd75591e48 in pyrun_simple_file (flags=0x7f7fffeaa2f0, closeit=1, filename=0x75bd75387620, fp=0x75bd73e0ade0) at Python/pythonrun.c:439
#39 PyRun_SimpleFileExFlags (fp=fp@entry=0x75bd73e0ade0, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7f7fffeaa2f0) at Python/pythonrun.c:472
#40 0x000075bd755922ff in PyRun_AnyFileExFlags (fp=fp@entry=0x75bd73e0ade0, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7f7fffeaa2f0) at Python/pythonrun.c:90
#41 0x000075bd755af516 in pymain_run_file (cf=0x7f7fffeaa2f0, config=0x75bd75aa60b0) at Modules/main.c:385
#42 pymain_run_python (exitcode=0x7f7fffeaa2e4) at Modules/main.c:610
#43 Py_RunMain () at Modules/main.c:689
#44 0x000075bd755afae5 in pymain_main (args=args@entry=0x7f7fffeaa400) at Modules/main.c:719
#45 0x000075bd755afc18 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:743
#46 0x0000000000400acd in ___start ()
#47 0x00007f7fdee0d280 in ?? () from /usr/libexec/ld.elf_so
#48 0x0000000000000002 in ?? ()
#49 0x00007f7fffeaaaf8 in ?? ()
#50 0x00007f7fffeaab0f in ?? ()
#51 0x0000000000000000 in ?? ()
```
I have the following dependency versions installed:
```
qt5-qtwebkit-5.212.0.alpha4nb6
qt5-qtx11extras-5.15.2nb2
py38-qt5-5.15.2nb3
py38-OpenSSL-20.0.1
py38-certifi-2021.5.30
py38-chardet-4.0.0
py38-idna-2.10
py38-Socks-1.7.1
py38-urllib3-1.26.6
py38-requests-2.25.1
py38-decorator-4.4.2
py38-gssapi-1.6.12
py38-requests-gssapi-1.2.3
py38-jeepney-0.5.0
py38-secretstorage-3.2.0
```

Is there a particular config file I need to create or something else I need to provide in the environment for a successful startup?

**Comment by 0-wiz-0** [comment]
On stdout I see
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-wiz'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
```

**Comment by HenriWahl** [comment]
> On stdout I see
> 
> ```
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-wiz'
> QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
> ```
> 
> and a small window seems to pop up shortly, but much too quickly for me to see anything.

That QLayout error appears for a while, without any consequences.

In general I do not have any experience with running Nagstamon under any BSD, so I actually don't have any idea.

One attempt may be to install all needed dependencias via pip instead of the NetBSD packages, but even this is just guessing.

**Comment by HenriWahl** [comment]
Quite likely can't fix.
