### ISSUE TITLE
3.6.0: Crash on startup (macOS 10.14.6)

### ISSUE THREAD

**Issue by kamrhein** [HenriWahl/Nagstamon#752]
The App (binary release) crashes only a few seconds after double clicking its icon.

I have removed ~/.nagstamon/ to no avail (it is not being recreated).

There is no crash report being displayed.

The only error I see in the logs is
`Failed to copy signing info for 3571, responsible for file:///Applications/Nagstamon.app/Contents/MacOS/Nagstamon: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"`.

However, when I execute `$ /Applications/Nagstamon.app/Contents/MacOS/Nagstamon` in the Terminal, the process terminates with 
```
[Errno 2] No such file or directory: '/Users/kamrhein/.nagstamon/nagstamon.pid'
Traceback (most recent call last):
  File "Nagstamon/Servers/Generic.py", line 60, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "gssapi/__init__.py", line 29, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "gssapi/_win_config.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/var/folders/ff/f520w0kx4mq54hq1t68wf6f00000gn/T/_MEIUaqQkK/_ctypes.cpython-39-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /var/folders/ff/f520w0kx4mq54hq1t68wf6f00000gn/T/_MEIUaqQkK/_ctypes.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /var/folders/ff/f520w0kx4mq54hq1t68wf6f00000gn/T/_MEIUaqQkK/_ctypes.cpython-39-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nagstamon.py", line 45, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "Nagstamon/QUI/__init__.py", line 61, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "Nagstamon/Servers/__init__.py", line 36, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "Nagstamon/Servers/Nagios.py", line 20, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "Nagstamon/Servers/Generic.py", line 63, in <module>
ModuleNotFoundError: No module named 'requests_kerberos'
```

The issue remains when I manually install requests_kerberos with pip3.
I have 
```
$ python3 -V
Python 3.9.5
$ python -V
Python 2.7.16
```

**Comment by HenriWahl** [comment]
requests_kerberos won't help here because Nagstamon comes with its own modules.

What might help is an update of your macOS installation, because Nagstamon is built on macOS 10.15 - quite likely that older versions do not work.

If you need to stay with your current OS version, just consider to build your own DMG installer as it it easily done following the steps at https://nagstamon.de/documentation#requirements and running the `build.sh` script at _/build_.

**Comment by kamrhein** [comment]
Thanks for looking into it. I need to stay with 10.14, so I built the installer as suggested and now it works.
