### ISSUE TITLE
Alertmanager: json.decoder.JSONDecodeError is shown instead of password mismatch

### ISSUE THREAD

**Issue by varac** [HenriWahl/Nagstamon#753]
When the alermanager passwords doesn't match, this is shown in the UI which is pretty confusing:

![image](https://user-images.githubusercontent.com/488213/127990194-abddddda-c133-4eb7-8d3b-622ff3d57a7b.png)

This is the log section:

```
ERROR: 2021-08-03 11:04:07.915725 example.org Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Alertmanager.py", line 120, in _get_status
    data = json.loads(result.result)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

DEBUG: 2021-08-03 11:04:21.143853 oas.greenhost.net Refreshing all hosts and services
DEBUG: 2021-08-03 11:04:21.143909 example.org Refreshing all hosts and services
DEBUG: 2021-08-03 11:04:21.515742 oas.greenhost.net detection config (map_to_status_information): 'message,summary,description'
DEBUG: 2021-08-03 11:04:21.515786 oas.greenhost.net detection config (map_to_hostname): 'pod_name,namespace,instance'
DEBUG: 2021-08-03 11:04:21.515798 oas.greenhost.net detection config (map_to_servicename): 'alertname'
DEBUG: 2021-08-03 11:04:21.515811 oas.greenhost.net detection config (alertmanager_filter): ''
DEBUG: 2021-08-03 11:04:21.515831 oas.greenhost.net FetchURL: https://alertmanager.oas.greenhost.net/api/v2/alerts CGI Data: None
DEBUG: 2021-08-03 11:04:21.893294 oas.greenhost.net received status code '401' with this content in result.result:
-----------------------------------------------------------------------------------------------------------------------------
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

The US should rather show `Aurthentication failure` or sth like this.

**Comment by HenriWahl** [comment]
Can you please try the latest testing release from https://github.com/HenriWahl/Nagstamon/releases/tag/latest ?

**Comment by varac** [comment]
Unfortunatly I get this with latest release .deb:

```
❯ sudo dpkg -i ~/Downloads/nagstamon_3.7-20210823_all.deb 

(Reading database ... 410173 files and directories currently installed.)
Preparing to unpack .../nagstamon_3.7-20210823_all.deb ...
Unpacking nagstamon (3.7-20210823) over (3.7-20210503) ...
Setting up nagstamon (3.7-20210823) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu1) ...
Processing triggers for mailcap (3.68ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.4-2) ...

❯ nagstamon 
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 45, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 61, in <module>
    from Nagstamon.Servers import (SERVER_TYPES,
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/__init__.py", line 54, in <module>
    from Nagstamon.Servers.Alertmanager import AlertmanagerServer
ModuleNotFoundError: No module named 'Nagstamon.Servers.Alertmanager'
```

**Comment by varac** [comment]
Downgrading to https://github.com/HenriWahl/Nagstamon/releases/tag/v3.6.0 deb fixed this `ModuleNotFoundError` for me

**Comment by HenriWahl** [comment]
@varac please check latest version 20210825
