### ISSUE TITLE
3.7-20210518 Zabbix 5.4 Crash on schedule downtime

### ISSUE THREAD

**Issue by hunsbea** [HenriWahl/Nagstamon#755]
![image](https://user-images.githubusercontent.com/5019061/128131891-9555cdaa-df28-4096-b97c-ce1ff41cafdb.png)

Nagstamon version 3.7-20210518
Zabbix version 5.4 latest

When I right-click a row in Nagstamon, select Schedule Downtime, and click OK, Nagstamon crashes, and does not create the downtime.

The funny thing is, it actually works ONCE. I mean, If there are currently NO scheduled down times in Zabbix, then this feature works and creates the downtime. But if there are any existing downtimes in Zabbix maintenance, then this fails, and Nagstamon crashes.

I enabled debug and debug logs, but Nagstamon does not write anything to the debug file, so I can't be any more help there.

This is a great great feature, so I hope it can be fixed soon! Let me know if you need any additional details.

**Comment by HenriWahl** [comment]
Are yo able to run Nagstamon from source in console so we could get the actual error?

**Comment by hunsbea** [comment]
I will try to set that up and will get back to you.

**Comment by hunsbea** [comment]
Are there any instructions on how to build from source besides https://nagstamon.de/documentation ?

I've tried building on Windows 10 with Python 3.6, and I've tried building on Ubuntu 20.04 with Python 3.8, and both builds failed similarly.

On Windows, I did:
```
pip install -r build\requirements\windows.txt
python setup.py install
```
and I get:
```
C:\...\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'executables'
  warnings.warn(msg)
C:\...\venv\lib\site-packages\setuptools\dist.py:485: UserWarning: The version specified ('3.7.20210809.') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
writing Nagstamon.egg-info\PKG-INFO
writing dependency_links to Nagstamon.egg-info\dependency_links.txt
writing top-level names to Nagstamon.egg-info\top_level.txt
reading manifest file 'Nagstamon.egg-info\SOURCES.txt'
writing manifest file 'Nagstamon.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
installing package data to build\bdist.win-amd64\egg
running install_data
installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
error: [Errno 13] Permission denied: 'nagstamon'
```
Note that I'm running from an Administrator command prompt so there's no reason to get permission denied.

And on Ubuntu, I similarly did:
```
pip install -r build/requirements/linux.txt
python setup.py install
```
And I get:
```
/.../python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'executables'
  warnings.warn(msg)
/.../venv/lib/python3.8/site-packages/setuptools/dist.py:481: UserWarning: The version specified ('3.7.20210809.ubuntu20.04') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
running bdist_egg
running egg_info
writing nagstamon.egg-info/PKG-INFO
writing dependency_links to nagstamon.egg-info/dependency_links.txt
writing top-level names to nagstamon.egg-info/top_level.txt
reading manifest file 'nagstamon.egg-info/SOURCES.txt'
writing manifest file 'nagstamon.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
installing package data to build/bdist.linux-x86_64/egg
running install_data
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
error: [Errno 21] Is a directory: 'nagstamon'
```

**Comment by hunsbea** [comment]
Sorry, I'm an idiot, here's the CLI output of sending a downtime request:
```
(venv) PS C:\...\Nagstamon> python .\nagstamon.py
[Errno 2] No such file or directory: 'C:\\...\\.nagstamon\\nagstamon.pid'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Traceback (most recent call last):
  File "C:\...\Nagstamon\Nagstamon\QUI\__init__.py", line 4328, in downtime
    self.server.set_downtime(info_dict)
  File "C:\...\Nagstamon\Nagstamon\Servers\Generic.py", line 462, in set_downtime
    info_dict['minutes'])
  File "C:\...\Nagstamon\Nagstamon\Servers\Zabbix.py", line 507, in _set_downtime
    { "timeperiod_type": 0, "start_date": stime, "period": etime - stime }
  File "C:\...\Nagstamon\Nagstamon\thirdparty\zabbix_api.py", line 333, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "C:\...\Nagstamon\Nagstamon\thirdparty\zabbix_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "C:\...\Nagstamon\Nagstamon\thirdparty\zabbix_api.py", line 340, in do_request
    return self.parent.do_request(req)
  File "C:\...\Nagstamon\Nagstamon\thirdparty\zabbix_api.py", line 288, in do_request
    raise Already_Exists(msg, jobj['error']['code'])
Nagstamon.thirdparty.zabbix_api.Already_Exists: ('Error -32602: Invalid params., Maintenance "scheduled downtime" already exists. while sending {"jsonrpc": "2.0", "method": "maintenance.create", "params": {"hostids": ["10627"], "name": "scheduled downtime", "description": "hunsbea", "active_since": 1628851080.0, "active_till": 1628858280.0, "maintenance_type": 0, "timeperiods": [{"timeperiod_type": 0, "start_date": 1628851080.0, "period": 7200.0}]}, "auth": "b18a045a99752cc7cae5b32755261667", "id": 37}', -32602)
(venv) PS C:\...\Nagstamon>
```
The error seems to be that this maintenance window already exists, although of course it doesn't. Or ... perhaps it's taking the name to be a primary key now, when before it wasn't?

Since I'm able to run the code now, I'll take a look at trying to fix it myself this weekend. If I succeed, I'll raise a PR for it.

Cheers.

**Comment by hunsbea** [comment]
I would like to build the windows installer so that I can share these changes with my coworkers. Do you have instructions for doing that?

Otherwise, are you planning to release another binary install soon? If it also includes https://github.com/HenriWahl/Nagstamon/pull/757 then that would be perfect.

This issue can be closed, but I hope you can help me out with how to package this for Windows. Thanks a lot.

**Comment by hunsbea** [comment]
Okay ignore my last comment, I was trying to run 
```
python setup.py build
```
but I should have been running
```
python build.py
```
from the build/ directory. It works now and I was able to build the windows installer, cheers.
