### ISSUE TITLE
Crash while acknowledge at CheckMK 2.x

### ISSUE THREAD

**Issue by SkeeveKlah** [HenriWahl/Nagstamon#763]
NM crashes while doing a problem acknowledge at CheckMK 2.x.
Happens with NM 3.6 and 3.7 64bit on Windows 10. The acknowledge is not done.

**Comment by HenriWahl** [comment]
Can you run Nagstamon from source in a console window to get some output of a crash?

**Comment by SkeeveKlah** [comment]
Well... hope thats right ;-)

QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Traceback (most recent call last):
  File "D:\Downloads\Nagstamon-latest\Nagstamon\QUI\__init__.py", line 4315, in acknowledge
    self.server.set_acknowledge(info_dict)
  File "D:\Downloads\Nagstamon-latest\Nagstamon\Servers\Generic.py", line 394, in set_acknowledge
    self._set_acknowledge(info_dict['host'],
  File "D:\Downloads\Nagstamon-latest\Nagstamon\Servers\Multisite.py", line 495, in _set_acknowledge
    self._action(self.hosts[host].site, host, service, p)
  File "D:\Downloads\Nagstamon-latest\Nagstamon\Servers\Multisite.py", line 463, in _action
    transid = self._get_transid(host, service)
  File "D:\Downloads\Nagstamon-latest\Nagstamon\Servers\Multisite.py", line 528, in _get_transid
    transid = self.FetchURL(self.urls['transid'].replace('$HOST$', host).replace('$SERVICE$', service.replace(' ', '+')),\
TypeError: 'NoneType' object is not subscriptable

**Comment by HenriWahl** [comment]
Thanks, looks good, needs more investigation and thus time.

**Comment by HenriWahl** [comment]
What Checkmk version do you use? I have no problems with 2.0.0p9.

**Comment by SkeeveKlah** [comment]
Yes, at the moment we use 2.0.0p9.
But issue is there since the upgrade from 1.6 to 2.
With the upgrade there was a lot changes to the webinterface.

**Comment by SkeeveKlah** [comment]
I tested it again, one acknowledge worked at the second try, but then Nagstamon crashes. Second event and Nagstamon crashed at first try.
