### ISSUE TITLE
Nagstamon latest not starting on MacOS 11.5.2

### ISSUE THREAD

**Issue by stearz** [HenriWahl/Nagstamon#771]
Starting latest Nagstamon (3.7-20210901) on MacOS 11.5.2 (20G95) throws this error:

```
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/CREDITS
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/LICENSE
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/close_template.svg
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/critical.wav
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/down.wav
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/menu_template.svg
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.1
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.1.gz
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.appdata.xml
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.desktop
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.icns
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.ico
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.rst
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.sfd
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.svg
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon.ttf
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon_logo_bar.svg
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon_logo_toparea_template.svg
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon_systrayicon_empty.svg
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/nagstamon_systrayicon_template.svg
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/qt.conf
[9079] WARNING: file already exists but should not: /var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/../Nagstamon/resources/warning.wav
qt.svg: Cannot open file '/var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/Nagstamon/resources/nagstamon.svg', because: No such file or directory
Traceback (most recent call last):
  File "nagstamon.py", line 45, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "Nagstamon/QUI/__init__.py", line 7224, in <module>
  File "Nagstamon/QUI/__init__.py", line 4573, in __init__
  File "Nagstamon/QUI/__init__.py", line 6796, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/rw/d_f4thvd77s5p8nhhzbth0nx3jn9rl/T/_MEIEpNFww/Nagstamon/resources/LICENSE'
```

**Comment by HenriWahl** [comment]
Which one was the last that worked?

**Comment by HenriWahl** [comment]
At least I can confirm the issue - same on macOS 10.5.

**Comment by dotsam** [comment]
I was actually just looking at this earlier today. I believe this happened when you moved the `.spec` file into a subdirectory. The `datas` destination path got a directory traversal when it shouldn't have. Changing it to
```
datas=[('../../Nagstamon/resources', 'Nagstamon/resources')]
```

should fix it I believe

**Comment by HenriWahl** [comment]
Yes, this is what I found too and already compiled a working version. Thanks for taking a look too!

@stearz please try with lates 20210908 - works for me.

**Comment by stearz** [comment]
@HenriWahl The latest lates 20210908 is working fine. - Wow, that was a very quick fix. I close the issue now.
