### ISSUE TITLE
Nagstamon crashes on launch with sensu server configured. -> with fix

### ISSUE THREAD

**Issue by eaxdword** [HenriWahl/Nagstamon#776]
OS: MacOS
Nagstamon version to reproduce: 3,6; 3,7

Issue description:  Crashes Nagstamon app on launch. 

Error in debug: 
`Traceback (most recent call last):
  File "/Users/username/Nagstamon/Nagstamon/QUI/__init__.py", line 4119, in get_status
    status = self.server.GetStatus()
  File "/Users/username/Nagstamon/Nagstamon/Servers/Generic.py", line 1402, in GetStatus
    print(service.get_hash())
  File "/Users/username/Nagstamon/Nagstamon/Objects.py", line 168, in get_hash
    return " ".join((self.server, self.site, self.host, self.name, self.status))
TypeError: sequence item 4: expected str instance, NoneType found`

The issue caused by:
bug in https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/Sensu.py
lines: 135 - 138

In case check returned any code that is other than 3(UNKNOWN) we will get nagstamon crashed due to the following code exception block:
`                try:
                    new_service.status = self.SEVERITY_CODE_TEXT_MAP.get(event_check['status'])
                except KeyError:
                    new_service.status = 'UNKNOWN'`

.get will never return KeyError, it returns None type by default. 

Fix: 

remove get and access dict directly: 

`          new_service.status = self.SEVERITY_CODE_TEXT_MAP[event_check['status']]`

this will rise KeyError and code will work as expected.

**Comment by eaxdword** [comment]
Merged, issue fixed
