### ISSUE TITLE
Setup invalid monitor url and 'cookies' -> fatal error, config lost

### ISSUE THREAD

**Issue by MilanDadok** [HenriWahl/Nagstamon#790]
I found that changing in configuration dialog correct url of Icinga2Web (ie. from https://server/icingaweb2 to https://server/ for example) give fatal error and config file of server is lost from disk (3.8.0, 3.6.0 win64 installer)

Traceback (most recent call last):.  File "Nagstamon\QUI\__init__.py", line 4119, in get_status.  File "Nagstamon\Servers\Generic.py", line 905, in GetStatus.  File "Nagstamon\Servers\IcingaWeb2.py", line 100, in init_HTTP.AttributeError: 'NoneType' object has no attribute 'cookies'
(it's from memory dump)

in Nagstamon/Servers/IcingaWeb2.py  on line 99,100 there is 
 if not self.no_cookie_auth:
   if len(self.session.cookies) == 0:

I thing that correct way in all servers implementation with cookies is 
 if not self.no_cookie_auth:
  if 'cookies' not in dir(self.session) or len(self.session.cookies) == 0:
or something like that

**Comment by HenriWahl** [comment]
Please check latest binaries from https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by MilanDadok** [comment]
if self.session.get('cookies') and len(self.session.cookies) == 0:
give me exception on every start (exe terminates silently)

Traceback (most recent call last):
  File "D:\InternetSources\nagstatmon\Nagstamon-master\Nagstamon\QUI\__init__.py", line 4119, in get_status
    status = self.server.GetStatus()
  File "D:\InternetSources\nagstatmon\Nagstamon-master\Nagstamon\Servers\Generic.py", line 863, in GetStatus
    self.init_HTTP()
  File "D:\InternetSources\nagstatmon\Nagstamon-master\Nagstamon\Servers\IcingaWeb2.py", line 100, in init_HTTP
    if self.session.get('cookies') and len(self.session.cookies) == 0:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'cookies': No schema supplied. Perhaps you meant http://cookies?

next two version works for me as expected
            if 'cookies' not in dir(self.session) or len(self.session.cookies) == 0:
            if self.session == None or len(self.session.cookies) == 0:
ie. invalid url -> authentication problem

**Comment by HenriWahl** [comment]
Can you create a pull request or show the exact lines you changed?

**Comment by MilanDadok** [comment]
always Nagstamon/Servers/IcingaWeb2.py line 100
for source file I'm using ZIP archive, for now I cannot create pull request ...

**Comment by HenriWahl** [comment]
Could you try the latest binary?

**Comment by MilanDadok** [comment]
Don't work, same exception 
self.session.get('cookies') - For me it looks like that function is trying to get content of uri 'cookies', not value of 'cookies' header of current http session ...

Traceback (most recent call last):
  File "D:\InternetSources\nagstatmon\Nagstamon-master\Nagstamon\QUI\__init__.py", line 4119, in get_status
    status = self.server.GetStatus()
  File "D:\InternetSources\nagstatmon\Nagstamon-master\Nagstamon\Servers\Generic.py", line 863, in GetStatus
    self.init_HTTP()
  File "D:\InternetSources\nagstatmon\Nagstamon-master\Nagstamon\Servers\IcingaWeb2.py", line 100, in init_HTTP
    if not self.session.get('cookies') or len(self.session.cookies) == 0:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'cookies': No schema supplied. Perhaps you meant http://cookies?

**Comment by HenriWahl** [comment]
Stupid me... you are right. .get is an already existing method for HTTP-GET-requests... I changed to your proposal and currently the binaries are going to be built.

**Comment by MilanDadok** [comment]
From source files all works with python 3.6 from VS

But from exe- that is not runnable on Windows 8.1, Windows Server 2016, 2019
               GetModuleHandleExW ( 0, "mscoree.dll", 0x000000c098c2f6f8 ) FALSE    126 0.0000068
After that ExitProcess(0) is called ...

Something is wrong with build ...

Milan Dadok

**Comment by HenriWahl** [comment]
Could you build the executable on such a machine?

**Comment by HenriWahl** [comment]
Any news?
