### ISSUE TITLE
Nagstamon 3.8.0-win64 - certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by sronline** [HenriWahl/Nagstamon#794]
When connection fails (eg. by using windows standby), Nagstamon reports "certificate verify failed: unable to get local issuer certificate" in the log and does not update any more. Icon schows state Error (which has been set to this color in the settings):

![grafik](https://user-images.githubusercontent.com/17158346/149167847-1af1acfe-d01c-4629-bb6f-08016b10dcd2.png)

Connection is only re-established by using the button "Fix error".

Settings:
![grafik](https://user-images.githubusercontent.com/17158346/149170685-2c37e0fe-aea7-4805-bbed-bd0e0384bb34.png)

Debug log shows:
[Debug.log](https://github.com/HenriWahl/Nagstamon/files/7855613/Debug.log)

DEBUG: 2022-01-12 10:44:02.124165 Check_Mk FetchURL: https://.../sr/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
ERROR: 2022-01-12 10:44:04.794318 Check_Mk Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 416, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

**Comment by gu-LGB** [comment]
I have the same problem after updating to Checkmk 2.0.0p17 (from p15).
However, the problem cannot be solved for me by clicking on "Fix error".

The configuration looks very similar:
![image](https://user-images.githubusercontent.com/6780678/149284743-e75cd1de-4fdc-45b9-879d-a9ec72eac1a7.png)

The debug-Log to:

```
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x00000242ACE19280>
DEBUG: 2022-01-13 08:18:25.420405 LGB Prod FetchURL: https://monitoring.lgb.local//lgb/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE19790> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE19700> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE19820> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE198B0> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE19940> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE199D0> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE19A60> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE19AF0> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE19B80> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE19C10> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000242ADE19CA0> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x00000242ADE19D30>
DEBUG: 2022-01-13 08:18:25.736791 LGB Prod FetchURL: https://monitoring.lgb.local//lgb/check_mk/login.py CGI Data: {'_username': 'ulbrichg', '_password': '***************', '_login': '1', '_origtarget': '', 'filled_in': ' login'}
DEBUG: 2022-01-13 08:18:25.922307 LGB Prod FetchURL: https://monitoring.lgb.local//lgb/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
DEBUG: 2022-01-13 08:18:25.990129 LGB Prod FetchURL: https://monitoring.lgb.local//lgb/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
ERROR: 2022-01-13 08:18:26.037028 LGB Prod Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 416, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='monitoring.lgb.local', port=443): Max retries exceeded with url: //lgb/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Nagstamon\Servers\Generic.py", line 1499, in FetchURL
  File "requests\sessions.py", line 555, in get
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='monitoring.lgb.local', port=443): Max retries exceeded with url: //lgb/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

**Comment by HenriWahl** [comment]
This looks strange. The result is that there is no state shown?

**Comment by gu-LGB** [comment]
Yes, nothing is shown:
![image](https://user-images.githubusercontent.com/6780678/150735204-031a53c5-2f88-4cf3-9d06-a48832a46986.png)

No, even after restarting the computer or restarting Nagstamon. After Check-MK Support reported that Nagstamon 3.8.0 (Linunx Client) + CheckMK 2p17 worked for him, we also recreated it for us. Same problem as on Windows.

Maybe you can contact Karsten (karsten.schoeke@geobasis-bb.de / 0335 5582553)? He administrates CheckMK for us and can give details about the certificate.

**Comment by gu-LGB** [comment]
We have found a user here who can access our CheckMK server via Nagstamon without any problems. We still have to find out what is different in her LDAP or whether it is because she is not an admin at CheckMK.

But it also shows that the error message from Nagstamon is incorrect (certificate verify failed: unable to get local issuer certificate)

**Comment by gu-LGB** [comment]
We updated today from checkmk 2p17 -> 2p19. Here the authentication with Nagstamon works again for everyone...
