### ISSUE TITLE
Nagstamon 3.10 configured with Zabbix servers crashes when starting in MacOS Monterey

### ISSUE THREAD

**Issue by yuri-ccp** [HenriWahl/Nagstamon#862]
Today I updated Nagstamon 3.8 to 3.10 but it's crashes soon when open icon in systray. Running in terminal I notice that it's reports crashes after get info from my Zabbix 5 server:

```
➜  ~ /Applications/Nagstamon.app/Contents/MacOS/Nagstamon        
qt.qpa.fonts: Populating font family aliases took 287 ms. Replace uses of missing font family ".SF NS Text" with one that exists to avoid this cost. 
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
20: url: http://zabbix..../api_jsonrpc.php
10: Trying to login with '...':'sha256(0215b300b72dd275d7881fe1cdb19e6f7291f4aa405a2a6a29b71a17cfbea889)'
10: json_obj: {'jsonrpc': '2.0', 'method': 'user.login', 'params': {'user':...}
20: Sending: {"jsonrpc": "2.0", "method": "user.login", "params": {"user": ...}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
20: Set logging level to 10
20: url: https://zabbix5..../api_jsonrpc.php
10: Trying to login with '...':'sha256(f64470005ac9e772e29ca173fa145b3ff69a8041dfb0bef5924f2b8e2ce49705)'
10: json_obj: {'jsonrpc': '2.0', 'method': 'user.login', 'params': {'user':...}
20: Sending: {"jsonrpc": "2.0", "method": "user.login", "params": {"user":...}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
DEBUG: 2022-10-28 10:11:34.137288 Saving configuration to file /Users/yuri/.nagstamon/nagstamon.conf
DEBUG: 2022-10-28 10:11:34.661466 Zabbix K2host Created server.
DEBUG: 2022-10-28 10:11:34.661677 Zabbix5 K2host Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111676b90> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111676b00> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111676c20> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111676cb0> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111676d40> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111676dd0> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111676e60> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111676ef0> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111676f80> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x111677010> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x1116770a0> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt6.QtGui.QIcon object at 0x111676950>
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': '353166b30729f1f3c40b8dbb77dfc514', 'id': 0}
10: json_obj: {'jsonrpc': '2.0', 'method': 'apiinfo.version', 'params': {}, 'id': 1}
20: Sending: {"jsonrpc": "2.0", "method": "apiinfo.version", "params": {}, "id": 1}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': '2.2.23', 'id': 1}
10: json_obj: {'jsonrpc': '2.0', 'method': 'maintenance.get', 'params': {'output': ['active_since', 'active_till', 'tags'], 'selectTags': 'extend'}, 'auth': '353166b30729f1f3c40b8dbb77dfc514', 'id': 2}
20: Sending: {"jsonrpc": "2.0", "method": "maintenance.get", "params": {"output": ["active_since", "active_till", "tags"], "selectTags": "extend"}, "auth": "353166b30729f1f3c40b8dbb77dfc514", "id": 2}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
DEBUG: 2022-10-28 10:11:35.630707 Zabbix K2host FetchURL: https://nagstamon.de/version/stable CGI Data: None
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [], 'id': 2}
10: json_obj: {'jsonrpc': '2.0', 'method': 'trigger.get', 'params': {'only_true': True, 'skipDependent': True, 'monitored': True, 'active': True, 'output': ['triggerid', 'description', 'lastchange', 'manual_close'], 'selectLastEvent': ['eventid', 'name', 'ns', 'clock', 'acknowledged', 'value', 'severity'], 'selectHosts': ['hostid', 'host', 'name', 'status', 'available', 'maintenance_status', 'maintenance_from'], 'selectItems': ['name', 'lastvalue', 'state', 'lastclock'], 'filter': {'value': 1}}, 'auth': '353166b30729f1f3c40b8dbb77dfc514', 'id': 3}
20: Sending: {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid", "description", "lastchange", "manual_close"], "selectLastEvent": ["eventid", "name", "ns", "clock", "acknowledged", "value", "severity"], "selectHosts": ["hostid", "host", "name", "status", "available", "maintenance_status", "maintenance_from"], "selectItems": ["name", "lastvalue", "state", "lastclock"], "filter": {"value": 1}}, "auth": "353166b30729f1f3c40b8dbb77dfc514", "id": 3}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [{'triggerid': '32731', 'description': 'Muitas conexões no MySQL: {ITEM.LASTVALUE}', 'lastchange': '1664940881', 'hosts': [{'hostid': '10165', 'host':...}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': '9488ce4235e283f572ec1bc7c00be456', 'id': 0}
10: json_obj: {'jsonrpc': '2.0', 'method': 'apiinfo.version', 'params': {}, 'id': 1}
20: Sending: {"jsonrpc": "2.0", "method": "apiinfo.version", "params": {}, "id": 1}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
20: Response Code: 200
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': '5.0.28', 'id': 1}
10: json_obj: {'jsonrpc': '2.0', 'method': 'maintenance.get', 'params': {'output': ['active_since', 'active_till', 'tags'], 'selectTags': 'extend'}, 'auth': '9488ce4235e283f572ec1bc7c00be456', 'id': 2}
20: Sending: {"jsonrpc": "2.0", "method": "maintenance.get", "params": {"output": ["active_since", "active_till", "tags"], "selectTags": "extend"}, "auth": "9488ce4235e283f572ec1bc7c00be456", "id": 2}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
10: Response Body: {'jsonrpc': '2.0', 'result': [{'hostid': '10156', 'host': ...}
Traceback (most recent call last):
  File "Nagstamon/QUI/__init__.py", line 3998, in get_status
  File "Nagstamon/Servers/Generic.py", line 900, in GetStatus
  File "Nagstamon/Servers/Zabbix.py", line 362, in _get_status
KeyError: 'severity'
[1]    30056 abort      /Applications/Nagstamon.app/Contents/MacOS/Nagstamon
```
Obs.: Some info was removed to prevent leakage from my servers, users and passwords.

**Comment by HenriWahl** [comment]
What Zabbix version is this?

**Comment by yuri-ccp** [comment]
There's 2 servers with different zabbix versions. One is 2.2.23 the other is 5.0.28.

**Comment by yuri-ccp** [comment]
I tested here and just the 2.2.23 is crashing Nagtamon. When I enable the Zabbix 5 server only it's works fine.

**Comment by HenriWahl** [comment]
@mprenditore @hunsbea any idea?

**Comment by HenriWahl** [comment]
@yuri-ccp did you meanwhile update all Zabbix servers to some newer releases?

**Comment by yuri-ccp** [comment]
Yes I updated all my servers' agents to Zabbix 5, so I no logger had anymore problem with it.
Once that Zabbix 2 aren't supported version anymore I think we can close this issue.
