### ISSUE TITLE
Can't connect to display ":0": b'Authorization required, but no authorization protocol specified

### ISSUE THREAD

**Issue by dacrhu** [HenriWahl/Nagstamon#877]
Hi,

OS: Fedora 37
Kernel: Linux fedora 6.0.8-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC
Window manager: Wayland
Graphics (dual): NVIDIA GeForce RTX™ 3050 Ti Laptop GPU / AMD Radeon™ Graphics

Nagstamon version: 
nagstamon.noarch                                     3.10.1.fedora37-1                   @nagstamon

Console out:

[berci@fedora ~]$ nagstamon
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 42, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3.11/site-packages/Nagstamon/QUI/__init__.py", line 7058, in <module>
    statuswindow = StatusWindow()
                   ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/QUI/__init__.py", line 955, in __init__
    self.ewmh = EWMH()
                ^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/thirdparty/ewmh.py", line 50, in __init__
    self.display = _display or display.Display()
                               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/thirdparty/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/thirdparty/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3.11/site-packages/Nagstamon/thirdparty/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'

Thank you for help!
David

**Comment by HenriWahl** [comment]
@dacrhu did it work before? Anything changed like Fedora upgrade from 36 to 37?

**Comment by HenriWahl** [comment]
A short local fix is installing the package **python3-pyqt6**. Nagstamon needs this for running on Wayland but apparently the dependency in the RPM-File is still on Qt5 - will fix this ASAP.

**Comment by dacrhu** [comment]
It worked before, yes. I upgraded to 37, and worked fine. But yesterday I shutted down my notebook, and it runned auto upgrade. In this morning nagstamon not runned again. I think yesterday nagstamon upgraded.

I've installed python3-pyqt6 now but result is same.

**Comment by dacrhu** [comment]
Sorry, result is little bit different:

Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 42, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3.11/site-packages/Nagstamon/QUI/__init__.py", line 7058, in <module>
    statuswindow = StatusWindow()
                   ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/QUI/__init__.py", line 955, in __init__
    self.ewmh = EWMH()
                ^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/thirdparty/ewmh.py", line 50, in __init__
    self.display = _display or display.Display()
                               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/thirdparty/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/thirdparty/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3.11/site-packages/Nagstamon/thirdparty/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'

**Comment by HenriWahl** [comment]
@dacrhu what happens if you use Xorg instead of Wayland?

**Comment by dacrhu** [comment]
With Xorg working fine.

**Comment by HenriWahl** [comment]
Wayland support by Qt got better with Qt6 but there are still issues for Nagstamon, because it partly does not behave like a normally windowed application. This is still under construction.

So if you could use Xorg as well this might be no fix but a workaround. By the way Nagstamon is the only reason why I still use Xorg.

**Comment by dacrhu** [comment]
Then I'll wait patiently.

**Comment by fluffysatoshi** [comment]
#880

Fixed the the issue for me. EWMH Hints are not awailable under Wayland.

`xdg-shell` might be used to get the EWMH functionality under Wayland.

**Comment by HenriWahl** [comment]
How do you use `xdg-shell` in this context?
