### ISSUE TITLE
crash: AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by drook** [HenriWahl/Nagstamon#891]
3.10.1 sometimes (when there's an authentication problem with an already configured source) crashes on start with 

````
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/Nagstamon/QUI/__init__.py", line 4015, in get_status
status = self.server.GetStatus()
File "/usr/local/lib/python3.9/site-packages/Nagstamon/Servers/Generic.py", line 897, in GetStatus
self.init_HTTP()
File "/usr/local/lib/python3.9/site-packages/Nagstamon/Servers/IcingaWeb2.py", line 107, in init_HTTP
if not form.find('input', {'name': form_input}) is None:
AttributeError: 'NoneType' object has no attribute 'find'
zsh: abort (core dumped)  nagstamon.py
````

This can be easy fixed by changing line 107 in Nagstamon/Servers/IcingaWeb2.py from
````
if not form.find('input', {'name': form_input}) is None:
````
to
````
if form is not None and not form.find('input', {'name': form_input}) is None:
````

**Comment by HenriWahl** [comment]
@drook thanks for the hint - must have been lost over Christmas. Could you please supply a pull request?

**Comment by HenriWahl** [comment]
@drook done in latest release 3.11-20230122 - please check if it still works at https://github.com/HenriWahl/Nagstamon/releases/tag/latest
