### ISSUE TITLE
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: Not logged in

### ISSUE THREAD

**Issue by bb2k** [HenriWahl/Nagstamon#901]
After upgrading in zabbix 6.4beta5 we 're facing an issue login to zabbix API.

Each Try raise an exception with a 'Not Logged In Error'. In the debug we Have : 

I'm using nagstamon 3.11

```
10: Trying to login with 'Admin':'sha256(813bxxxxx0b0f7e1d717e2073abc02ea26a0a200b9fccbcc5268)'
10: json_obj: {'jsonrpc': '2.0', 'method': 'user.login', 'params': {'user': 'Admin', 'password': 'xxxxxx'}, 'id': 15}
20: Sending: {"jsonrpc": "2.0", "method": "user.login", "params": {"user": "Admin", "password": "xxxxx"}, "id": 15}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'error': {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter "/": unexpected parameter "user".'}, 'id': 15}
(<class 'Nagstamon.thirdparty.zabbix_api.ZabbixAPIException'>, ZabbixAPIException('Not logged in.'), <traceback object at 0x7f81240929c0>)
ERROR: 2023-01-30 14:48:04.466208 Zabbix Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 93, in _login
    self.zapi.login(self.username, self.password)
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 209, in login
    result = self.do_request(obj)
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 291, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: ('Error -32602: Invalid params., Invalid parameter "/": unexpected parameter "user". while sending {"jsonrpc": "2.0", "method": "user.login", "params": {"user": "Admin", "password": "PouetPouet"}, "id": 15}', -32602)

ERROR: 2023-01-30 14:48:04.466623 Zabbix Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 138, in _get_status
    api_version = int(''.join(self.zapi.api_version().split('.')[:-1])) # Make API Version smaller
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 300, in api_version
    self.__checkauth__()
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 306, in __checkauth__
    raise ZabbixAPIException("Not logged in.")
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: Not logged in.
```

thx !

**Comment by bb2k** [comment]
I found the solution in the zabiix jira App : 
  https://support.zabbix.com/browse/ZBX-22251
  
The parameter "user" is now "username" 

here is a patch : 
```
--- zabbix_api.py       2023-01-30 12:05:40.428190572 +0100
+++ zabbix_api_new.py   2023-01-31 16:06:49.957684063 +0100
@@ -204,7 +204,7 @@
         hashed_pw_string = "sha256(" + hashlib.sha256(l_password.encode('utf-8')).hexdigest() + ")"
         self.debug(logging.DEBUG, "Trying to login with %s:%s" %
                 (repr(l_user), repr(hashed_pw_string)))
-        obj = self.json_obj('user.login', {'user': l_user, 'password': l_password}, auth=False)
+        obj = self.json_obj('user.login', {'username': l_user, 'password': l_password}, auth=False)
 
         result = self.do_request(obj)
         self.auth = result['result']

```

**Comment by sebhofmann** [comment]
I have the same error. I can not confirm if the solution works, because i am not able to build the project.

**Comment by sebhofmann** [comment]
I could repoduce now. The file Nagstamon/Servers/ZabbixProblemBased.py also needs to be patched, because the problem base approach has its own api.

**Comment by HenriWahl** [comment]
@sebhofmann could you check if this would still work if BOTH variants would be submitted to keep backward compatibility? Like:
```
  obj = self.json_obj('user.login', {'username': l_user, 'user': l_user, 'password': l_password}, auth=False)
```

**Comment by sebhofmann** [comment]
@HenriWahl unfortunately this does not work
```
curl -X POST -H "Content-Type:application/json" -d '{
            "jsonrpc": "2.0",
            "method": "user.login",            
            "params": { "user": "testuser", "username": "testuser", "password": "xxxxxxxxxx"},
            "id": 0
        }                                          
' https://zabbix.xxx.de/api_jsonrpc.php


{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params.","data":"Parameter \"user\" is deprecated."},"id":0}
```

**Comment by HenriWahl** [comment]
@mprenditore what do you think about version detection?

**Comment by HenriWahl** [comment]
@bb2k @sebhofmann  I added version detection at login and now it may work again - can you please test the latest testing release from https://github.com/HenriWahl/Nagstamon/releases/tag/latest?

**Comment by sebhofmann** [comment]
@HenriWahl It works for me. Thank you!

**Comment by kkrebs** [comment]
I tested the windows version with zabbix 6.0.13 and it works for me as well. Thanks!

**Comment by bb2k** [comment]
Sorry i was on holliday ! 
That's perfect ! Thx for all !
