### ISSUE TITLE
After upgrading to zabbix 6.4 the connection to the api stopped working

### ISSUE THREAD

**Issue by jcayrbp** [HenriWahl/Nagstamon#922]
ERROR: 2023-03-20 14:45:59.730351 Monitor server Traceback (most recent call last):
  File "Nagstamon\Servers\Zabbix.py", line 93, in _login
  File "Nagstamon\thirdparty\zabbix_api.py", line 208, in login
  File "Nagstamon\thirdparty\zabbix_api.py", line 290, in do_request
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: ('Error -32602: Invalid params., Invalid parameter "/": unexpected parameter "user". while sending {"jsonrpc": "2.0", "method": "user.login", "params": {"user": "XXXXX", "password": "XXXXXX"}, "id": 155}', -32602)

ERROR: 2023-03-20 14:45:59.731350 Monitor server Traceback (most recent call last):
  File "Nagstamon\Servers\Zabbix.py", line 138, in _get_status
  File "Nagstamon\thirdparty\zabbix_api.py", line 299, in api_version
  File "Nagstamon\thirdparty\zabbix_api.py", line 305, in __checkauth__
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: Not logged in.

**Comment by HenriWahl** [comment]
@jcayrbp they changed their login with 6.4, please check with latest testing release of Nagstamon.

**Comment by jcayrbp** [comment]
3.1120230209 Working fine. Thanks!
