### ISSUE TITLE
windows 10 nagstamon 3.11 crash

### ISSUE THREAD

**Issue by andershagman** [HenriWahl/Nagstamon#931]
Have installed 3.11 but it does not start at all.
No log, no nothing.

**Comment by HenriWahl** [comment]
@andershagman @sronline you both use Zabbix? If so, which versions?
Could you anyway try the debug version https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.11-20230331-win64_debug.zip to get more output?

**Comment by sronline** [comment]
D:\Apps\Nagstamon>cmd /k nagstamon.exe
Traceback (most recent call last):
  File "nagstamon.py", line 38, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "Nagstamon\Helpers.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "psutil\__init__.py", line 241, in <module>
ImportError: version conflict: 'D:\\Apps\\Nagstamon\\psutil\\_psutil_windows.cp310-win_amd64.pyd' C extension module was built for another version of psutil (5.9.3 instead of 5.9.4); you may try to 'pip uninstall psutil', manually remove D:\Apps\Nagstamon\psutil\_psutil_windows.cp310-win_amd64.pyd or clean the virtual env somehow, then reinstall

After I cleaned the whole directory, and placed only the files from the zip it works

**Comment by HenriWahl** [comment]
Was it a clean install before?

**Comment by HenriWahl** [comment]
@sronline @andershagman meanwhile there is the 3.12.0 release published. Did you try that one?

**Comment by sronline** [comment]
thank you very much, the release 3.12.0 works (I cleaned the old directory before)

**Comment by HenriWahl** [comment]
@andershagman so this problems persists?
