### ISSUE TITLE
MacOS and 3.12.0

### ISSUE THREAD

**Issue by penguruh** [HenriWahl/Nagstamon#938]
Hi all, 
i have a connection issue with 3.12.0 and check-mk 2.0.0.p33, debug logs looks like 

ERROR: 2023-05-11 07:25:14.476578 BDS cmk Traceback (most recent call last):
  File "urllib3/connection.py", line 200, in _new_conn
  File "urllib3/util/connection.py", line 85, in create_connection
  File "urllib3/util/connection.py", line 73, in create_connection
OSError: [Errno 9] Bad file descriptor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 790, in urlopen
  File "urllib3/connectionpool.py", line 491, in _make_request
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "urllib3/connectionpool.py", line 1092, in _validate_conn
  File "urllib3/connection.py", line 604, in connect
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x121401550>: Failed to establish a new connection: [Errno 9] Bad file descriptor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 844, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxx', port=443): Max retries exceeded with url: /ccc_master/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x121401550>: Failed to establish a new connection: [Errno 9] Bad file descriptor'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Nagstamon/Servers/Generic.py", line 1485, in FetchURL
  File "requests/sessions.py", line 600, in get
  File "requests/sessions.py", line 587, in request
  File "requests/sessions.py", line 701, in send
  File "requests/adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xxx', port=443): Max retries exceeded with url: /ccc_master/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x121401550>: Failed to establish a new connection: [Errno 9] Bad file descriptor'))

DEBUG: 2023-05-11 07:26:14.595706 BDS cmk FetchURL: https://xxx/ccc_master/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
ERROR: 2023-05-11 07:26:14.617817 BDS cmk Traceback (most recent call last):
  File "urllib3/connection.py", line 200, in _new_conn
  File "urllib3/util/connection.py", line 85, in create_connection
  File "urllib3/util/connection.py", line 73, in create_connection
OSError: [Errno 9] Bad file descriptor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 790, in urlopen
  File "urllib3/connectionpool.py", line 491, in _make_request
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "urllib3/connectionpool.py", line 1092, in _validate_conn
  File "urllib3/connection.py", line 604, in connect
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1214019d0>: Failed to establish a new connection: [Errno 9] Bad file descriptor

Client is MacOS 13.3.1

any idea's what I can do? 

regards,
Patrick

**Comment by HenriWahl** [comment]
Hi  @penguruh ,
strange error. I have the 3.12.0 running on macOS 13.3.1(a) without problems.
This error `urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x121401550>: Failed to establish a new connection: [Errno 9] Bad file descriptor` looks or feels like some permission problem?
Might it be possible that there is some kind of restriction applied to the Nagstamon app?
