### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by multee35** [HenriWahl/Nagstamon#954]
Hello,

I can't connect Nagstamon 3.12.0 to Centreon 22.04.4. In the Log file I got :

``ERROR: 2023-07-26 14:56:08.247367 CENTREON-EMS Traceback (most recent call last):
  File "Nagstamon\Servers\Centreon\CentreonAPI.py", line 751, in check_session
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)``

I dont know where it comes from please help

**Comment by multee35** [comment]
I've found my problem. I didn't have the API right even if doing calls manualy on browser worked.
