### ISSUE TITLE
Nagstamon 3.12.0 on Windows - File "<string>", line 3

### ISSUE THREAD

**Issue by trcmd9000** [HenriWahl/Nagstamon#957]
Hi Henri,
after waking up from standby, nagstamon displays the error `File "<string>", line 3`. A simple restart of nagstamon makes the error disappear. This is issue can be reproduced. This is the debug output. I have included the 'go to sleep' (="connection aborted") and 'wake up' time.

> Traceback (most recent call last):
>   File "Nagstamon\Servers\Generic.py", line 1485, in FetchURL
>   File "requests\sessions.py", line 600, in get
>   File "requests\sessions.py", line 587, in request
>   File "requests\sessions.py", line 723, in send
>   File "requests\sessions.py", line 723, in <listcomp>
> requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> DEBUG: 2023-08-11 08:57:11.164251 checkmk FetchURL: https://host.domain.local/monitoring/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
> DEBUG: 2023-08-11 08:57:11.786150 checkmk FetchURL: https://host.domain.local/monitoring/check_mk/view.py?view_name=nagstamon_svc&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1&hst0=On&hst1=On CGI Data: None
> ERROR: 2023-08-11 08:57:12.501427 checkmk Traceback (most recent call last):
>   File "Nagstamon\Servers\Multisite.py", line 312, in _get_status
>   File "Nagstamon\Servers\Multisite.py", line 197, in _get_url
>   File "<string>", line 3
>     
>     ^
> SyntaxError: invalid syntax

Best regards

**Comment by HenriWahl** [comment]
@trcmd9000 which version of Nagstamon do you use?

**Comment by trcmd9000** [comment]
3.12 :)

**Comment by HenriWahl** [comment]
Ah, yes, I see... 🤪
Can you try a later testing release?

**Comment by trcmd9000** [comment]
Will do and report back

**Comment by trcmd9000** [comment]
Have reproduced the issue with 3.13-202308080.

**Comment by HenriWahl** [comment]
@trcmd9000 sorry for the late reply. What monitoring server do you use?

**Comment by trcmd9000** [comment]
checkmk Multisite

**Comment by HenriWahl** [comment]
Seems to be connected to https://github.com/HenriWahl/Nagstamon/issues/952

**Comment by HenriWahl** [comment]
@trcmd9000 did you meanwhile update your Checkmk instance? Looked like does not happen with newer instances.

**Comment by HenriWahl** [comment]
Not sure if still relevant.
