### ISSUE TITLE
ModuleNotFoundError: No module named 'sspi.raw._text'

### ISSUE THREAD

**Issue by nona00** [HenriWahl/Nagstamon#968]
I tried Nagstamon-3.13-20230927-win64_debug.zip. The application shows the following error at startup:

C:\Apps\Nagstamon>cmd /k nagstamon.exe
Traceback (most recent call last):
  File "Nagstamon\Servers\Generic.py", line 78, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "requests_kerberos\__init__.py", line 17, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "requests_kerberos\kerberos_.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "spnego\__init__.py", line 26, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "spnego\auth.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "spnego\_negotiate.py", line 31, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "spnego\_sspi.py", line 39, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "sspi\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "sspi\raw\__init__.py", line 8, in <module>
  File "src\\sspi\\raw\\_context_attributes.pyx", line 1, in init sspi.raw._context_attributes
  File "src\\sspi\\raw\\_security_context.pyx", line 1, in init sspi.raw._security_context
  File "src\\sspi\\raw\\_credential.pyx", line 1, in init sspi.raw._credential
ModuleNotFoundError: No module named 'sspi.raw._text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nagstamon.py", line 45, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "Nagstamon\QUI\__init__.py", line 53, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "Nagstamon\Servers\__init__.py", line 36, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "Nagstamon\Servers\Nagios.py", line 20, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "Nagstamon\Servers\Generic.py", line 80, in <module>
ModuleNotFoundError: No module named 'requests_gssapi'

**Comment by HenriWahl** [comment]
@nona00 do you use Kerberos authentication?

**Comment by HenriWahl** [comment]
Please try latest 3.13-20231010 - not sure if it would work WITH Kerberos but it does at least WITHOUT.

**Comment by nona00** [comment]
I'm not using kerberos. The new version Nagstamon-3.13-20231010-win64 is starting :-)
