### ISSUE TITLE
Error since IcingaDB-Web 1.1

### ISSUE THREAD

**Issue by Tontonitch** [HenriWahl/Nagstamon#970]
Tested compatibility with the fresh new version of icingadb-web (https://github.com/Icinga/icingadb-web)

![image](https://github.com/HenriWahl/Nagstamon/assets/600025/367d0c8d-f27a-428e-a03d-54db8628586d)

Debug:
```
Traceback (most recent call last):
  File "Nagstamon\Servers\IcingaDBWeb.py", line 211, in _get_status
ValueError: could not convert string to float: '2023-09-28T20:50:02.582+00:00'
DEBUG: 2023-09-28 23:02:43.730600 xxxx FetchURL: https://xxxx/icingaweb2/icingadb/hosts?host.state.is_problem=y&host.state.state_type=hard&columns=host.state.last_update&format=json CGI Data: None
ERROR: 2023-09-28 23:02:43.777469 xxxx Traceback (most recent call last):
  File "Nagstamon\Servers\IcingaDBWeb.py", line 211, in _get_status
ValueError: could not convert string to float: '2023-09-28T20:50:02.582+00:00'
```

tested with latest dev nagstamon 3.13 + 3.10.1.

**Comment by Tontonitch** [comment]
Duplicate of #962
